
CREATE TABLE [bld].[contact] ([contactid] INT IDENTITY (1,
                                                        1) NOT NULL,
                                                           [bk] VARCHAR (255) NULL,
                                                                              [code] VARCHAR (255) NULL,
                                                                                                   [bk_contactgroup] VARCHAR (255) NULL,
                                                                                                                                   [contactgroup] VARCHAR (255) NULL,
                                                                                                                                                                [contactrole] VARCHAR (255) NULL,
                                                                                                                                                                                            [main_contact] VARCHAR (255) NULL,
                                                                                                                                                                                                                         [alert_contact] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                       [contactperson_name] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                                          [contactperson_department] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                                   [contacperson_phonenumber] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                                                                            [contactperson_mailadress] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                     [contactperson_active] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                          [rn_contact] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     [mta_createdate] datetime2 (7) DEFAULT (getdate()) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        [mta_rectype] SMALLINT DEFAULT ((1)) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             [mta_bk] CHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 [mta_bkh] CHAR (128) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      [mta_rh] CHAR (128) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          [mta_source] VARCHAR (255) NULL);GO
CREATE UNIQUE nonclustered INDEX [uix_bld_contact]
    ON [bld].[contact]([mta_bkh] DESC, [mta_rh] DESC, [mta_createdate] DESC);GO
CREATE clustered INDEX [cix_bld_contact]
    ON [bld].[contact]([bk] ASC, [mta_bkh] ASC, [code] ASC, [mta_rh] ASC, [mta_createdate] DESC);
