
CREATE TABLE [bld].[dwhreftemplates] ([dwhreftemplatesid] INT IDENTITY (1,
                                                                        1) NOT NULL,
                                                                           [bk] VARCHAR (255) NULL,
                                                                                              [code] VARCHAR (255) NULL,
                                                                                                                   [bk_template] VARCHAR (255) NULL,
                                                                                                                                               [bk_dataset] VARCHAR (255) NULL,
                                                                                                                                                                          [templatetype] VARCHAR (255) NULL,
                                                                                                                                                                                                       [templatesource] VARCHAR (255) NULL,
                                                                                                                                                                                                                                      [bk_reftype_objecttype] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                            [templatescript] VARCHAR (MAX) NULL,
                                                                                                                                                                                                                                                                                                           [templateversion] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                                           [rownum] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                                                                  [mta_createdate] datetime2 (7) DEFAULT (getdate()) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                     [mta_rectype] SMALLINT DEFAULT ((1)) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                          [mta_bk] CHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              [mta_bkh] CHAR (128) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   [mta_rh] CHAR (128) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       [mta_source] VARCHAR (255) NULL);GO
CREATE UNIQUE nonclustered INDEX [uix_bld_dwhreftemplates]
    ON [bld].[dwhreftemplates]([mta_bkh] DESC, [mta_rh] DESC, [mta_createdate] DESC);GO
CREATE clustered INDEX [cix_bld_dwhreftemplates]
    ON [bld].[dwhreftemplates]([bk] ASC, [mta_bkh] ASC, [code] ASC, [mta_rh] ASC, [mta_createdate] DESC);
