
CREATE TABLE [bld].[flow] ([flowid] INT IDENTITY (1,
                                                  1) NOT NULL,
                                                     [bk] VARCHAR (255) NULL,
                                                                        [code] VARCHAR (255) NULL,
                                                                                             [bk_flow] VARCHAR (255) NULL,
                                                                                                                     [flow_name] VARCHAR (255) NULL,
                                                                                                                                               [flow_description] VARCHAR (255) NULL,
                                                                                                                                                                                [flow_layer_step_name] VARCHAR (255) NULL,
                                                                                                                                                                                                                     [flow_layer_step_description] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                 [flow_layer_step_order] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                                                       [bk_layer] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                                [bk_schema] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                                                          [readfromview] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                                                                                       [bk_template_load] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                        [bk_template_create] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                           [mta_createdate] datetime2 (7) DEFAULT (getdate()) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              [mta_rectype] SMALLINT DEFAULT ((1)) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   [mta_bk] CHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       [mta_bkh] CHAR (128) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            [mta_rh] CHAR (128) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                [mta_source] VARCHAR (255) NULL);GO
CREATE UNIQUE nonclustered INDEX [uix_bld_flow]
    ON [bld].[flow]([mta_bkh] DESC, [mta_rh] DESC, [mta_createdate] DESC);GO
CREATE clustered INDEX [cix_bld_flow]
    ON [bld].[flow]([bk] ASC, [mta_bkh] ASC, [code] ASC, [mta_rh] ASC, [mta_createdate] DESC);
