
CREATE TABLE [bld].[layer] ([layerid] INT IDENTITY (1,
                                                    1) NOT NULL,
                                                       [bk] VARCHAR (255) NULL,
                                                                          [code] VARCHAR (255) NULL,
                                                                                               [layer_name] VARCHAR (255) NULL,
                                                                                                                          [layer_desciption] VARCHAR (255) NULL,
                                                                                                                                                           [isdwhhelper] VARCHAR (255) NULL,
                                                                                                                                                                                       [isrep] VARCHAR (255) NULL,
                                                                                                                                                                                                             [isaudit] VARCHAR (255) NULL,
                                                                                                                                                                                                                                     [issrc] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                           [isdwh] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                                 [istgt] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                                                       [layer_process_order] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                                           [mta_createdate] datetime2 (7) DEFAULT (getdate()) NULL,
                                                                                                                                                                                                                                                                                                                                                                                              [mta_rectype] SMALLINT DEFAULT ((1)) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                   [mta_bk] CHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                       [mta_bkh] CHAR (128) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            [mta_rh] CHAR (128) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                [mta_source] VARCHAR (255) NULL);GO
CREATE UNIQUE nonclustered INDEX [uix_bld_layer]
    ON [bld].[layer]([mta_bkh] DESC, [mta_rh] DESC, [mta_createdate] DESC);GO
CREATE clustered INDEX [cix_bld_layer]
    ON [bld].[layer]([bk] ASC, [mta_bkh] ASC, [code] ASC, [mta_rh] ASC, [mta_createdate] DESC);
