
CREATE TABLE [bld].[markers] ([markersid] INT IDENTITY (1,
                                                        1) NOT NULL,
                                                           [bk] VARCHAR (255) NULL,
                                                                              [bk_dataset] VARCHAR (255) NULL,
                                                                                                         [code] VARCHAR (255) NULL,
                                                                                                                              [markertype] VARCHAR (255) NULL,
                                                                                                                                                         [markerdescription] VARCHAR (255) NULL,
                                                                                                                                                                                           [marker] VARCHAR (255) NULL,
                                                                                                                                                                                                                  [markervalue] VARCHAR (MAX) NULL,
                                                                                                                                                                                                                                              [pre] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                  [post] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                                       [markerversion] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                     [mta_createdate] datetime2 (7) DEFAULT (getdate()) NULL,
                                                                                                                                                                                                                                                                                                                                                                        [mta_rectype] SMALLINT DEFAULT ((1)) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                             [mta_bk] CHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                 [mta_bkh] CHAR (128) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                      [mta_rh] CHAR (128) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          [mta_source] VARCHAR (255) NULL);GO
CREATE UNIQUE nonclustered INDEX [uix_bld_markers]
    ON [bld].[markers]([mta_bkh] DESC, [mta_rh] DESC, [mta_createdate] DESC);GO
CREATE clustered INDEX [cix_bld_markers]
    ON [bld].[markers]([bk] ASC, [mta_bkh] ASC, [code] ASC, [mta_rh] ASC, [mta_createdate] DESC);
