
CREATE TABLE [bld].[template] ([templateid] INT IDENTITY (1,
                                                          1) NOT NULL,
                                                             [bk] VARCHAR (255) NULL,
                                                                                [code] VARCHAR (255) NULL,
                                                                                                     [templatename] VARCHAR (255) NULL,
                                                                                                                                  [templatetype] VARCHAR (255) NULL,
                                                                                                                                                               [templatedecription] VARCHAR (255) NULL,
                                                                                                                                                                                                  [objecttype] VARCHAR (255) NULL,
                                                                                                                                                                                                                             [objecttypedeployorder] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                   [script] VARCHAR (MAX) NULL,
                                                                                                                                                                                                                                                                                          [scriptlanguagecode] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                             [scriptlanguage] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                                                            [objectname] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                                                                                       [bk_reftype_templatetype] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                               [bk_reftype_objecttype] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     [bk_reftype_objecttype_basedon] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   [bk_reftype_scriptlanguage] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             [templateversion] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             [mta_createdate] datetime2 (7) DEFAULT (getdate()) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                [mta_rectype] SMALLINT DEFAULT ((1)) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     [mta_bk] CHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         [mta_bkh] CHAR (128) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              [mta_rh] CHAR (128) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  [mta_source] VARCHAR (255) NULL);GO
CREATE UNIQUE nonclustered INDEX [uix_bld_template]
    ON [bld].[template]([mta_bkh] DESC, [mta_rh] DESC, [mta_createdate] DESC);GO
CREATE clustered INDEX [cix_bld_template]
    ON [bld].[template]([bk] ASC, [mta_bkh] ASC, [code] ASC, [mta_rh] ASC, [mta_createdate] DESC);
