
CREATE TABLE [bld].[testrules] ([testrulesid] INT IDENTITY (1,
                                                            1) NOT NULL,
                                                               [code] VARCHAR (255) NULL,
                                                                                    [bk] VARCHAR (255) NULL,
                                                                                                       [bk_dataset] VARCHAR (255) NULL,
                                                                                                                                  [bk_reftype_repositorystatus] VARCHAR (255) NULL,
                                                                                                                                                                              [testdefintion] VARCHAR (255) NULL,
                                                                                                                                                                                                            [adfpipeline] VARCHAR (255) NULL,
                                                                                                                                                                                                                                        [getattributes] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                      [tresholdvalue] VARCHAR (MAX) NULL,
                                                                                                                                                                                                                                                                                                    [specificattribute] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                                      [attributename] VARCHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                                                                    [expectedvalue] VARCHAR (MAX) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                  [mta_createdate] datetime2 (7) DEFAULT (getdate()) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                     [mta_rectype] SMALLINT DEFAULT ((1)) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          [mta_bk] CHAR (255) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              [mta_bkh] CHAR (128) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   [mta_rh] CHAR (128) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       [mta_source] VARCHAR (255) NULL);GO
CREATE UNIQUE nonclustered INDEX [uix_bld_testrules]
    ON [bld].[testrules]([mta_bkh] DESC, [mta_rh] DESC, [mta_createdate] DESC);GO
CREATE clustered INDEX [cix_bld_testrules]
    ON [bld].[testrules]([bk] ASC, [mta_bkh] ASC, [code] ASC, [mta_rh] ASC, [mta_createdate] DESC);
