CREATE TABLE [adf].[DWH_Date] (
    [DateKey]                INT           NOT NULL,
    [TheDate]                DATE          NULL,
    [TheDay]                 INT           NULL,
    [TheDaySuffix]           CHAR (2)      NULL,
    [TheDayName]             VARCHAR (30)  NULL,
    [TheDayOfWeek]           INT           NULL,
    [TheDayOfWeekInMonth]    TINYINT       NULL,
    [TheDayOfYear]           INT           NULL,
    [IsWeekend]              INT           NOT NULL,
    [IsWorkDay]              INT           NOT NULL,
    [WorkdayOfMonth]         INT           NOT NULL,
    [TheWeek]                INT           NULL,
    [TheISOweek]             INT           NULL,
    [TheFirstOfWeek]         DATE          NULL,
    [TheLastOfWeek]          DATE          NULL,
    [TheWeekOfMonth]         TINYINT       NULL,
    [TheMonth]               INT           NULL,
    [TheMonthName]           VARCHAR (30)  NULL,
    [TheFirstWorkDayOfMonth] DATE          NULL,
    [TheFirstOfMonth]        DATE          NULL,
    [TheLastWorkDayOfMonth]  DATE          NULL,
    [TheLastOfMonth]         DATE          NULL,
    [TheFirstOfNextMonth]    DATE          NULL,
    [TheLastOfNextMonth]     DATE          NULL,
    [TheQuarter]             INT           NULL,
    [TheFirstOfQuarter]      DATE          NULL,
    [TheLastOfQuarter]       DATE          NULL,
    [TheYear]                INT           NULL,
    [TheISOYear]             INT           NULL,
    [TheFirstOfYear]         DATE          NULL,
    [TheLastOfYear]          DATE          NULL,
    [IsLeapYear]             BIT           NULL,
    [Has53Weeks]             INT           NOT NULL,
    [Has53ISOWeeks]          INT           NOT NULL,
    [MMYYYY]                 CHAR (6)      NULL,
    [Style101]               CHAR (10)     NULL,
    [Style103]               CHAR (10)     NULL,
    [Style112]               CHAR (8)      NULL,
    [Style120]               CHAR (10)     NULL,
    [YearWeek]               CHAR (6)      NULL,
    [YearISOWeek]            CHAR (6)      NULL,
    [YearMonth]              CHAR (6)      NULL,
    [HolidayName]            VARCHAR (255) NULL,
    [IsBankHoliday]          INT           NULL,
    [IsPublicHoliday]        INT           NULL,
    [HolidayName_NL]         VARCHAR (255) NULL,
    [TheDayName_NL]          VARCHAR (255) NULL,
    [TheMonthName_NL]        VARCHAR (255) NULL,
    [DayCounter]             BIGINT        NULL,
    [WorkDayCounter]         BIGINT        NULL
);

