
CREATE TABLE [adf].[jobs]
  ([jobid] AS (convert([nvarchar](900), concat_ws('|', [flowid], [jobname]))) persisted NOT NULL,
                                                                                        [jobname] NVARCHAR (280) NOT NULL,
                                                                                                                 [jobdescription] NVARCHAR (MAX) NOT NULL,
                                                                                                                                                 [flowid] NVARCHAR (900) NOT NULL,
                                                                                                                                                                         [jobtype] NVARCHAR (MAX) NOT NULL,
                                                                                                                                                                                                  [jobgroup] NVARCHAR (MAX) NOT NULL,
                                                                                                                                                                                                                            [joborder] INT NOT NULL,
                                                                                                                                                                                                                                           [lastrunduration] INT NULL,
                                                                                                                                                                                                                                                                 [lastrunstart] datetime2 (7) NULL,
                                                                                                                                                                                                                                                                                              [lastrunstatus] NVARCHAR (10) NULL,
                                                                                                                                                                                                                                                                                                                            [checkpoint] datetime2 (7) NULL,
                                                                                                                                                                                                                                                                                                                                                       CONSTRAINT [pk_jobid] PRIMARY KEY clustered ([jobid] ASC),
                                                                                                                                                                                                                                                                                                                                                                                         CONSTRAINT [fk_jobs_flowid]
   FOREIGN KEY ([flowid]) REFERENCES [adf].[flows] ([flowid]) ON DELETE CASCADE ON UPDATE CASCADE);