
CREATE TABLE [adf].[projectparameters]
  ([projectparameterid] AS (convert([nvarchar](900), concat_ws('|', [projectid], [projectparameterjobtype], [projectparametername]))) persisted NOT NULL,
                                                                                                                                                [projectparametername] NVARCHAR (280) NULL,
                                                                                                                                                                                      [projectparametervalue] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                                             [projectparameterjobtype] NVARCHAR (280) NULL,
                                                                                                                                                                                                                                                                      [projectparameterdescription] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                                                                                                                                   [projectid] NVARCHAR (900) NULL,
                                                                                                                                                                                                                                                                                                                                              CONSTRAINT [pk_projectparameters] PRIMARY KEY clustered ([projectparameterid] ASC),
                                                                                                                                                                                                                                                                                                                                                                                            CONSTRAINT [fk_projectparameters_projectid]
   FOREIGN KEY ([projectid]) REFERENCES [adf].[projects] ([projectid]) ON DELETE CASCADE ON UPDATE CASCADE);