
    CREATE   VIEW [rep].[vw_LinkedServiceProperties] AS
    /*
    View is generated by  : metro
    Generated at          : 2025-01-06 16:02:26
    Description           : View on stage table
    */
    SELECT 
        -- List of columns:
        LTRIM(RTRIM(CAST([BK] as varchar(255)))) as [BK], LTRIM(RTRIM(CAST([Code] as varchar(255)))) as [Code], LTRIM(RTRIM(CAST([Name] as varchar(255)))) as [Name], LTRIM(RTRIM(CAST([Description] as varchar(255)))) as [Description], LTRIM(RTRIM(CAST([BK_LinkedService] as varchar(255)))) as [BK_LinkedService], LTRIM(RTRIM(CAST([LinkedServicePropertiesName] as varchar(255)))) as [LinkedServicePropertiesName], LTRIM(RTRIM(CAST([LinkedServicePropertiesValue] as varchar(max)))) as [LinkedServicePropertiesValue], LTRIM(RTRIM(CAST([LinkedServicePropertiesDesc] as varchar(max)))) as [LinkedServicePropertiesDesc], LTRIM(RTRIM(CAST([Active] as varchar(255)))) as [Active], LTRIM(RTRIM(CAST([IsSystem] as varchar(255)))) as [IsSystem], LTRIM(RTRIM(CAST([BK_RefType_RepositoryStatus] as varchar(255)))) as [BK_RefType_RepositoryStatus], LTRIM(RTRIM(CAST([mta_Source] as varchar(255)))) as [mta_Source], LTRIM(RTRIM(CAST([mta_LoadDate] as varchar(255)))) as [mta_LoadDate],
        -- Meta data columns:
        mta_RowNum     = ROW_NUMBER() OVER (ORDER BY [BK] ASC),
        mta_BK         = UPPER(ISNULL(LTRIM(RTRIM(CAST([BK] AS VARCHAR(500)))),'-')),
        mta_BKH        = CONVERT(CHAR(64), HASHBYTES('SHA2_512', UPPER(ISNULL(LTRIM(RTRIM(CAST([BK] AS VARCHAR(500)))),'-'))), 2),
        mta_RH         = CONVERT(CHAR(64), HASHBYTES('SHA2_512', UPPER(ISNULL(LTRIM(RTRIM(CAST([BK] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([Code] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([Name] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([Description] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([BK_LinkedService] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([LinkedServicePropertiesName] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([LinkedServicePropertiesValue] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([LinkedServicePropertiesDesc] AS VARCHAR(8000)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([Active] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([IsSystem] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([BK_RefType_RepositoryStatus] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([mta_Source] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([mta_LoadDate] AS VARCHAR(255)))),'-'))), 2)
    FROM [rep].[LinkedServiceProperties]
    WHERE 1=1 and 1=1
      AND ISNULL(Active,'1') = '1'
      AND ISNULL(LTRIM(RTRIM([BK])),'') != ''