
    CREATE   VIEW [rep].[vw_MtaAttribute] AS
    /*
    View is generated by  : metro
    Generated at          : 2025-01-06 16:02:26
    Description           : View on stage table
    */
    SELECT 
        -- List of columns:
        LTRIM(RTRIM(CAST([BK] as varchar(255)))) as [BK], LTRIM(RTRIM(CAST([Code] as varchar(255)))) as [Code], LTRIM(RTRIM(CAST([Active] as varchar(255)))) as [Active], LTRIM(RTRIM(CAST([BK_Schema] as varchar(255)))) as [BK_Schema], LTRIM(RTRIM(CAST([BK_RefType_ObjectType] as varchar(255)))) as [BK_RefType_ObjectType], LTRIM(RTRIM(CAST([Name] as varchar(255)))) as [Name], LTRIM(RTRIM(CAST([Description] as varchar(255)))) as [Description], LTRIM(RTRIM(CAST([BK_RefType_DataType] as varchar(255)))) as [BK_RefType_DataType], LTRIM(RTRIM(CAST([Isnullable] as varchar(255)))) as [Isnullable], LTRIM(RTRIM(CAST([OrdinalPosition] as varchar(255)))) as [OrdinalPosition], LTRIM(RTRIM(CAST([MaximumLength] as varchar(255)))) as [MaximumLength], LTRIM(RTRIM(CAST([Precision] as varchar(255)))) as [Precision], LTRIM(RTRIM(CAST([Scale] as varchar(255)))) as [Scale], LTRIM(RTRIM(CAST([Default] as varchar(255)))) as [Default], LTRIM(RTRIM(CAST([ComputedColumn] as varchar(255)))) as [ComputedColumn], LTRIM(RTRIM(CAST([ComputedColumnPersisted] as varchar(255)))) as [ComputedColumnPersisted], LTRIM(RTRIM(CAST([IsSystem] as varchar(255)))) as [IsSystem], LTRIM(RTRIM(CAST([mta_Source] as varchar(255)))) as [mta_Source], LTRIM(RTRIM(CAST([mta_LoadDate] as varchar(255)))) as [mta_LoadDate],
        -- Meta data columns:
        mta_RowNum     = ROW_NUMBER() OVER (ORDER BY [BK] ASC),
        mta_BK         = UPPER(ISNULL(LTRIM(RTRIM(CAST([BK] AS VARCHAR(500)))),'-')),
        mta_BKH        = CONVERT(CHAR(64), HASHBYTES('SHA2_512', UPPER(ISNULL(LTRIM(RTRIM(CAST([BK] AS VARCHAR(500)))),'-'))), 2),
        mta_RH         = CONVERT(CHAR(64), HASHBYTES('SHA2_512', UPPER(ISNULL(LTRIM(RTRIM(CAST([BK] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([Code] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([Active] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([BK_Schema] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([BK_RefType_ObjectType] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([Name] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([Description] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([BK_RefType_DataType] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([Isnullable] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([OrdinalPosition] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([MaximumLength] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([Precision] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([Scale] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([Default] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([ComputedColumn] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([ComputedColumnPersisted] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([IsSystem] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([mta_Source] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([mta_LoadDate] AS VARCHAR(255)))),'-'))), 2)
    FROM [rep].[MtaAttribute]
    WHERE 1=1 and 1=1
      AND ISNULL(Active,'1') = '1'
      AND ISNULL(LTRIM(RTRIM([BK])),'') != ''