
CREATE VIEW [rep].[vw_mtaattribute] AS /*
    View is generated by  : metro
    Generated at          : 2025-01-06 16:02:26
    Description           : View on stage table
    */
SELECT -- List of columns:
 ltrim(rtrim(cast([bk] AS varchar(255)))) AS [bk],

       ltrim(rtrim(cast([code] AS varchar(255)))) AS [code],

       ltrim(rtrim(cast([active] AS varchar(255)))) AS [active],

       ltrim(rtrim(cast([bk_schema] AS varchar(255)))) AS [bk_schema],

       ltrim(rtrim(cast([bk_reftype_objecttype] AS varchar(255)))) AS [bk_reftype_objecttype],

       ltrim(rtrim(cast([name] AS varchar(255)))) AS [name],

       ltrim(rtrim(cast([description] AS varchar(255)))) AS [description],

       ltrim(rtrim(cast([bk_reftype_datatype] AS varchar(255)))) AS [bk_reftype_datatype],

       ltrim(rtrim(cast([isnullable] AS varchar(255)))) AS [isnullable],

       ltrim(rtrim(cast([ordinalposition] AS varchar(255)))) AS [ordinalposition],

       ltrim(rtrim(cast([maximumlength] AS varchar(255)))) AS [maximumlength],

       ltrim(rtrim(cast([precision] AS varchar(255)))) AS [precision],

       ltrim(rtrim(cast([scale] AS varchar(255)))) AS [scale],

       ltrim(rtrim(cast([default] AS varchar(255)))) AS [default],

       ltrim(rtrim(cast([computedcolumn] AS varchar(255)))) AS [computedcolumn],

       ltrim(rtrim(cast([computedcolumnpersisted] AS varchar(255)))) AS [computedcolumnpersisted],

       ltrim(rtrim(cast([issystem] AS varchar(255)))) AS [issystem],

       ltrim(rtrim(cast([mta_source] AS varchar(255)))) AS [mta_source],

       ltrim(rtrim(cast([mta_loaddate] AS varchar(255)))) AS [mta_loaddate], -- Meta data columns:
 mta_rownum = row_number() OVER (
                                 ORDER BY [bk] ASC),

       mta_bk = upper(isnull(ltrim(rtrim(cast([bk] AS varchar(500)))), '-')),

       mta_bkh = convert(char(64), hashbytes('SHA2_512', upper(isnull(ltrim(rtrim(cast([bk] AS varchar(500)))), '-'))), 2),

       mta_rh = convert(char(64), hashbytes('SHA2_512', upper(isnull(ltrim(rtrim(cast([bk] AS varchar(255)))), '-') + '|' + isnull(ltrim(rtrim(cast([code] AS varchar(255)))), '-') + '|' + isnull(ltrim(rtrim(cast([active] AS varchar(255)))), '-') + '|' + isnull(ltrim(rtrim(cast([bk_schema] AS varchar(255)))), '-') + '|' + isnull(ltrim(rtrim(cast([bk_reftype_objecttype] AS varchar(255)))), '-') + '|' + isnull(ltrim(rtrim(cast([name] AS varchar(255)))), '-') + '|' + isnull(ltrim(rtrim(cast([description] AS varchar(255)))), '-') + '|' + isnull(ltrim(rtrim(cast([bk_reftype_datatype] AS varchar(255)))), '-') + '|' + isnull(ltrim(rtrim(cast([isnullable] AS varchar(255)))), '-') + '|' + isnull(ltrim(rtrim(cast([ordinalposition] AS varchar(255)))), '-') + '|' + isnull(ltrim(rtrim(cast([maximumlength] AS varchar(255)))), '-') + '|' + isnull(ltrim(rtrim(cast([precision] AS varchar(255)))), '-') + '|' + isnull(ltrim(rtrim(cast([scale] AS varchar(255)))), '-') + '|' + isnull(ltrim(rtrim(cast([default] AS varchar(255)))), '-') + '|' + isnull(ltrim(rtrim(cast([computedcolumn] AS varchar(255)))), '-') + '|' + isnull(ltrim(rtrim(cast([computedcolumnpersisted] AS varchar(255)))), '-') + '|' + isnull(ltrim(rtrim(cast([issystem] AS varchar(255)))), '-') + '|' + isnull(ltrim(rtrim(cast([mta_source] AS varchar(255)))), '-') + '|' + isnull(ltrim(rtrim(cast([mta_loaddate] AS varchar(255)))), '-'))), 2)

  FROM [rep].[mtaattribute]

 WHERE 1 = 1

   AND 1 = 1

   AND isnull(active, '1') = '1'

   AND isnull(ltrim(rtrim([bk])), '') != ''