
    CREATE   VIEW [rep].[vw_Schedule] AS
    /*
    View is generated by  : metro
    Generated at          : 2025-01-06 16:02:26
    Description           : View on stage table
    */
    SELECT 
        -- List of columns:
        LTRIM(RTRIM(CAST([BK] AS varchar(255)))) AS [BK],
        LTRIM(RTRIM(CAST([Name] AS varchar(255)))) AS [Name],
        LTRIM(RTRIM(CAST([Code] AS varchar(255)))) AS [Code],
        LTRIM(RTRIM(CAST([Description] AS varchar(255)))) AS [Description],
        LTRIM(RTRIM(CAST([Active] AS varchar(255)))) AS [Active],
        LTRIM(RTRIM(CAST([BK_ScheduleType] AS varchar(255)))) AS [BK_ScheduleType],
        LTRIM(RTRIM(CAST([BK_ScheduleFrequency] AS varchar(255)))) AS [BK_ScheduleFrequency],
        LTRIM(RTRIM(CAST([BK_ScheduleDailyInterval] AS varchar(255)))) AS [BK_ScheduleDailyInterval],
        LTRIM(RTRIM(CAST([BK_ScheduleWeeklyInterval] AS varchar(255)))) AS [BK_ScheduleWeeklyInterval],
        LTRIM(RTRIM(CAST([BK_ScheduleWorkDayInterval] AS varchar(255)))) AS [BK_ScheduleWorkDayInterval],
        LTRIM(RTRIM(CAST([BK_ScheduleMonthlyInterval] AS varchar(255)))) AS [BK_ScheduleMonthlyInterval],
        LTRIM(RTRIM(CAST([BK_ScheduleQuarterlyInterval] AS varchar(255)))) AS [BK_ScheduleQuarterlyInterval],
        LTRIM(RTRIM(CAST([BK_ScheduleYearlyInterval] AS varchar(255)))) AS [BK_ScheduleYearlyInterval],
        LTRIM(RTRIM(CAST([BK_ScheduleSpecials] AS varchar(255)))) AS [BK_ScheduleSpecials],
        LTRIM(RTRIM(CAST([StartDate] AS varchar(255)))) AS [StartDate],
        LTRIM(RTRIM(CAST([EndDate] AS varchar(255)))) AS [EndDate],
        LTRIM(RTRIM(CAST([StartTime] AS varchar(255)))) AS [StartTime],
        LTRIM(RTRIM(CAST([EndTime] AS varchar(255)))) AS [EndTime],
        LTRIM(RTRIM(CAST([BK_RefType_RepositoryStatus] AS varchar(255)))) AS [BK_RefType_RepositoryStatus],
        LTRIM(RTRIM(CAST([mta_Source] AS varchar(255)))) AS [mta_Source],
        LTRIM(RTRIM(CAST([mta_LoadDate] AS varchar(255)))) AS [mta_LoadDate],
        -- Meta data columns:
        mta_RowNum     = ROW_NUMBER() OVER (ORDER BY [BK] ASC),
        mta_BK         = UPPER(ISNULL(LTRIM(RTRIM(CAST([BK] AS VARCHAR(500)))),'-')),
        mta_BKH        = CONVERT(CHAR(64), HASHBYTES('SHA2_512', UPPER(ISNULL(LTRIM(RTRIM(CAST([BK] AS VARCHAR(500)))),'-'))), 2),
        mta_RH         = CONVERT(
            CHAR(64),
            HASHBYTES(
                'SHA2_512',
                UPPER(
                    ISNULL(LTRIM(RTRIM(CAST([BK] AS VARCHAR(255)))),'-')
                    + '|'
                    + ISNULL(LTRIM(RTRIM(CAST([Name] AS VARCHAR(255)))),'-')
                    + '|'
                    + ISNULL(LTRIM(RTRIM(CAST([Code] AS VARCHAR(255)))),'-')
                    + '|'
                    + ISNULL(LTRIM(RTRIM(CAST([Description] AS VARCHAR(255)))),'-')
                    + '|'
                    + ISNULL(LTRIM(RTRIM(CAST([Active] AS VARCHAR(255)))),'-')
                    + '|'
                    + ISNULL(LTRIM(RTRIM(CAST([BK_ScheduleType] AS VARCHAR(255)))),'-')
                    + '|'
                    + ISNULL(LTRIM(RTRIM(CAST([BK_ScheduleFrequency] AS VARCHAR(255)))),'-')
                    + '|'
                    + ISNULL(LTRIM(RTRIM(CAST([BK_ScheduleDailyInterval] AS VARCHAR(255)))),'-')
                    + '|'
                    + ISNULL(LTRIM(RTRIM(CAST([BK_ScheduleWeeklyInterval] AS VARCHAR(255)))),'-')
                    + '|'
                    + ISNULL(LTRIM(RTRIM(CAST([BK_ScheduleWorkDayInterval] AS VARCHAR(255)))),'-')
                    + '|'
                    + ISNULL(LTRIM(RTRIM(CAST([BK_ScheduleMonthlyInterval] AS VARCHAR(255)))),'-')
                    + '|'
                    + ISNULL(LTRIM(RTRIM(CAST([BK_ScheduleQuarterlyInterval] AS VARCHAR(255)))),'-')
                    + '|'
                    + ISNULL(LTRIM(RTRIM(CAST([BK_ScheduleYearlyInterval] AS VARCHAR(255)))),'-')
                    + '|'
                    + ISNULL(LTRIM(RTRIM(CAST([BK_ScheduleSpecials] AS VARCHAR(255)))),'-')
                    + '|'
                    + ISNULL(LTRIM(RTRIM(CAST([StartDate] AS VARCHAR(255)))),'-')
                    + '|'
                    + ISNULL(LTRIM(RTRIM(CAST([EndDate] AS VARCHAR(255)))),'-')
                    + '|'
                    + ISNULL(LTRIM(RTRIM(CAST([StartTime] AS VARCHAR(255)))),'-')
                    + '|'
                    + ISNULL(LTRIM(RTRIM(CAST([EndTime] AS VARCHAR(255)))),'-')
                    + '|'
                    + ISNULL(LTRIM(RTRIM(CAST([BK_RefType_RepositoryStatus] AS VARCHAR(255)))),'-')
                    + '|'
                    + ISNULL(LTRIM(RTRIM(CAST([mta_Source] AS VARCHAR(255)))),'-')
                    + '|'
                    + ISNULL(LTRIM(RTRIM(CAST([mta_LoadDate] AS VARCHAR(255)))),'-')
                )
            ),
            2
        )
    FROM [rep].[Schedule]
    WHERE 1=1 AND 1=1
      AND ISNULL(Active,'1') = '1'
      AND ISNULL(LTRIM(RTRIM([BK])),'') != ''