
        CREATE   VIEW [bld].[vw_BuildCheck] AS
        /*
        View is generated by  : metro
        Generated at          : 2024-12-24 08:25:25
        Description           : View on stage table
        */
        WITH Cur AS (
            SELECT 
                [BuildCheckId] AS [BuildCheckId],
                [BK] AS [BK],
                [Code] AS [Code],
                [CheckMessage] AS [CheckMessage],
                [LayerName] AS [LayerName],
                [SchemaName] AS [SchemaName],
                [GroupName] AS [GroupName],
                [ShortName] AS [ShortName],
                [mta_RecType], [mta_CreateDate], [mta_Source], [mta_BK], [mta_BKH], [mta_RH],
                [mta_CurrentFlag] = ROW_NUMBER() OVER (PARTITION BY [mta_BKH] ORDER BY [mta_CreateDate] DESC)
            FROM [bld].[BuildCheck]
               
        )
        SELECT 
            [BuildCheckId] AS [BuildCheckId],
            [BK] AS [BK],
            [Code] AS [Code],
            [CheckMessage] AS [CheckMessage],
            [LayerName] AS [LayerName],
            [SchemaName] AS [SchemaName],
            [GroupName] AS [GroupName],
            [ShortName] AS [ShortName],
            [mta_RecType], [mta_CreateDate], [mta_Source], [mta_BK], [mta_BKH], [mta_RH],
            [mta_IsDeleted] = IIF([mta_RecType] = -1, 1, 0)
        FROM Cur
        WHERE [mta_CurrentFlag] = 1 AND [mta_RecType] > -1