
        CREATE   VIEW [bld].[vw_Contact] AS
        /*
        View is generated by  : metro
        Generated at          : 2025-01-21 08:32:48
        Description           : View on stage table
        */
        WITH Cur AS (
            SELECT 
                [ContactId] AS [ContactId],
                [bk] AS [bk],
                [code] AS [code],
                [bk_contactgroup] AS [bk_contactgroup],
                [contactgroup] AS [contactgroup],
                [contactrole] AS [contactrole],
                [main_contact] AS [main_contact],
                [alert_contact] AS [alert_contact],
                [contactperson_name] AS [contactperson_name],
                [contactperson_department] AS [contactperson_department],
                [contacperson_phonenumber] AS [contacperson_phonenumber],
                [contactperson_mailadress] AS [contactperson_mailadress],
                [contactperson_active] AS [contactperson_active],
                [rn_contact] AS [rn_contact],
                [mta_RecType], [mta_CreateDate], [mta_Source], [mta_BK], [mta_BKH], [mta_RH],
                [mta_CurrentFlag] = ROW_NUMBER() OVER (PARTITION BY [mta_BKH] ORDER BY [mta_CreateDate] DESC)
            FROM [bld].[Contact]
               
        )
        SELECT 
            [ContactId] AS [ContactId],
            [bk] AS [bk],
            [code] AS [code],
            [bk_contactgroup] AS [bk_contactgroup],
            [contactgroup] AS [contactgroup],
            [contactrole] AS [contactrole],
            [main_contact] AS [main_contact],
            [alert_contact] AS [alert_contact],
            [contactperson_name] AS [contactperson_name],
            [contactperson_department] AS [contactperson_department],
            [contacperson_phonenumber] AS [contacperson_phonenumber],
            [contactperson_mailadress] AS [contactperson_mailadress],
            [contactperson_active] AS [contactperson_active],
            [rn_contact] AS [rn_contact],
            [mta_RecType], [mta_CreateDate], [mta_Source], [mta_BK], [mta_BKH], [mta_RH],
            [mta_IsDeleted] = IIF([mta_RecType] = -1, 1, 0)
        FROM Cur
        WHERE [mta_CurrentFlag] = 1 AND [mta_RecType] > -1