
CREATE VIEW [bld].[vw_contactgroup] AS /*
        View is generated by  : metro
        Generated at          : 2024-12-24 08:25:25
        Description           : View on stage table
        */  WITH cur AS

        (SELECT [contactgroupid] AS [contactgroupid],

               [bk] AS [bk],

               [code] AS [code],

               [name] AS [name],

               [description] AS [description],

               [active] AS [active],

               [mta_rectype],

               [mta_createdate],

               [mta_source],

               [mta_bk],

               [mta_bkh],

               [mta_rh],

               [mta_currentflag] = row_number() OVER (PARTITION BY [mta_bkh]
                                                 ORDER BY [mta_createdate] DESC)

          FROM [bld].[contactgroup]
       )
SELECT [contactgroupid] AS [contactgroupid],

       [bk] AS [bk],

       [code] AS [code],

       [name] AS [name],

       [description] AS [description],

       [active] AS [active],

       [mta_rectype],

       [mta_createdate],

       [mta_source],

       [mta_bk],

       [mta_bkh],

       [mta_rh],

       [mta_isdeleted] = iif([mta_rectype] = -1, 1, 0)

  FROM cur

 WHERE [mta_currentflag] = 1

   AND [mta_rectype] > -1
