
        CREATE   VIEW [bld].[vw_DWHRefTemplates] AS
        /*
        View is generated by  : metro
        Generated at          : 2025-01-21 08:32:48
        Description           : View on stage table
        */
        WITH Cur AS (
            SELECT 
                [DWHRefTemplatesId] AS [DWHRefTemplatesId],
                [BK] AS [BK],
                [Code] AS [Code],
                [BK_Template] AS [BK_Template],
                [BK_Dataset] AS [BK_Dataset],
                [TemplateType] AS [TemplateType],
                [TemplateSource] AS [TemplateSource],
                [BK_RefType_ObjectType] AS [BK_RefType_ObjectType],
                [TemplateScript] AS [TemplateScript],
                [TemplateVersion] AS [TemplateVersion],
                [RowNum] AS [RowNum],
                [mta_RecType], [mta_CreateDate], [mta_Source], [mta_BK], [mta_BKH], [mta_RH],
                [mta_CurrentFlag] = ROW_NUMBER() OVER (PARTITION BY [mta_BKH] ORDER BY [mta_CreateDate] DESC)
            FROM [bld].[DWHRefTemplates]
               
        )
        SELECT 
            [DWHRefTemplatesId] AS [DWHRefTemplatesId],
            [BK] AS [BK],
            [Code] AS [Code],
            [BK_Template] AS [BK_Template],
            [BK_Dataset] AS [BK_Dataset],
            [TemplateType] AS [TemplateType],
            [TemplateSource] AS [TemplateSource],
            [BK_RefType_ObjectType] AS [BK_RefType_ObjectType],
            [TemplateScript] AS [TemplateScript],
            [TemplateVersion] AS [TemplateVersion],
            [RowNum] AS [RowNum],
            [mta_RecType], [mta_CreateDate], [mta_Source], [mta_BK], [mta_BKH], [mta_RH],
            [mta_IsDeleted] = IIF([mta_RecType] = -1, 1, 0)
        FROM Cur
        WHERE [mta_CurrentFlag] = 1 AND [mta_RecType] > -1