
        CREATE   VIEW [bld].[vw_DeployScriptsSmartLoad] AS
        /*
        View is generated by  : metro
        Generated at          : 2024-12-24 08:25:25
        Description           : View on stage table
        */
        WITH Cur AS (
            SELECT 
                [DeployScriptsSmartLoadId] AS [DeployScriptsSmartLoadId],
                [BK] AS [BK],
                [BK_Dataset] AS [BK_Dataset],
                [Code] AS [Code],
                [SrcCreateDate] AS [SrcCreateDate],
                [TgtCreateDate] AS [TgtCreateDate],
                [IsUpdated] AS [IsUpdated],
                [RecType] AS [RecType],
                [mta_RecType], [mta_CreateDate], [mta_Source], [mta_BK], [mta_BKH], [mta_RH],
                [mta_CurrentFlag] = ROW_NUMBER() OVER (PARTITION BY [mta_BKH] ORDER BY [mta_CreateDate] DESC)
            FROM [bld].[DeployScriptsSmartLoad]
               
        )
        SELECT 
            [DeployScriptsSmartLoadId] AS [DeployScriptsSmartLoadId],
            [BK] AS [BK],
            [BK_Dataset] AS [BK_Dataset],
            [Code] AS [Code],
            [SrcCreateDate] AS [SrcCreateDate],
            [TgtCreateDate] AS [TgtCreateDate],
            [IsUpdated] AS [IsUpdated],
            [RecType] AS [RecType],
            [mta_RecType], [mta_CreateDate], [mta_Source], [mta_BK], [mta_BKH], [mta_RH],
            [mta_IsDeleted] = IIF([mta_RecType] = -1, 1, 0)
        FROM Cur
        WHERE [mta_CurrentFlag] = 1 AND [mta_RecType] > -1