
CREATE VIEW [bld].[vw_flow] AS /*
        View is generated by  : metro
        Generated at          : 2024-12-24 08:25:26
        Description           : View on stage table
        */  WITH cur AS

        (SELECT [flowid] AS [flowid],

               [bk] AS [bk],

               [code] AS [code],

               [bk_flow] AS [bk_flow],

               [flow_name] AS [flow_name],

               [flow_description] AS [flow_description],

               [flow_layer_step_name] AS [flow_layer_step_name],

               [flow_layer_step_description] AS [flow_layer_step_description],

               [flow_layer_step_order] AS [flow_layer_step_order],

               [bk_layer] AS [bk_layer],

               [bk_schema] AS [bk_schema],

               [readfromview] AS [readfromview],

               [bk_template_load] AS [bk_template_load],

               [bk_template_create] AS [bk_template_create],

               [mta_rectype],

               [mta_createdate],

               [mta_source],

               [mta_bk],

               [mta_bkh],

               [mta_rh],

               [mta_currentflag] = row_number() OVER (PARTITION BY [mta_bkh]
                                                 ORDER BY [mta_createdate] DESC)

          FROM [bld].[flow]
       )
SELECT [flowid] AS [flowid],

       [bk] AS [bk],

       [code] AS [code],

       [bk_flow] AS [bk_flow],

       [flow_name] AS [flow_name],

       [flow_description] AS [flow_description],

       [flow_layer_step_name] AS [flow_layer_step_name],

       [flow_layer_step_description] AS [flow_layer_step_description],

       [flow_layer_step_order] AS [flow_layer_step_order],

       [bk_layer] AS [bk_layer],

       [bk_schema] AS [bk_schema],

       [readfromview] AS [readfromview],

       [bk_template_load] AS [bk_template_load],

       [bk_template_create] AS [bk_template_create],

       [mta_rectype],

       [mta_createdate],

       [mta_source],

       [mta_bk],

       [mta_bkh],

       [mta_rh],

       [mta_isdeleted] = iif([mta_rectype] = -1, 1, 0)

  FROM cur

 WHERE [mta_currentflag] = 1

   AND [mta_rectype] > -1
