
        CREATE   VIEW [bld].[vw_LoadDependency] AS
        /*
        View is generated by  : metro
        Generated at          : 2025-01-21 08:32:49
        Description           : View on stage table
        */
        WITH Cur AS (
            SELECT 
                [LoadDependencyId] AS [LoadDependencyId],
                [BK] AS [BK],
                [Code] AS [Code],
                [BK_Target] AS [BK_Target],
                [TGT_Layer] AS [TGT_Layer],
                [TGT_Schema] AS [TGT_Schema],
                [TGT_Group] AS [TGT_Group],
                [TGT_ShortName] AS [TGT_ShortName],
                [TGT_Code] AS [TGT_Code],
                [TGT_DatasetName] AS [TGT_DatasetName],
                [BK_Source] AS [BK_Source],
                [SRC_Layer] AS [SRC_Layer],
                [SRC_Schema] AS [SRC_Schema],
                [SRC_Group] AS [SRC_Group],
                [SRC_ShortName] AS [SRC_ShortName],
                [SRC_Code] AS [SRC_Code],
                [SRC_DatasetName] AS [SRC_DatasetName],
                [DependencyType] AS [DependencyType],
                [Generation_Number] AS [Generation_Number],
                [mta_RecType], [mta_CreateDate], [mta_Source], [mta_BK], [mta_BKH], [mta_RH],
                [mta_CurrentFlag] = ROW_NUMBER() OVER (PARTITION BY [mta_BKH] ORDER BY [mta_CreateDate] DESC)
            FROM [bld].[LoadDependency]
               
        )
        SELECT 
            [LoadDependencyId] AS [LoadDependencyId],
            [BK] AS [BK],
            [Code] AS [Code],
            [BK_Target] AS [BK_Target],
            [TGT_Layer] AS [TGT_Layer],
            [TGT_Schema] AS [TGT_Schema],
            [TGT_Group] AS [TGT_Group],
            [TGT_ShortName] AS [TGT_ShortName],
            [TGT_Code] AS [TGT_Code],
            [TGT_DatasetName] AS [TGT_DatasetName],
            [BK_Source] AS [BK_Source],
            [SRC_Layer] AS [SRC_Layer],
            [SRC_Schema] AS [SRC_Schema],
            [SRC_Group] AS [SRC_Group],
            [SRC_ShortName] AS [SRC_ShortName],
            [SRC_Code] AS [SRC_Code],
            [SRC_DatasetName] AS [SRC_DatasetName],
            [DependencyType] AS [DependencyType],
            [Generation_Number] AS [Generation_Number],
            [mta_RecType], [mta_CreateDate], [mta_Source], [mta_BK], [mta_BKH], [mta_RH],
            [mta_IsDeleted] = IIF([mta_RecType] = -1, 1, 0)
        FROM Cur
        WHERE [mta_CurrentFlag] = 1 AND [mta_RecType] > -1