
        CREATE   VIEW [bld].[vw_Layer] AS
        /*
        View is generated by  : metro
        Generated at          : 2024-12-24 08:25:26
        Description           : View on stage table
        */
        WITH Cur AS (
            SELECT 
                [LayerId] AS [LayerId], [bk] AS [bk], [code] AS [code], [Layer_Name] AS [Layer_Name], [Layer_Desciption] AS [Layer_Desciption], [isDWHhelper] AS [isDWHhelper], [isRep] AS [isRep], [isAudit] AS [isAudit], [isSRC] AS [isSRC], [isDWH] AS [isDWH], [isTGT] AS [isTGT], [Layer_Process_Order] AS [Layer_Process_Order],
                [mta_RecType], [mta_CreateDate], [mta_Source], [mta_BK], [mta_BKH], [mta_RH],
                [mta_CurrentFlag] = ROW_NUMBER() OVER (PARTITION BY [mta_BKH] ORDER BY [mta_CreateDate] DESC)
            FROM [bld].[Layer]
               
        )
        SELECT 
            [LayerId] AS [LayerId], [bk] AS [bk], [code] AS [code], [Layer_Name] AS [Layer_Name], [Layer_Desciption] AS [Layer_Desciption], [isDWHhelper] AS [isDWHhelper], [isRep] AS [isRep], [isAudit] AS [isAudit], [isSRC] AS [isSRC], [isDWH] AS [isDWH], [isTGT] AS [isTGT], [Layer_Process_Order] AS [Layer_Process_Order],
            [mta_RecType], [mta_CreateDate], [mta_Source], [mta_BK], [mta_BKH], [mta_RH],
            [mta_IsDeleted] = IIF([mta_RecType] = -1, 1, 0)
        FROM Cur
        WHERE [mta_CurrentFlag] = 1 AND [mta_RecType] > -1