
CREATE VIEW [bld].[vw_loaddependency] AS /*
        View is generated by  : metro
        Generated at          : 2024-12-24 08:25:26
        Description           : View on stage table
        */  WITH cur AS

        (SELECT [loaddependencyid] AS [loaddependencyid],

               [bk] AS [bk],

               [code] AS [code],

               [bk_target] AS [bk_target],

               [tgt_layer] AS [tgt_layer],

               [tgt_schema] AS [tgt_schema],

               [tgt_group] AS [tgt_group],

               [tgt_shortname] AS [tgt_shortname],

               [tgt_code] AS [tgt_code],

               [tgt_datasetname] AS [tgt_datasetname],

               [bk_source] AS [bk_source],

               [src_layer] AS [src_layer],

               [src_schema] AS [src_schema],

               [src_group] AS [src_group],

               [src_shortname] AS [src_shortname],

               [src_code] AS [src_code],

               [src_datasetname] AS [src_datasetname],

               [dependencytype] AS [dependencytype],

               [generation_number] AS [generation_number],

               [mta_rectype],

               [mta_createdate],

               [mta_source],

               [mta_bk],

               [mta_bkh],

               [mta_rh],

               [mta_currentflag] = row_number() OVER (PARTITION BY [mta_bkh]
                                                 ORDER BY [mta_createdate] DESC)

          FROM [bld].[loaddependency]
       )
SELECT [loaddependencyid] AS [loaddependencyid],

       [bk] AS [bk],

       [code] AS [code],

       [bk_target] AS [bk_target],

       [tgt_layer] AS [tgt_layer],

       [tgt_schema] AS [tgt_schema],

       [tgt_group] AS [tgt_group],

       [tgt_shortname] AS [tgt_shortname],

       [tgt_code] AS [tgt_code],

       [tgt_datasetname] AS [tgt_datasetname],

       [bk_source] AS [bk_source],

       [src_layer] AS [src_layer],

       [src_schema] AS [src_schema],

       [src_group] AS [src_group],

       [src_shortname] AS [src_shortname],

       [src_code] AS [src_code],

       [src_datasetname] AS [src_datasetname],

       [dependencytype] AS [dependencytype],

       [generation_number] AS [generation_number],

       [mta_rectype],

       [mta_createdate],

       [mta_source],

       [mta_bk],

       [mta_bkh],

       [mta_rh],

       [mta_isdeleted] = iif([mta_rectype] = -1, 1, 0)

  FROM cur

 WHERE [mta_currentflag] = 1

   AND [mta_rectype] > -1
