
CREATE VIEW [bld].[vw_testrules] AS /*
        View is generated by  : metro
        Generated at          : 2024-12-24 08:25:26
        Description           : View on stage table
        */  WITH cur AS

        (SELECT [testrulesid] AS [testrulesid],

               [code] AS [code],

               [bk] AS [bk],

               [bk_dataset] AS [bk_dataset],

               [bk_reftype_repositorystatus] AS [bk_reftype_repositorystatus],

               [testdefintion] AS [testdefintion],

               [adfpipeline] AS [adfpipeline],

               [getattributes] AS [getattributes],

               [tresholdvalue] AS [tresholdvalue],

               [specificattribute] AS [specificattribute],

               [attributename] AS [attributename],

               [expectedvalue] AS [expectedvalue],

               [mta_rectype],

               [mta_createdate],

               [mta_source],

               [mta_bk],

               [mta_bkh],

               [mta_rh],

               [mta_currentflag] = row_number() OVER (PARTITION BY [mta_bkh]
                                                 ORDER BY [mta_createdate] DESC)

          FROM [bld].[testrules]
       )
SELECT [testrulesid] AS [testrulesid],

       [code] AS [code],

       [bk] AS [bk],

       [bk_dataset] AS [bk_dataset],

       [bk_reftype_repositorystatus] AS [bk_reftype_repositorystatus],

       [testdefintion] AS [testdefintion],

       [adfpipeline] AS [adfpipeline],

       [getattributes] AS [getattributes],

       [tresholdvalue] AS [tresholdvalue],

       [specificattribute] AS [specificattribute],

       [attributename] AS [attributename],

       [expectedvalue] AS [expectedvalue],

       [mta_rectype],

       [mta_createdate],

       [mta_source],

       [mta_bk],

       [mta_bkh],

       [mta_rh],

       [mta_isdeleted] = iif([mta_rectype] = -1, 1, 0)

  FROM cur

 WHERE [mta_currentflag] = 1

   AND [mta_rectype] > -1
