
CREATE VIEW [bld].[vw_template] AS /*
        View is generated by  : metro
        Generated at          : 2024-12-24 08:25:26
        Description           : View on stage table
        */  WITH cur AS

        (SELECT [templateid] AS [templateid],

               [bk] AS [bk],

               [code] AS [code],

               [templatename] AS [templatename],

               [templatetype] AS [templatetype],

               [templatedecription] AS [templatedecription],

               [objecttype] AS [objecttype],

               [objecttypedeployorder] AS [objecttypedeployorder],

               [script] AS [script],

               [scriptlanguagecode] AS [scriptlanguagecode],

               [scriptlanguage] AS [scriptlanguage],

               [objectname] AS [objectname],

               [bk_reftype_templatetype] AS [bk_reftype_templatetype],

               [bk_reftype_objecttype] AS [bk_reftype_objecttype],

               [bk_reftype_objecttype_basedon] AS [bk_reftype_objecttype_basedon],

               [bk_reftype_scriptlanguage] AS [bk_reftype_scriptlanguage],

               [templateversion] AS [templateversion],

               [mta_rectype],

               [mta_createdate],

               [mta_source],

               [mta_bk],

               [mta_bkh],

               [mta_rh],

               [mta_currentflag] = row_number() OVER (PARTITION BY [mta_bkh]
                                                 ORDER BY [mta_createdate] DESC)

          FROM [bld].[template]
       )
SELECT [templateid] AS [templateid],

       [bk] AS [bk],

       [code] AS [code],

       [templatename] AS [templatename],

       [templatetype] AS [templatetype],

       [templatedecription] AS [templatedecription],

       [objecttype] AS [objecttype],

       [objecttypedeployorder] AS [objecttypedeployorder],

       [script] AS [script],

       [scriptlanguagecode] AS [scriptlanguagecode],

       [scriptlanguage] AS [scriptlanguage],

       [objectname] AS [objectname],

       [bk_reftype_templatetype] AS [bk_reftype_templatetype],

       [bk_reftype_objecttype] AS [bk_reftype_objecttype],

       [bk_reftype_objecttype_basedon] AS [bk_reftype_objecttype_basedon],

       [bk_reftype_scriptlanguage] AS [bk_reftype_scriptlanguage],

       [templateversion] AS [templateversion],

       [mta_rectype],

       [mta_createdate],

       [mta_source],

       [mta_bk],

       [mta_bkh],

       [mta_rh],

       [mta_isdeleted] = iif([mta_rectype] = -1, 1, 0)

  FROM cur

 WHERE [mta_currentflag] = 1

   AND [mta_rectype] > -1
