
        CREATE   VIEW [bld].[vw_TestRules] AS
        /*
        View is generated by  : metro
        Generated at          : 2024-12-24 08:25:26
        Description           : View on stage table
        */
        WITH Cur AS (
            SELECT 
                [TestRulesId] AS [TestRulesId],
                [Code] AS [Code],
                [BK] AS [BK],
                [BK_Dataset] AS [BK_Dataset],
                [BK_RefType_RepositoryStatus] AS [BK_RefType_RepositoryStatus],
                [TestDefintion] AS [TestDefintion],
                [ADFPipeline] AS [ADFPipeline],
                [GetAttributes] AS [GetAttributes],
                [TresholdValue] AS [TresholdValue],
                [SpecificAttribute] AS [SpecificAttribute],
                [AttributeName] AS [AttributeName],
                [ExpectedValue] AS [ExpectedValue],
                [mta_RecType], [mta_CreateDate], [mta_Source], [mta_BK], [mta_BKH], [mta_RH],
                [mta_CurrentFlag] = ROW_NUMBER() OVER (PARTITION BY [mta_BKH] ORDER BY [mta_CreateDate] DESC)
            FROM [bld].[TestRules]
               
        )
        SELECT 
            [TestRulesId] AS [TestRulesId],
            [Code] AS [Code],
            [BK] AS [BK],
            [BK_Dataset] AS [BK_Dataset],
            [BK_RefType_RepositoryStatus] AS [BK_RefType_RepositoryStatus],
            [TestDefintion] AS [TestDefintion],
            [ADFPipeline] AS [ADFPipeline],
            [GetAttributes] AS [GetAttributes],
            [TresholdValue] AS [TresholdValue],
            [SpecificAttribute] AS [SpecificAttribute],
            [AttributeName] AS [AttributeName],
            [ExpectedValue] AS [ExpectedValue],
            [mta_RecType], [mta_CreateDate], [mta_Source], [mta_BK], [mta_BKH], [mta_RH],
            [mta_IsDeleted] = IIF([mta_RecType] = -1, 1, 0)
        FROM Cur
        WHERE [mta_CurrentFlag] = 1 AND [mta_RecType] > -1