
CREATE PROCEDURE [rep].[010_rep_recreate_repviews_backup] AS /*
Developed by:			metro
Description:			(Re)Create views on the [stg_rep] tables with meta columns:
						- mta_BK		(Stores the Businesskey of the table)
						- mta_BKH		(Stores the hash of the Businesskey of the table)
						- mta_RH		(Stores the hash of the full row)
						- mta_RowNum	actually only needed for the view [rep].[vw_XlsTabsToLoad] so i could make an easy loop in this procedure

Change log:
Date					Author				Description
20220915 00:00			K. Vermeij			Initial version
*/ DECLARE @logprocname varchar(MAX) = '[rep].[010_rep_Recreate_RepViews]' DECLARE @logsql varchar(MAX) DECLARE @srcschema varchar(MAX) = 'rep' DECLARE @tgtschema varchar(MAX) = 'rep' -- variables for the loop
DECLARE @counternr integer DECLARE @maxnr integer DECLARE @sql1 varchar(MAX) DECLARE @sql2 varchar(MAX) DECLARE @tablename varchar(MAX) DECLARE @msg varchar(MAX) IF object_id('tempdb..#XlsTabsToLoad') IS NOT NULL
DROP TABLE #xlstabstoload
SELECT * ,

       mta_rownum = row_number() OVER (
                                       ORDER BY [bk] ASC) INTO #xlstabstoload

  FROM rep.xlstabstoload

 WHERE bk IS NOT NULL
  SELECT @counternr = min(mta_rownum) ,

       @maxnr = max(mta_rownum)

  FROM #xlstabstoload WHILE (@counternr IS NOT NULL
                             AND @counternr <= @maxnr) BEGIN
  SELECT @tablename = c.[table_name] ,

       @sql1 = 'if exists(select * from INFORMATION_SCHEMA.[TABLES]  v where table_schema = ''' + @srcschema + ''' and table_name=''vw_' + c.[table_name] + ''' and TABLE_TYPE=''VIEW'')' + char(10) + 'drop view ' + @srcschema + '.[vw_' + c.[table_name] + '];' ,

       @sql2 = 'create view ' + @tgtschema + '.vw_' + c.[table_name] + ' as' + char(10) + '/*' + char(10) + 'View is generated by  : metro' + char(10) + 'Generated at          : ' + convert(varchar(19), getdate(), 121) + char(10) + 'Description           : View on stage table' + char(10) + '*/' + char(10) + char(10) + 'Select ' + char(10) + char(9) + '-- List of columns:' + char(10) + char(9) + string_agg('Ltrim(Rtrim(Cast([' + c.[column_name] + '] as varchar(' + CASE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          WHEN c.[column_name] like '%desc'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               OR c.[column_name] like '%expression'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               OR c.[column_name] like '%script'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               OR c.[column_name] like '%RecordSrcDate'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               OR c.[column_name] like '%BusinessDate'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               OR c.[column_name] like '%value' THEN 'max'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ELSE '255'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      END + ')))) as [' + c.[column_name] + ']', ',') within GROUP (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ORDER BY t.table_type ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             c.[table_name] ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             c.[ordinal_position] ASC) + char(10) + char(9) + char(10) + char(9) + '-- Meta data columns:' + char(10) + char(9) + ', mta_RowNum     = Row_Number() Over (Order By [BK] asc)' + char(10) + char(9) + ', mta_BK         = Upper(Isnull(Ltrim(Rtrim(Cast([BK] as varchar(500)))),''-''))' + char(10) + char(9) + ', mta_BKH        = Convert(char(64),(hashbytes(''sha2_512'',' + char(10) + char(9) + char(9) + char(9) + char(9) + char(9) + char(9) + char(9) + char(9) + 'Upper(Isnull(Ltrim(Rtrim(Cast([BK] as varchar(500)))),''-''))' + char(10) + char(9) + char(9) + char(9) + char(9) + char(9) + char(9) + char(9) + ')),2)' + char(10) + char(9) + ', mta_RH         = Convert(char(64),(Hashbytes(''sha2_512'',upper(' + char(10) + char(9) + char(9) + char(9) + char(9) + char(9) + char(9) + char(9) + char(9) + string_agg('isnull(ltrim(rtrim(cast([' + c.[column_name] + ']as varchar(' + CASE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              WHEN c.[column_name] like '%desc'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   OR c.[column_name] like '%script' THEN '8000'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ELSE '255'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          END + '))	)),''-'')', '+''|''+') within GROUP (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ORDER BY t.table_type ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  c.[table_name] ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  c.[ordinal_position] ASC) + char(10) + char(9) + char(9) + char(9) + char(9) + char(9) + char(9) + char(9) + '))),2)	' + char(10) + char(9) + ', mta_Source     = mta_Source' + char(10) + char(9) + ', mta_Loaddate   = Cast(mta_LoadDate as datetime2)' + char(10) + 'From ' + @srcschema + '.[' + c.[table_name] + ']' + char(10) + 'Where 1=1' + char(10) + char(9) + 'and isnull(Active,''1'') = ''1'' ' + char(10) + char(9) + 'and isnull([BK],'''') != ''''	;'

  FROM [information_schema].[columns] c

  JOIN [information_schema].[tables] t
    ON c.table_schema = t.table_schema

   AND c.table_name = t.table_name

  JOIN #xlstabstoload xt
    ON c.table_name = xt.tablename

 WHERE 1 = 1

   AND t.table_type = 'BASE TABLE'

   AND t.table_schema = @tgtschema

   AND c.column_name != 'mta_Source'

   AND c.column_name != 'mta_LoadDate'

   AND xt.tablename != 'XlsTabsToLoad'

   AND xt.mta_rownum = @counternr

 GROUP BY c.[table_name] -- drop views if exists
 PRINT ('') PRINT (@sql1) EXEC (@sql1)

   SET @msg = 'Drop view ' + isnull(@tgtschema, '') + isnull('.vw_' + @tablename, '') EXEC [aud].[proc_log_procedure] @logaction = 'DROP' ,

       @lognote = @msg ,

       @logprocedure = @logprocname ,

       @logsql = @sql1 ,

       @logrowcount = 1 -- create views
 PRINT ('') PRINT (@sql2) EXEC (@sql2)

   SET @msg = 'Create view ' + isnull(@tgtschema, '') + isnull('.vw_' + @tablename, '') EXEC [aud].[proc_log_procedure] @logaction = 'CREATE' ,

       @lognote = @msg ,

       @logprocedure = @logprocname ,

       @logsql = @sql2 ,

       @logrowcount = 1

   SET @counternr = @counternr + 1 END

   SET @logsql = 'exec ' + @tgtschema + '.' + @logprocname EXEC [aud].[proc_log_procedure] @logaction = 'INFO' ,

       @lognote = '(Re)Created views on the [stg_rep] tables with meta columns' ,

       @logprocedure = @logprocname ,

       @logsql = @logsql ,

       @logrowcount = @maxnr
