
CREATE PROCEDURE [rep].[022_bld_recreate_currentviews_backup] AS /*
Developed by:			metro
Description:			(Re)Create views for the current records on the [generated] tables

Change log:
Date					Author				Description
20220915 00:00			K. Vermeij			Initial version
20220917 08:25			K. Vermeij			Add [mta_IsDeleted]
*/ DECLARE @logprocname varchar(MAX) = '[rep].[022_bld_Recreate_CurrentViews]' DECLARE @lognote varchar(MAX) = '(Re)Create views for the current records on the [bld] tables' DECLARE @logsql varchar(MAX) DECLARE @srcschema varchar(MAX) = 'bld' DECLARE @tgtschema varchar(MAX) = 'bld' -- variables for the loop
DECLARE @counternr integer DECLARE @maxnr integer DECLARE @sql1 varchar(MAX) DECLARE @sql2 varchar(MAX) DECLARE @longsql varchar(MAX) DECLARE @tablename varchar(MAX) DECLARE @msg varchar(MAX) IF object_id('tempdb..#BuildCurrentViews') IS NOT NULL
DROP TABLE #buildcurrentviews; WITH base AS

        (SELECT table_catalog = t.[table_catalog],

               src_table_schema = t.[table_schema],

               src_table_name = t.[table_name],

               src_table_type = t.[table_type],

               tgt_table_name = rep.[getnamepart](replace(t.[table_name], 'tr_', ''), 2) ,RowNum = row_number() OVER (PARTITION BY rep.[getnamepart](replace(t.[table_name], 'tr_', ''), 2)
                                                                                                                 ORDER BY t.[table_name])

          FROM [information_schema].[tables] t

         WHERE 1 = 1

           AND table_type = 'VIEW'

           AND left(t.[table_name], 3) = 'tr_'

           AND t.table_schema = @srcschema
       )
SELECT *,

       processsequence = row_number() OVER (
                                            ORDER BY tgt_table_name) INTO #buildcurrentviews

  FROM base

 WHERE RowNum = 1
  SELECT @counternr = min(processsequence),

       @maxnr = max(processsequence)

  FROM #buildcurrentviews WHILE (@counternr IS NOT NULL
                                 AND @counternr <= @maxnr) BEGIN
  SELECT @tablename = src.tgt_table_name,

       @sql1 = 'if exists(select * from INFORMATION_SCHEMA.[TABLES]  v where table_schema = ''' + @tgtschema + ''' and table_name=''vw_' + src.tgt_table_name + ''' and TABLE_TYPE=''VIEW'')' + char(10) + 'drop view [' + @tgtschema + '].[vw_' + src.tgt_table_name + '];',

       @sql2 = 'create view [' + @tgtschema + '].vw_' + src.tgt_table_name + ' as' + char(10) + '/*' + char(10) + 'View is generated by	: metro' + char(10) + 'Generated at			: ' + convert(varchar(19), getdate(), 121) + char(10) + '*/' + char(10) + char(10) + 'With Cur as (' + char(10) + char(9) + 'SELECT ' + char(10) + char(9) + char(9) + string_agg('[' + c.[column_name] + ']  as [' + c.[column_name] + ']', ',') within GROUP (
                                                                                                                                                                                                                                                                                                                                                                                                                                                ORDER BY src.tgt_table_name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                         c.[ordinal_position] ASC) + char(10) + char(9) + char(9) + ',[mta_RecType], [mta_CreateDate], [mta_Source], [mta_BK], [mta_BKH], [mta_RH]' + char(10) + char(9) + char(9) + '-- Determine latest record based on create date' + char(10) + char(9) + char(9) + ', [mta_CurrentFlag] = Row_Number() Over (Partition By [mta_BKH] Order by [mta_CreateDate] Desc)' + char(10) + char(9) + 'FROM [' + @srcschema + '].[' + src.tgt_table_name + ']' + char(10) + char(9) + 'WHERE 1=1' + char(10) + char(9) + ')' + 'Select ' + char(10) + char(9) + string_agg('[' + c.[column_name] + ']  as [' + c.[column_name] + ']', ',') within GROUP (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ORDER BY src.tgt_table_name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             c.[ordinal_position] ASC) + char(10) + char(9) + '-- Add "Deleted" indicator, the current view shows the latest record even if deleted. This gives the oppurtunity to delete records in the [bld] schema' + char(10) + char(9) + ',[mta_RecType], [mta_CreateDate], [mta_Source], [mta_BK], [mta_BKH], [mta_RH]' + char(10) + char(9) + ', mta_IsDeleted = iif([mta_RecType]=-1,1,0)' + char(10) + 'From Cur' + char(10) + 'Where [mta_CurrentFlag] = 1 and [mta_RecType]>-1' + char(10) --select *

  FROM #buildcurrentviews src

  JOIN [information_schema].[columns] c
    ON c.table_schema = src_table_schema

   AND c.table_name = src.tgt_table_name

 WHERE 1 = 1

   AND left(c.[column_name], 3) != 'mta'

   AND src.processsequence = @counternr

 GROUP BY src.tgt_table_name -- drop views if exists
 PRINT '' PRINT (@sql1) EXEC (@sql1)

   SET @msg = 'Drop view bld.vw_' + @tablename EXEC [aud].[proc_log_procedure] @logaction = 'DROP',

       @lognote = @msg,

       @logprocedure = @logprocname,

       @logsql = @sql1,

       @logrowcount = 1 -- create views
 PRINT '' --Print	(@sql2)

   SET @longsql = @sql2 EXEC rep.helper_longprint @string = @longsql EXEC (@longsql)

   SET @msg = 'Create view bld.vw_' + @tablename EXEC [aud].[proc_log_procedure] @logaction = 'CREATE',

       @lognote = @msg,

       @logprocedure = @logprocname,

       @logsql = @sql2,

       @logrowcount = 1

   SET @counternr = @counternr + 1 END

   SET @logsql = 'exec ' + @tgtschema + '.' + @logprocname EXEC [aud].[proc_log_procedure] @logaction = 'INFO',

       @lognote = @lognote,

       @logprocedure = @logprocname,

       @logsql = @logsql,

       @logrowcount = @maxnr -- Cleaning
IF object_id('tempdb..#BuildCurrentViews') IS NOT NULL
  DROP TABLE #buildcurrentviews
