
CREATE TABLE [rep].[contactperson] ([bk] NVARCHAR (MAX) NULL,
                                                        [code] NVARCHAR (MAX) NULL,
                                                                              [name] NVARCHAR (MAX) NULL,
                                                                                                    [description] NVARCHAR (MAX) NULL,
                                                                                                                                 [contact_name] NVARCHAR (MAX) NULL,
                                                                                                                                                               [contact_department] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                   [contact_org] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                                                [contact_phone_number] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                                                                                      [contact_mail_address] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                                                                                                                            [active] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                                                                                                                                                    [mta_source] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                                                                                                                                                                                [mta_loaddate] NVARCHAR (MAX) NULL);