CREATE TABLE [rep].[DatasetSrcFileProperties] (
    [BK]                       NVARCHAR (MAX) NULL,
    [Code]                     NVARCHAR (MAX) NULL,
    [Name]                     NVARCHAR (MAX) NULL,
    [Description]              NVARCHAR (MAX) NULL,
    [BK_SrcDataset]            NVARCHAR (MAX) NULL,
    [Active]                   NVARCHAR (MAX) NULL,
    [BK_FileFormat]            NVARCHAR (MAX) NULL,
    [FileSystem]               NVARCHAR (MAX) NULL,
    [Folder]                   NVARCHAR (MAX) NULL,
    [Filename]                 NVARCHAR (MAX) NULL,
    [FileMask]                 NVARCHAR (MAX) NULL,
    [BK_Schedule_Expected]     NVARCHAR (MAX) NULL,
    [ExpectedFileSize]         NVARCHAR (MAX) NULL,
    [ExpectedFileCount]        NVARCHAR (MAX) NULL,
    [isPGP]                    NVARCHAR (MAX) NULL,
    [DateInFileNameStartPos]   NVARCHAR (MAX) NULL,
    [DateinFileNameLength]     NVARCHAR (MAX) NULL,
    [DateInFileNameFormat]     NVARCHAR (MAX) NULL,
    [DateInFileNameExpression] NVARCHAR (MAX) NULL,
    [TestDateInFileName]       NVARCHAR (MAX) NULL,
    [IsSystem]                 NVARCHAR (MAX) NULL,
    [Filesize]                 NVARCHAR (MAX) NULL,
    [Threshold]                NVARCHAR (MAX) NULL,
    [mta_Source]               NVARCHAR (MAX) NULL,
    [mta_LoadDate]             NVARCHAR (MAX) NULL
);

