
CREATE TABLE [rep].[datasource] ([bk] NVARCHAR (MAX) NULL,
                                                     [code] NVARCHAR (MAX) NULL,
                                                                           [name] NVARCHAR (MAX) NULL,
                                                                                                 [active] NVARCHAR (MAX) NULL,
                                                                                                                         [description] NVARCHAR (MAX) NULL,
                                                                                                                                                      [bk_reftype_datasourcetype] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                 [bk_linkedservice] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                                                   [isdwh] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                                                                          [isrep] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                                                                                                 [connectionstring] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                                                                                                                                   [issystem] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                                                                                                                                                             [mta_source] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                                                                                                                                                                                         [mta_loaddate] NVARCHAR (MAX) NULL);
