CREATE TABLE [rep].[DatasetSto] (
    [bk]                          NVARCHAR (MAX) NULL,
    [code]                        NVARCHAR (MAX) NULL,
    [name]                        NVARCHAR (MAX) NULL,
    [Description]                 NVARCHAR (MAX) NULL,
    [Description_nl]              NVARCHAR (MAX) NULL,
    [active]                      NVARCHAR (MAX) NULL,
    [BK_Schema]                   NVARCHAR (MAX) NULL,
    [StoType]                     NVARCHAR (MAX) NULL,
    [prefix]                      NVARCHAR (MAX) NULL,
    [bk_datasetTrn_based_on]      NVARCHAR (MAX) NULL,
    [Kolom1]                      NVARCHAR (MAX) NULL,
    [bk_schedule]                 NVARCHAR (MAX) NULL,
    [bk_schema_to]                NVARCHAR (MAX) NULL,
    [container]                   NVARCHAR (MAX) NULL,
    [folder]                      NVARCHAR (MAX) NULL,
    [filename]                    NVARCHAR (MAX) NULL,
    [datetime]                    NVARCHAR (MAX) NULL,
    [bk_fileformat]               NVARCHAR (MAX) NULL,
    [where_filter]                NVARCHAR (MAX) NULL,
    [order_by]                    NVARCHAR (MAX) NULL,
    [BK_ContactGroup]             NVARCHAR (MAX) NULL,
    [split_by]                    NVARCHAR (MAX) NULL,
    [BK_RefType_RepositoryStatus] NVARCHAR (MAX) NULL,
    [mta_Source]                  NVARCHAR (MAX) NULL,
    [mta_LoadDate]                NVARCHAR (MAX) NULL
);

