
CREATE TABLE [rep].[datasourceproperties] ([bk] NVARCHAR (MAX) NULL,
                                                               [code] NVARCHAR (MAX) NULL,
                                                                                     [name] NVARCHAR (MAX) NULL,
                                                                                                           [description] NVARCHAR (MAX) NULL,
                                                                                                                                        [active] NVARCHAR (MAX) NULL,
                                                                                                                                                                [bk_datasource] NVARCHAR (MAX) NULL,
                                                                                                                                                                                               [bk_reftype_environment] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                                                       [datasourcepropertiesname] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                                                                                                 [datasourcepropertiesvalue] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                                                                                                                                            [bk_reftype_repositorystatus] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                                                                                                                                                                                         [issystem] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                   [mta_source] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                               [mta_loaddate] NVARCHAR (MAX) NULL);