CREATE TABLE [rep].[DatasetTrnAttribute] (
    [BK]                  NVARCHAR (MAX) NULL,
    [Code]                NVARCHAR (MAX) NULL,
    [Name]                NVARCHAR (MAX) NULL,
    [BK_DatasetTrn]       NVARCHAR (MAX) NULL,
    [DatasetTrn]          NVARCHAR (MAX) NULL,
    [AttributeName]       NVARCHAR (MAX) NULL,
    [Description]         NVARCHAR (MAX) NULL,
    [Description_nl]      NVARCHAR (MAX) NULL,
    [Active]              NVARCHAR (MAX) NULL,
    [DistributionHashKey] NVARCHAR (MAX) NULL,
    [Expression]          NVARCHAR (MAX) NULL,
    [NotInRH]             NVARCHAR (MAX) NULL,
    [DefaultValue]        NVARCHAR (MAX) NULL,
    [SCDDate]             NVARCHAR (MAX) NULL,
    [BusinessKey]         NVARCHAR (MAX) NULL,
    [SrcName]             NVARCHAR (MAX) NULL,
    [BK_RefType_DataType] NVARCHAR (MAX) NULL,
    [Isnullable]          NVARCHAR (MAX) NULL,
    [OrdinalPosition]     NVARCHAR (MAX) NULL,
    [MaximumLength]       NVARCHAR (MAX) NULL,
    [Precision]           NVARCHAR (MAX) NULL,
    [Scale]               NVARCHAR (MAX) NULL,
    [Collation]           NVARCHAR (MAX) NULL,
    [mta_Source]          NVARCHAR (MAX) NULL,
    [mta_LoadDate]        NVARCHAR (MAX) NULL
);

