
CREATE TABLE [rep].[informationschema] ([bk] NVARCHAR (MAX) NULL,
                                                            [code] NVARCHAR (MAX) NULL,
                                                                                  [name] NVARCHAR (MAX) NULL,
                                                                                                        [bk_datasourcetype] NVARCHAR (MAX) NULL,
                                                                                                                                           [src_schema] NVARCHAR (MAX) NULL,
                                                                                                                                                                       [src_dataset] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                    [tgt_schema_metro] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                                                      [tgt_dataset_metro] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                                                                                         [active] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                                                                                                                 [mta_source] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                                                                                                                                             [mta_loaddate] NVARCHAR (MAX) NULL);