
CREATE TABLE [rep].[linkedserviceproperties] ([bk] NVARCHAR (MAX) NULL,
                                                                  [code] NVARCHAR (MAX) NULL,
                                                                                        [name] NVARCHAR (MAX) NULL,
                                                                                                              [description] NVARCHAR (MAX) NULL,
                                                                                                                                           [bk_linkedservice] NVARCHAR (MAX) NULL,
                                                                                                                                                                             [linkedservicepropertiesname] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                                          [linkedservicepropertiesvalue] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                                                                                        [linkedservicepropertiesdesc] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                                                                                                                                     [active] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                                                                                                                                                             [issystem] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                                                                                                                                                                                       [bk_reftype_repositorystatus] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                    [mta_source] NVARCHAR (MAX) NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                [mta_loaddate] NVARCHAR (MAX) NULL);