CREATE TABLE [rep].[Schedules] (
    [BK]                           NVARCHAR (MAX) NULL,
    [Code]                         NVARCHAR (MAX) NULL,
    [ProcessSourceDependencies]    NVARCHAR (MAX) NULL,
    [Name]                         NVARCHAR (MAX) NULL,
    [Description]                  NVARCHAR (MAX) NULL,
    [Description_nl]               NVARCHAR (MAX) NULL,
    [Active]                       NVARCHAR (MAX) NULL,
    [BK_Schedule]                  NVARCHAR (MAX) NULL,
    [ProcessAll]                   NVARCHAR (MAX) NULL,
    [ExcludeFromAllLevel]          NVARCHAR (MAX) NULL,
    [ExcludeFromAllOther]          NVARCHAR (MAX) NULL,
    [dependend_on_schedules_group] NVARCHAR (MAX) NULL,
    [schedules_group]              NVARCHAR (MAX) NULL,
    [BK_SRCDataset]                NVARCHAR (MAX) NULL,
    [SRC_Shortname]                NVARCHAR (MAX) NULL,
    [BK_TrnDataset]                NVARCHAR (MAX) NULL,
    [BK_Group]                     NVARCHAR (MAX) NULL,
    [BK_Schema]                    NVARCHAR (MAX) NULL,
    [BK_Layer]                     NVARCHAR (MAX) NULL,
    [BK_SRC_layer]                 NVARCHAR (MAX) NULL,
    [BK_export]                    NVARCHAR (MAX) NULL,
    [IsSystem]                     NVARCHAR (MAX) NULL,
    [BK_RefType_RepositoryStatus]  NVARCHAR (MAX) NULL,
    [mta_Source]                   NVARCHAR (MAX) NULL,
    [mta_LoadDate]                 NVARCHAR (MAX) NULL
);

