create view rep.vw_AliasViews as
/*
View is generated by  : metro
Generated at          : 2023-02-15 05:30:46
Description           : View on stage table
*/

Select 
	-- List of columns:
	Cast([BK] as varchar(255)) as [BK],Cast([Code] as varchar(255)) as [Code],Cast([Name] as varchar(255)) as [Name],Cast([SRC_Dataset] as varchar(255)) as [SRC_Dataset],Cast([SRC_Schema] as varchar(255)) as [SRC_Schema],Cast([SRC_GroupName] as varchar(255)) as [SRC_GroupName],Cast([TGT_ShortName] as varchar(255)) as [TGT_ShortName],Cast([Active] as varchar(255)) as [Active],Cast([BK_Template_Crate] as varchar(255)) as [BK_Template_Crate]
	
	-- Meta data columns:
	, mta_RowNum     = Row_Number() Over (Order By [BK] asc)
	, mta_BK         = Upper(Isnull(Ltrim(Rtrim(Cast([BK] as varchar(500)))),'-'))
	, mta_BKH        = Convert(char(64),(hashbytes('sha2_512',
								Upper(Isnull(Ltrim(Rtrim(Cast([BK] as varchar(500)))),'-'))
							)),2)
	, mta_RH         = Convert(char(64),(Hashbytes('sha2_512',upper(
								isnull(ltrim(rtrim(cast([BK]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([Code]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([Name]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([SRC_Dataset]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([SRC_Schema]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([SRC_GroupName]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([TGT_ShortName]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([Active]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([BK_Template_Crate]as varchar(255))	)),'-')
							))),2)	
	, mta_Source     = mta_Source
	, mta_Loaddate   = Cast(mta_LoadDate as datetime2)
From rep.[AliasViews]
Where 1=1
	and isnull(Active,'1') = '1' 
	and isnull([BK],'') != ''	;