
    CREATE   VIEW [rep].[vw_Contact] AS
    /*
    View is generated by  : metro
    Generated at          : 2025-01-06 16:02:25
    Description           : View on stage table
    */
    SELECT 
        -- List of columns:
        LTRIM(RTRIM(CAST([BK] as varchar(255)))) as [BK], LTRIM(RTRIM(CAST([Code] as varchar(255)))) as [Code], LTRIM(RTRIM(CAST([Name] as varchar(255)))) as [Name], LTRIM(RTRIM(CAST([Description] as varchar(255)))) as [Description], LTRIM(RTRIM(CAST([bk_contactgroup] as varchar(255)))) as [bk_contactgroup], LTRIM(RTRIM(CAST([bk_contactrole] as varchar(255)))) as [bk_contactrole], LTRIM(RTRIM(CAST([bk_contactperson] as varchar(255)))) as [bk_contactperson], LTRIM(RTRIM(CAST([main_contact] as varchar(255)))) as [main_contact], LTRIM(RTRIM(CAST([alert_contact] as varchar(255)))) as [alert_contact], LTRIM(RTRIM(CAST([Active] as varchar(255)))) as [Active], LTRIM(RTRIM(CAST([mta_Source] as varchar(255)))) as [mta_Source], LTRIM(RTRIM(CAST([mta_LoadDate] as varchar(255)))) as [mta_LoadDate],
        -- Meta data columns:
        mta_RowNum     = ROW_NUMBER() OVER (ORDER BY [BK] ASC),
        mta_BK         = UPPER(ISNULL(LTRIM(RTRIM(CAST([BK] AS VARCHAR(500)))),'-')),
        mta_BKH        = CONVERT(CHAR(64), HASHBYTES('SHA2_512', UPPER(ISNULL(LTRIM(RTRIM(CAST([BK] AS VARCHAR(500)))),'-'))), 2),
        mta_RH         = CONVERT(CHAR(64), HASHBYTES('SHA2_512', UPPER(ISNULL(LTRIM(RTRIM(CAST([BK] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([Code] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([Name] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([Description] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([bk_contactgroup] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([bk_contactrole] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([bk_contactperson] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([main_contact] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([alert_contact] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([Active] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([mta_Source] AS VARCHAR(255)))),'-') + '|' + ISNULL(LTRIM(RTRIM(CAST([mta_LoadDate] AS VARCHAR(255)))),'-'))), 2)
    FROM [rep].[Contact]
    WHERE 1=1 and 1=1
      AND ISNULL(Active,'1') = '1'
      AND ISNULL(LTRIM(RTRIM([BK])),'') != ''