create view rep.vw_DatasetTrn as
/*
View is generated by  : metro
Generated at          : 2023-02-15 05:30:46
Description           : View on stage table
*/

Select 
	-- List of columns:
	Cast([BK] as varchar(255)) as [BK],Cast([Code] as varchar(255)) as [Code],Cast([Name] as varchar(255)) as [Name],Cast([TargetDataset] as varchar(255)) as [TargetDataset],Cast([Active] as varchar(255)) as [Active],Cast([DataSource] as varchar(255)) as [DataSource],Cast([BK_Schema] as varchar(255)) as [BK_Schema],Cast([Schema] as varchar(255)) as [Schema],Cast([prefix] as varchar(255)) as [prefix],Cast([BK_Group] as varchar(255)) as [BK_Group],Cast([ShortName] as varchar(255)) as [ShortName],Cast([postfix] as varchar(255)) as [postfix],Cast([Description] as varchar(255)) as [Description],Cast([BK_Flow] as varchar(255)) as [BK_Flow],Cast([TimeStamp] as varchar(255)) as [TimeStamp],Cast([BusinessDate] as varchar(255)) as [BusinessDate],Cast([WhereFilter] as varchar(255)) as [WhereFilter],Cast([PartitionStatement] as varchar(255)) as [PartitionStatement],Cast([BK_RefType_TableType] as varchar(255)) as [BK_RefType_TableType],Cast([FullLoad] as varchar(255)) as [FullLoad],Cast([InsertOnly] as varchar(255)) as [InsertOnly],Cast([BigData] as varchar(255)) as [BigData],Cast([BK_Template_Load] as varchar(255)) as [BK_Template_Load],Cast([BK_Template_Create] as varchar(255)) as [BK_Template_Create],Cast([BK_RefType_RepositoryStatus] as varchar(255)) as [BK_RefType_RepositoryStatus],Cast([IsSystem] as varchar(255)) as [IsSystem]
	
	-- Meta data columns:
	, mta_RowNum     = Row_Number() Over (Order By [BK] asc)
	, mta_BK         = Upper(Isnull(Ltrim(Rtrim(Cast([BK] as varchar(500)))),'-'))
	, mta_BKH        = Convert(char(64),(hashbytes('sha2_512',
								Upper(Isnull(Ltrim(Rtrim(Cast([BK] as varchar(500)))),'-'))
							)),2)
	, mta_RH         = Convert(char(64),(Hashbytes('sha2_512',upper(
								isnull(ltrim(rtrim(cast([BK]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([Code]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([Name]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([TargetDataset]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([Active]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([DataSource]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([BK_Schema]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([Schema]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([prefix]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([BK_Group]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([ShortName]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([postfix]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([Description]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([BK_Flow]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([TimeStamp]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([BusinessDate]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([WhereFilter]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([PartitionStatement]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([BK_RefType_TableType]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([FullLoad]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([InsertOnly]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([BigData]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([BK_Template_Load]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([BK_Template_Create]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([BK_RefType_RepositoryStatus]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([IsSystem]as varchar(255))	)),'-')
							))),2)	
	, mta_Source     = mta_Source
	, mta_Loaddate   = Cast(mta_LoadDate as datetime2)
From rep.[DatasetTrn]
Where 1=1
	and isnull(Active,'1') = '1' 
	and isnull([BK],'') != ''	;