create view rep.vw_Schedule as
/*
View is generated by  : metro
Generated at          : 2023-02-15 05:30:47
Description           : View on stage table
*/

Select 
	-- List of columns:
	Cast([BK] as varchar(255)) as [BK],Cast([Name] as varchar(255)) as [Name],Cast([Code] as varchar(255)) as [Code],Cast([Description] as varchar(255)) as [Description],Cast([BK_ScheduleType] as varchar(255)) as [BK_ScheduleType],Cast([BK_ScheduleFrequency] as varchar(255)) as [BK_ScheduleFrequency],Cast([BK_ScheduleDailyInterval] as varchar(255)) as [BK_ScheduleDailyInterval],Cast([BK_ScheduleWeeklyInterval] as varchar(255)) as [BK_ScheduleWeeklyInterval],Cast([BK_ScheduleMonthlyInterval] as varchar(255)) as [BK_ScheduleMonthlyInterval],Cast([BK_ScheduleQuarterlyInterval] as varchar(255)) as [BK_ScheduleQuarterlyInterval],Cast([BK_ScheduleYearlyInterval] as varchar(255)) as [BK_ScheduleYearlyInterval],Cast([BK_ScheduleSpecials] as varchar(255)) as [BK_ScheduleSpecials],Cast([StartDate] as varchar(255)) as [StartDate],Cast([EndDate] as varchar(255)) as [EndDate],Cast([StartTime] as varchar(255)) as [StartTime],Cast([EndTime] as varchar(255)) as [EndTime],Cast([CRON] as varchar(255)) as [CRON],Cast([Active] as varchar(255)) as [Active]
	
	-- Meta data columns:
	, mta_RowNum     = Row_Number() Over (Order By [BK] asc)
	, mta_BK         = Upper(Isnull(Ltrim(Rtrim(Cast([BK] as varchar(500)))),'-'))
	, mta_BKH        = Convert(char(64),(hashbytes('sha2_512',
								Upper(Isnull(Ltrim(Rtrim(Cast([BK] as varchar(500)))),'-'))
							)),2)
	, mta_RH         = Convert(char(64),(Hashbytes('sha2_512',upper(
								isnull(ltrim(rtrim(cast([BK]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([Name]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([Code]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([Description]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([BK_ScheduleType]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([BK_ScheduleFrequency]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([BK_ScheduleDailyInterval]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([BK_ScheduleWeeklyInterval]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([BK_ScheduleMonthlyInterval]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([BK_ScheduleQuarterlyInterval]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([BK_ScheduleYearlyInterval]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([BK_ScheduleSpecials]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([StartDate]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([EndDate]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([StartTime]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([EndTime]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([CRON]as varchar(255))	)),'-')+'|'+isnull(ltrim(rtrim(cast([Active]as varchar(255))	)),'-')
							))),2)	
	, mta_Source     = mta_Source
	, mta_Loaddate   = Cast(mta_LoadDate as datetime2)
From rep.[Schedule]
Where 1=1
	and isnull(Active,'1') = '1' 
	and isnull([BK],'') != ''	;