
CREATE proc [bld].[load_050_schema_010_default] AS /*
	Proc is generated by	: metro
	Generated at			: 2025-01-06 14:43:26

	exec [bld].[load_050_Schema_010_Default]*/  DECLARE @routinename varchar(8000) = 'load_050_Schema_010_Default' DECLARE @startdatetime datetime2 = getutcdate() DECLARE @enddatetime datetime2 DECLARE @duration bigint -- Create a helper temp table
 IF object_id('tempdb..#050_Schema_010_Default') IS NOT NULL
DROP TABLE # 050_schema_010_default ; PRINT '-- create temp table:'
SELECT mta_bk = src.[bk] ,

       mta_bkh = convert(char(64),(hashbytes('sha2_512', upper(src.bk))),2) ,

       mta_rh = convert(char(64),(hashbytes('sha2_512', upper(isnull(cast(src.[bk] AS varchar(8000)), '-') + '|' + isnull(cast(src.[code] AS varchar(8000)), '-') + '|' + isnull(cast(src.[name] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_schema] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_layer] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_datasource] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_linkedservice] AS varchar(8000)), '-') + '|' + isnull(cast(src.[schemacode] AS varchar(8000)), '-') + '|' + isnull(cast(src.[schemaname] AS varchar(8000)), '-') + '|' + isnull(cast(src.[datasourcecode] AS varchar(8000)), '-') + '|' + isnull(cast(src.[datasourcename] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_datasourcetype] AS varchar(8000)), '-') + '|' + isnull(cast(src.[datasourcetypecode] AS varchar(8000)), '-') + '|' + isnull(cast(src.[datasourcetypename] AS varchar(8000)), '-') + '|' + isnull(cast(src.[layercode] AS varchar(8000)), '-') + '|' + isnull(cast(src.[layername] AS varchar(8000)), '-') + '|' + isnull(cast(src.[layerorder] AS varchar(8000)), '-') + '|' + isnull(cast(src.[processorderlayer] AS varchar(8000)), '-') + '|' + isnull(cast(src.[processparallel] AS varchar(8000)), '-') + '|' + isnull(cast(src.[isdwh] AS varchar(8000)), '-') + '|' + isnull(cast(src.[issrc] AS varchar(8000)), '-') + '|' + isnull(cast(src.[istgt] AS varchar(8000)), '-') + '|' + isnull(cast(src.[isrep] AS varchar(8000)), '-') + '|' + isnull(cast(src.[createdummies] AS varchar(8000)), '-') + '|' + isnull(cast(src.[linkedservicecode] AS varchar(8000)), '-') + '|' + isnull(cast(src.[linkedservicename] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_template_create] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_template_load] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_reftype_tochar] AS varchar(8000)), '-')))),2) ,

       mta_source = '[bld].[tr_050_Schema_010_Default]' ,

       mta_rectype = CASE
                         WHEN tgt.[bk] IS NULL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  THEN 1

            WHEN tgt.[mta_rh] != convert(char(64),(hashbytes('sha2_512', upper(isnull(cast(src.[bk] AS varchar(8000)), '-') + '|' + isnull(cast(src.[code] AS varchar(8000)), '-') + '|' + isnull(cast(src.[name] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_schema] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_layer] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_datasource] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_linkedservice] AS varchar(8000)), '-') + '|' + isnull(cast(src.[schemacode] AS varchar(8000)), '-') + '|' + isnull(cast(src.[schemaname] AS varchar(8000)), '-') + '|' + isnull(cast(src.[datasourcecode] AS varchar(8000)), '-') + '|' + isnull(cast(src.[datasourcename] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_datasourcetype] AS varchar(8000)), '-') + '|' + isnull(cast(src.[datasourcetypecode] AS varchar(8000)), '-') + '|' + isnull(cast(src.[datasourcetypename] AS varchar(8000)), '-') + '|' + isnull(cast(src.[layercode] AS varchar(8000)), '-') + '|' + isnull(cast(src.[layername] AS varchar(8000)), '-') + '|' + isnull(cast(src.[layerorder] AS varchar(8000)), '-') + '|' + isnull(cast(src.[processorderlayer] AS varchar(8000)), '-') + '|' + isnull(cast(src.[processparallel] AS varchar(8000)), '-') + '|' + isnull(cast(src.[isdwh] AS varchar(8000)), '-') + '|' + isnull(cast(src.[issrc] AS varchar(8000)), '-') + '|' + isnull(cast(src.[istgt] AS varchar(8000)), '-') + '|' + isnull(cast(src.[isrep] AS varchar(8000)), '-') + '|' + isnull(cast(src.[createdummies] AS varchar(8000)), '-') + '|' + isnull(cast(src.[linkedservicecode] AS varchar(8000)), '-') + '|' + isnull(cast(src.[linkedservicename] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_template_create] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_template_load] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_reftype_tochar] AS varchar(8000)), '-')))),2) THEN 0

            ELSE -99

             END INTO # 050_schema_010_default

  FROM [bld].[tr_050_schema_010_default] src

  LEFT JOIN [bld].[vw_schema] tgt
    ON src.[bk] = tgt.[bk]
CREATE clustered INDEX [ix_tr_050_schema_010_default]
    ON # 050_schema_010_default([mta_bkh] ASC, [mta_rh] ASC) --------------------- start loading data
 PRINT '-- new records:'

   SET @startdatetime = getdate()
INSERT INTO [bld].[schema] ([bk], [code], [name], [bk_schema], [bk_layer], [bk_datasource], [bk_linkedservice], [schemacode], [schemaname], [datasourcecode], [datasourcename], [bk_datasourcetype], [datasourcetypecode], [datasourcetypename], [layercode], [layername], [layerorder], [processorderlayer], [processparallel], [isdwh], [issrc], [istgt], [isrep], [createdummies], [linkedservicecode], [linkedservicename], [bk_template_create], [bk_template_load], [bk_reftype_tochar] , [mta_bk], [mta_bkh], [mta_rh], [mta_source], [mta_rectype])
SELECT src.[bk],

       src.[code],

       src.[name],

       src.[bk_schema],

       src.[bk_layer],

       src.[bk_datasource],

       src.[bk_linkedservice],

       src.[schemacode],

       src.[schemaname],

       src.[datasourcecode],

       src.[datasourcename],

       src.[bk_datasourcetype],

       src.[datasourcetypecode],

       src.[datasourcetypename],

       src.[layercode],

       src.[layername],

       src.[layerorder],

       src.[processorderlayer],

       src.[processparallel],

       src.[isdwh],

       src.[issrc],

       src.[istgt],

       src.[isrep],

       src.[createdummies],

       src.[linkedservicecode],

       src.[linkedservicename],

       src.[bk_template_create],

       src.[bk_template_load],

       src.[bk_reftype_tochar] ,

       h.[mta_bk],

       h.[mta_bkh],

       h.[mta_rh],

       h.[mta_source],

       h.[mta_rectype]

  FROM [bld].[tr_050_schema_010_default] src

  JOIN # 050_schema_010_default h
    ON h.[mta_bk] = src.[bk]

  LEFT JOIN [bld].[vw_schema] tgt
    ON h.[mta_bkh] = tgt.[mta_bkh]

 WHERE 1 = 1

   AND cast(h.mta_rectype AS int) = 1

   AND tgt.[mta_bkh] IS NULL

   SET @enddatetime = getutcdate() EXEC [aud].[proc_log_procedure] @logaction = 'INSERT - NEW',

       @lognote = 'New Records',

       @logprocedure = @routinename,

       @logsql = 'Insert Into [bld].[Schema]',

       @logrowcount = @@ rowcount,

       @log_timestart = @startdatetime,

       @log_timeend = @enddatetime; PRINT '-- changed records:'

   SET @startdatetime = getdate()
  INSERT INTO [bld].[schema] ([bk], [code], [name], [bk_schema], [bk_layer], [bk_datasource], [bk_linkedservice], [schemacode], [schemaname], [datasourcecode], [datasourcename], [bk_datasourcetype], [datasourcetypecode], [datasourcetypename], [layercode], [layername], [layerorder], [processorderlayer], [processparallel], [isdwh], [issrc], [istgt], [isrep], [createdummies], [linkedservicecode], [linkedservicename], [bk_template_create], [bk_template_load], [bk_reftype_tochar] , [mta_bk], [mta_bkh], [mta_rh], [mta_source], [mta_rectype])
SELECT src.[bk],

       src.[code],

       src.[name],

       src.[bk_schema],

       src.[bk_layer],

       src.[bk_datasource],

       src.[bk_linkedservice],

       src.[schemacode],

       src.[schemaname],

       src.[datasourcecode],

       src.[datasourcename],

       src.[bk_datasourcetype],

       src.[datasourcetypecode],

       src.[datasourcetypename],

       src.[layercode],

       src.[layername],

       src.[layerorder],

       src.[processorderlayer],

       src.[processparallel],

       src.[isdwh],

       src.[issrc],

       src.[istgt],

       src.[isrep],

       src.[createdummies],

       src.[linkedservicecode],

       src.[linkedservicename],

       src.[bk_template_create],

       src.[bk_template_load],

       src.[bk_reftype_tochar] ,

       h.[mta_bk],

       h.[mta_bkh],

       h.[mta_rh],

       h.[mta_source],

       h.[mta_rectype]

  FROM [bld].[tr_050_schema_010_default] src

  JOIN # 050_schema_010_default h
    ON h.[mta_bk] = src.[bk]

 WHERE 1 = 1

   AND cast(h.mta_rectype AS int) = 0

   SET @enddatetime = getutcdate() EXEC [aud].[proc_log_procedure] @logaction = 'INSERT - CHG',

       @lognote = 'Changed Records',

       @logprocedure = @routinename,

       @logsql = 'Insert Into [bld].[Schema]',

       @logrowcount = @@ rowcount,

       @log_timestart = @startdatetime,

       @log_timeend = @enddatetime; PRINT '-- deleted records:'

   SET @startdatetime = getdate()
  INSERT INTO [bld].[schema] ([bk], [code], [name], [bk_schema], [bk_layer], [bk_datasource], [bk_linkedservice], [schemacode], [schemaname], [datasourcecode], [datasourcename], [bk_datasourcetype], [datasourcetypecode], [datasourcetypename], [layercode], [layername], [layerorder], [processorderlayer], [processparallel], [isdwh], [issrc], [istgt], [isrep], [createdummies], [linkedservicecode], [linkedservicename], [bk_template_create], [bk_template_load], [bk_reftype_tochar] , [mta_bk], [mta_bkh], [mta_rh], [mta_source], [mta_rectype])
SELECT src.[bk],

       src.[code],

       src.[name],

       src.[bk_schema],

       src.[bk_layer],

       src.[bk_datasource],

       src.[bk_linkedservice],

       src.[schemacode],

       src.[schemaname],

       src.[datasourcecode],

       src.[datasourcename],

       src.[bk_datasourcetype],

       src.[datasourcetypecode],

       src.[datasourcetypename],

       src.[layercode],

       src.[layername],

       src.[layerorder],

       src.[processorderlayer],

       src.[processparallel],

       src.[isdwh],

       src.[issrc],

       src.[istgt],

       src.[isrep],

       src.[createdummies],

       src.[linkedservicecode],

       src.[linkedservicename],

       src.[bk_template_create],

       src.[bk_template_load],

       src.[bk_reftype_tochar] ,

       src.[mta_bk],

       src.[mta_bkh],

       src.[mta_rh],

       src.[mta_source],

       [mta_rectype] = -1

  FROM [bld].[vw_schema] src

  LEFT JOIN # 050_schema_010_default h
    ON h.[mta_bkh] = src.[mta_bkh]

   AND h.[mta_source] = src.[mta_source]

 WHERE 1 = 1

   AND h.[mta_bkh] IS NULL

   AND src.mta_source = '[bld].[tr_050_Schema_010_Default]'

   SET @enddatetime = getutcdate() EXEC [aud].[proc_log_procedure] @logaction = 'INSERT - DEL',

       @lognote = 'Changed Deleted',

       @logprocedure = @routinename,

       @logsql = 'Insert Into [bld].[Schema]',

       @logrowcount = @@ rowcount,

       @log_timestart = @startdatetime,

       @log_timeend = @enddatetime ; -- Clean up ...
 IF object_id('tempdb..#050_Schema_010_Default') IS NOT NULL
  DROP TABLE # 050_schema_010_default;

   SET @enddatetime = getutcdate()

   SET @duration = datediff(ss, @startdatetime, @enddatetime) PRINT 'Load "load_050_Schema_010_Default" took ' + cast(@duration AS varchar(10)) + ' second(s)'
