
	CREATE PROC [bld].[load_420_LoadDependency_010_SrcToTgt] AS
	/*
	Proc is generated by	: metro
	Generated at			: 2025-01-06 14:43:27
	
	exec [bld].[load_420_LoadDependency_010_SrcToTgt]*/

	
	DECLARE @RoutineName	varchar(8000)	= 'load_420_LoadDependency_010_SrcToTgt'
	DECLARE @StartDateTime	datetime2		=  getutcdate()
	DECLARE @EndDateTime	datetime2		
	DECLARE @Duration		bigint



	-- Create a helper temp table
	IF OBJECT_ID('tempdb..#420_LoadDependency_010_SrcToTgt') IS NOT NULL 
	DROP TABLE #420_LoadDependency_010_SrcToTgt ;
	PRINT '-- create temp table:'
	SELECT
	  mta_BK		= src.[BK]
	, mta_BKH		= CONVERT(char(64),(Hashbytes('sha2_512',upper(src.BK) )),2)
	, mta_RH		= CONVERT(char(64),(Hashbytes('sha2_512',upper(
								ISNULL(CAST(src.[BK] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[Code] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[BK_Target] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[TGT_Layer] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[TGT_Schema] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[TGT_Group] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[TGT_ShortName] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[TGT_Code] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[TGT_DatasetName] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[BK_Source] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[SRC_Layer] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[SRC_Schema] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[SRC_Group] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[SRC_ShortName] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[SRC_Code] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[SRC_DatasetName] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[DependencyType] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[Generation_Number] AS varchar(8000)),'-') 
							))),2)
	, mta_Source	= '[bld].[tr_420_LoadDependency_010_SrcToTgt]'
	, mta_RecType	= CASE 
												WHEN tgt.[BK] IS null THEN 1
												WHEN
												    tgt.[mta_RH]
												    !=  CONVERT(
												        char(64),
												        (
												            Hashbytes(
												                'sha2_512',
												                upper(
												                    ISNULL(CAST(src.[BK] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[Code] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[BK_Target] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[TGT_Layer] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[TGT_Schema] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[TGT_Group] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[TGT_ShortName] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[TGT_Code] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[TGT_DatasetName] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[BK_Source] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[SRC_Layer] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[SRC_Schema] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[SRC_Group] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[SRC_ShortName] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[SRC_Code] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[SRC_DatasetName] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[DependencyType] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[Generation_Number] AS varchar(8000)),'-')
												                )
												            )
												        ),
												        2
												    )
						THEN 0
						ELSE -99 END
	
	INTO #420_LoadDependency_010_SrcToTgt
	FROM [bld].[tr_420_LoadDependency_010_SrcToTgt] src
	LEFT JOIN [bld].[vw_LoadDependency] tgt ON src.[BK] = tgt.[BK]
	
	
	
	CREATE CLUSTERED INDEX [IX_tr_420_LoadDependency_010_SrcToTgt] ON #420_LoadDependency_010_SrcToTgt( [mta_BKH] ASC,[mta_RH] ASC)
	
	
	--------------------- start loading data
	
	PRINT '-- new records:'
	
	SET @StartDateTime = getdate()
	
	INSERT INTO [bld].[LoadDependency]
	( 
		[BK] ,
		[Code] ,
		[BK_Target] ,
		[TGT_Layer] ,
		[TGT_Schema] ,
		[TGT_Group] ,
		[TGT_ShortName] ,
		[TGT_Code] ,
		[TGT_DatasetName] ,
		[BK_Source] ,
		[SRC_Layer] ,
		[SRC_Schema] ,
		[SRC_Group] ,
		[SRC_ShortName] ,
		[SRC_Code] ,
		[SRC_DatasetName] ,
		[DependencyType] ,
		[Generation_Number] 
		, [mta_BK], [mta_BKH], [mta_RH], [mta_Source], [mta_RecType]) 
	SELECT 
		src.[BK] ,
		src.[Code] ,
		src.[BK_Target] ,
		src.[TGT_Layer] ,
		src.[TGT_Schema] ,
		src.[TGT_Group] ,
		src.[TGT_ShortName] ,
		src.[TGT_Code] ,
		src.[TGT_DatasetName] ,
		src.[BK_Source] ,
		src.[SRC_Layer] ,
		src.[SRC_Schema] ,
		src.[SRC_Group] ,
		src.[SRC_ShortName] ,
		src.[SRC_Code] ,
		src.[SRC_DatasetName] ,
		src.[DependencyType] ,
		src.[Generation_Number] 
		, h.[mta_BK], h.[mta_BKH], h.[mta_RH], h.[mta_Source], h.[mta_RecType]
	FROM  [bld].[tr_420_LoadDependency_010_SrcToTgt] src
	JOIN #420_LoadDependency_010_SrcToTgt h ON h.[mta_BK] = src.[BK]
	LEFT JOIN [bld].[vw_LoadDependency] tgt ON h.[mta_BKH] = tgt.[mta_BKH] 
	WHERE 1=1 AND CAST(h.mta_RecType AS int) = 1 AND tgt.[mta_BKH] IS null
	
	
	SET @EndDateTime = getutcdate()
	EXEC [aud].[proc_Log_Procedure]  
							@LogAction		= 'INSERT - NEW', 
							@LogNote		= 'New Records',
							@LogProcedure	= @RoutineName,
							@LogSQL			= 'Insert Into [bld].[LoadDependency]',
							@LogRowCount	= @@ROWCOUNT,
							@Log_TimeStart  = @StartDateTime,
							@Log_TimeEnd    = @EndDateTime;
	
	PRINT '-- changed records:'
	SET @StartDateTime = getdate()
	
		INSERT INTO [bld].[LoadDependency]
	( 
		[BK] ,
		[Code] ,
		[BK_Target] ,
		[TGT_Layer] ,
		[TGT_Schema] ,
		[TGT_Group] ,
		[TGT_ShortName] ,
		[TGT_Code] ,
		[TGT_DatasetName] ,
		[BK_Source] ,
		[SRC_Layer] ,
		[SRC_Schema] ,
		[SRC_Group] ,
		[SRC_ShortName] ,
		[SRC_Code] ,
		[SRC_DatasetName] ,
		[DependencyType] ,
		[Generation_Number] 
		, [mta_BK], [mta_BKH], [mta_RH], [mta_Source], [mta_RecType]) 
	SELECT 
		src.[BK] ,
		src.[Code] ,
		src.[BK_Target] ,
		src.[TGT_Layer] ,
		src.[TGT_Schema] ,
		src.[TGT_Group] ,
		src.[TGT_ShortName] ,
		src.[TGT_Code] ,
		src.[TGT_DatasetName] ,
		src.[BK_Source] ,
		src.[SRC_Layer] ,
		src.[SRC_Schema] ,
		src.[SRC_Group] ,
		src.[SRC_ShortName] ,
		src.[SRC_Code] ,
		src.[SRC_DatasetName] ,
		src.[DependencyType] ,
		src.[Generation_Number] 
		, h.[mta_BK], h.[mta_BKH], h.[mta_RH], h.[mta_Source], h.[mta_RecType]
	FROM  [bld].[tr_420_LoadDependency_010_SrcToTgt] src
	JOIN #420_LoadDependency_010_SrcToTgt h ON h.[mta_BK] = src.[BK]
	WHERE 1=1 AND CAST(h.mta_RecType AS int) = 0

	
	SET @EndDateTime = getutcdate()
	EXEC [aud].[proc_Log_Procedure]  
												@LogAction		= 'INSERT - CHG', 
												@LogNote		= 'Changed Records',
												@LogProcedure	= @RoutineName,
												@LogSQL			= 'Insert Into [bld].[LoadDependency]',
												@LogRowCount	= @@ROWCOUNT,
												@Log_TimeStart  = @StartDateTime,
												@Log_TimeEnd    = @EndDateTime;
	
	PRINT '-- deleted records:'
	
	SET @StartDateTime = getdate()
	
	INSERT INTO [bld].[LoadDependency]
	
	( 
	
		[BK] ,
		[Code] ,
		[BK_Target] ,
		[TGT_Layer] ,
		[TGT_Schema] ,
		[TGT_Group] ,
		[TGT_ShortName] ,
		[TGT_Code] ,
		[TGT_DatasetName] ,
		[BK_Source] ,
		[SRC_Layer] ,
		[SRC_Schema] ,
		[SRC_Group] ,
		[SRC_ShortName] ,
		[SRC_Code] ,
		[SRC_DatasetName] ,
		[DependencyType] ,
		[Generation_Number] 
		, [mta_BK], [mta_BKH], [mta_RH], [mta_Source], [mta_RecType]) 
	SELECT 
		src.[BK] ,
		src.[Code] ,
		src.[BK_Target] ,
		src.[TGT_Layer] ,
		src.[TGT_Schema] ,
		src.[TGT_Group] ,
		src.[TGT_ShortName] ,
		src.[TGT_Code] ,
		src.[TGT_DatasetName] ,
		src.[BK_Source] ,
		src.[SRC_Layer] ,
		src.[SRC_Schema] ,
		src.[SRC_Group] ,
		src.[SRC_ShortName] ,
		src.[SRC_Code] ,
		src.[SRC_DatasetName] ,
		src.[DependencyType] ,
		src.[Generation_Number] 
		, src.[mta_BK], src.[mta_BKH], src.[mta_RH], src.[mta_Source], [mta_RecType] = -1
	FROM  [bld].[vw_LoadDependency] src
	LEFT JOIN #420_LoadDependency_010_SrcToTgt h ON h.[mta_BKH] = src.[mta_BKH] AND h.[mta_Source] = src.[mta_Source]
	WHERE 1=1 AND h.[mta_BKH] IS null AND  src.mta_Source = '[bld].[tr_420_LoadDependency_010_SrcToTgt]'
	
	
	SET @EndDateTime = getutcdate()
	EXEC [aud].[proc_Log_Procedure]  
												@LogAction		= 'INSERT - DEL', 
												@LogNote		= 'Changed Deleted',
												@LogProcedure	= @RoutineName,
												@LogSQL			= 'Insert Into [bld].[LoadDependency]',
												@LogRowCount	= @@ROWCOUNT,
												@Log_TimeStart  = @StartDateTime,
												@Log_TimeEnd    = @EndDateTime
												;
	
	-- Clean up ...
	IF OBJECT_ID('tempdb..#420_LoadDependency_010_SrcToTgt') IS NOT NULL 
DROP TABLE #420_LoadDependency_010_SrcToTgt;
	
	SET @EndDateTime =  getutcdate()
	SET @Duration = datediff(SS,@StartDateTime, @EndDateTime)
	PRINT 'Load "load_420_LoadDependency_010_SrcToTgt" took ' +CAST(@Duration AS varchar(10))+ ' second(s)'