
	CREATE PROC [bld].[load_060_Layer_010_Default] AS
	/*
	Proc is generated by	: metro
	Generated at			: 2025-01-06 14:43:27
	
	exec [bld].[load_060_Layer_010_Default]*/

	
	DECLARE @RoutineName	varchar(8000)	= 'load_060_Layer_010_Default'
	DECLARE @StartDateTime	datetime2		=  getutcdate()
	DECLARE @EndDateTime	datetime2		
	DECLARE @Duration		bigint



	-- Create a helper temp table
	IF OBJECT_ID('tempdb..#060_Layer_010_Default') IS NOT NULL 
	DROP TABLE #060_Layer_010_Default ;
	PRINT '-- create temp table:'
	SELECT
	  mta_BK		= src.[BK]
	, mta_BKH		= CONVERT(char(64),(Hashbytes('sha2_512',upper(src.BK) )),2)
	, mta_RH		= CONVERT(char(64),(Hashbytes('sha2_512',upper(
								ISNULL(CAST(src.[bk] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[code] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[Layer_Name] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[Layer_Desciption] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[isDWHhelper] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[isRep] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[isAudit] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[isSRC] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[isDWH] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[isTGT] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[Layer_Process_Order] AS varchar(8000)),'-') 
							))),2)
	, mta_Source	= '[bld].[tr_060_Layer_010_Default]'
	, mta_RecType	= CASE 
												WHEN tgt.[BK] IS null THEN 1
												WHEN
												    tgt.[mta_RH]
												    !=  CONVERT(
												        char(64),
												        (
												            Hashbytes(
												                'sha2_512',
												                upper(
												                    ISNULL(CAST(src.[bk] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[code] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[Layer_Name] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[Layer_Desciption] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[isDWHhelper] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[isRep] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[isAudit] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[isSRC] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[isDWH] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[isTGT] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[Layer_Process_Order] AS varchar(8000)),'-')
												                )
												            )
												        ),
												        2
												    )
						THEN 0
						ELSE -99 END
	
	INTO #060_Layer_010_Default
	FROM [bld].[tr_060_Layer_010_Default] src
	LEFT JOIN [bld].[vw_Layer] tgt ON src.[BK] = tgt.[BK]
	
	
	
	CREATE CLUSTERED INDEX [IX_tr_060_Layer_010_Default] ON #060_Layer_010_Default( [mta_BKH] ASC,[mta_RH] ASC)
	
	
	--------------------- start loading data
	
	PRINT '-- new records:'
	
	SET @StartDateTime = getdate()
	
	INSERT INTO [bld].[Layer]
	( 
		[bk] ,[code] ,[Layer_Name] ,[Layer_Desciption] ,[isDWHhelper] ,[isRep] ,[isAudit] ,[isSRC] ,[isDWH] ,[isTGT] ,[Layer_Process_Order] 
		, [mta_BK], [mta_BKH], [mta_RH], [mta_Source], [mta_RecType]) 
	SELECT 
		src.[bk] ,
		src.[code] ,
		src.[Layer_Name] ,
		src.[Layer_Desciption] ,
		src.[isDWHhelper] ,
		src.[isRep] ,
		src.[isAudit] ,
		src.[isSRC] ,
		src.[isDWH] ,
		src.[isTGT] ,
		src.[Layer_Process_Order] 
		, h.[mta_BK], h.[mta_BKH], h.[mta_RH], h.[mta_Source], h.[mta_RecType]
	FROM  [bld].[tr_060_Layer_010_Default] src
	JOIN #060_Layer_010_Default h ON h.[mta_BK] = src.[BK]
	LEFT JOIN [bld].[vw_Layer] tgt ON h.[mta_BKH] = tgt.[mta_BKH] 
	WHERE 1=1 AND CAST(h.mta_RecType AS int) = 1 AND tgt.[mta_BKH] IS null
	
	
	SET @EndDateTime = getutcdate()
	EXEC [aud].[proc_Log_Procedure]  
							@LogAction		= 'INSERT - NEW', 
							@LogNote		= 'New Records',
							@LogProcedure	= @RoutineName,
							@LogSQL			= 'Insert Into [bld].[Layer]',
							@LogRowCount	= @@ROWCOUNT,
							@Log_TimeStart  = @StartDateTime,
							@Log_TimeEnd    = @EndDateTime;
	
	PRINT '-- changed records:'
	SET @StartDateTime = getdate()
	
		INSERT INTO [bld].[Layer]
	( 
		[bk] ,[code] ,[Layer_Name] ,[Layer_Desciption] ,[isDWHhelper] ,[isRep] ,[isAudit] ,[isSRC] ,[isDWH] ,[isTGT] ,[Layer_Process_Order] 
		, [mta_BK], [mta_BKH], [mta_RH], [mta_Source], [mta_RecType]) 
	SELECT 
		src.[bk] ,
		src.[code] ,
		src.[Layer_Name] ,
		src.[Layer_Desciption] ,
		src.[isDWHhelper] ,
		src.[isRep] ,
		src.[isAudit] ,
		src.[isSRC] ,
		src.[isDWH] ,
		src.[isTGT] ,
		src.[Layer_Process_Order] 
		, h.[mta_BK], h.[mta_BKH], h.[mta_RH], h.[mta_Source], h.[mta_RecType]
	FROM  [bld].[tr_060_Layer_010_Default] src
	JOIN #060_Layer_010_Default h ON h.[mta_BK] = src.[BK]
	WHERE 1=1 AND CAST(h.mta_RecType AS int) = 0

	
	SET @EndDateTime = getutcdate()
	EXEC [aud].[proc_Log_Procedure]  
												@LogAction		= 'INSERT - CHG', 
												@LogNote		= 'Changed Records',
												@LogProcedure	= @RoutineName,
												@LogSQL			= 'Insert Into [bld].[Layer]',
												@LogRowCount	= @@ROWCOUNT,
												@Log_TimeStart  = @StartDateTime,
												@Log_TimeEnd    = @EndDateTime;
	
	PRINT '-- deleted records:'
	
	SET @StartDateTime = getdate()
	
	INSERT INTO [bld].[Layer]
	
	( 
	
		[bk] ,[code] ,[Layer_Name] ,[Layer_Desciption] ,[isDWHhelper] ,[isRep] ,[isAudit] ,[isSRC] ,[isDWH] ,[isTGT] ,[Layer_Process_Order] 
		, [mta_BK], [mta_BKH], [mta_RH], [mta_Source], [mta_RecType]) 
	SELECT 
		src.[bk] ,
		src.[code] ,
		src.[Layer_Name] ,
		src.[Layer_Desciption] ,
		src.[isDWHhelper] ,
		src.[isRep] ,
		src.[isAudit] ,
		src.[isSRC] ,
		src.[isDWH] ,
		src.[isTGT] ,
		src.[Layer_Process_Order] 
		, src.[mta_BK], src.[mta_BKH], src.[mta_RH], src.[mta_Source], [mta_RecType] = -1
	FROM  [bld].[vw_Layer] src
	LEFT JOIN #060_Layer_010_Default h ON h.[mta_BKH] = src.[mta_BKH] AND h.[mta_Source] = src.[mta_Source]
	WHERE 1=1 AND h.[mta_BKH] IS null AND  src.mta_Source = '[bld].[tr_060_Layer_010_Default]'
	
	
	SET @EndDateTime = getutcdate()
	EXEC [aud].[proc_Log_Procedure]  
												@LogAction		= 'INSERT - DEL', 
												@LogNote		= 'Changed Deleted',
												@LogProcedure	= @RoutineName,
												@LogSQL			= 'Insert Into [bld].[Layer]',
												@LogRowCount	= @@ROWCOUNT,
												@Log_TimeStart  = @StartDateTime,
												@Log_TimeEnd    = @EndDateTime
												;
	
	-- Clean up ...
	IF OBJECT_ID('tempdb..#060_Layer_010_Default') IS NOT NULL 
DROP TABLE #060_Layer_010_Default;
	
	SET @EndDateTime =  getutcdate()
	SET @Duration = datediff(SS,@StartDateTime, @EndDateTime)
	PRINT 'Load "load_060_Layer_010_Default" took ' +CAST(@Duration AS varchar(10))+ ' second(s)'