
CREATE proc [bld].[load_600_template_010_default] AS /*
	Proc is generated by	: metro
	Generated at			: 2025-01-06 14:43:28

	exec [bld].[load_600_Template_010_Default]*/  DECLARE @routinename varchar(8000) = 'load_600_Template_010_Default' DECLARE @startdatetime datetime2 = getutcdate() DECLARE @enddatetime datetime2 DECLARE @duration bigint -- Create a helper temp table
 IF object_id('tempdb..#600_Template_010_Default') IS NOT NULL
DROP TABLE # 600_template_010_default ; PRINT '-- create temp table:'
SELECT mta_bk = src.[bk] ,

       mta_bkh = convert(char(64),(hashbytes('sha2_512', upper(src.bk))),2) ,

       mta_rh = convert(char(64),(hashbytes('sha2_512', upper(isnull(cast(src.[bk] AS varchar(8000)), '-') + '|' + isnull(cast(src.[code] AS varchar(8000)), '-') + '|' + isnull(cast(src.[templatename] AS varchar(8000)), '-') + '|' + isnull(cast(src.[templatetype] AS varchar(8000)), '-') + '|' + isnull(cast(src.[templatedecription] AS varchar(8000)), '-') + '|' + isnull(cast(src.[objecttype] AS varchar(8000)), '-') + '|' + isnull(cast(src.[objecttypedeployorder] AS varchar(8000)), '-') + '|' + isnull(cast(src.[script] AS varchar(8000)), '-') + '|' + isnull(cast(src.[scriptlanguagecode] AS varchar(8000)), '-') + '|' + isnull(cast(src.[scriptlanguage] AS varchar(8000)), '-') + '|' + isnull(cast(src.[objectname] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_reftype_templatetype] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_reftype_objecttype] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_reftype_objecttype_basedon] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_reftype_scriptlanguage] AS varchar(8000)), '-') + '|' + isnull(cast(src.[templateversion] AS varchar(8000)), '-')))),2) ,

       mta_source = '[bld].[tr_600_Template_010_Default]' ,

       mta_rectype = CASE
                         WHEN tgt.[bk] IS NULL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            THEN 1

            WHEN tgt.[mta_rh] != convert(char(64),(hashbytes('sha2_512', upper(isnull(cast(src.[bk] AS varchar(8000)), '-') + '|' + isnull(cast(src.[code] AS varchar(8000)), '-') + '|' + isnull(cast(src.[templatename] AS varchar(8000)), '-') + '|' + isnull(cast(src.[templatetype] AS varchar(8000)), '-') + '|' + isnull(cast(src.[templatedecription] AS varchar(8000)), '-') + '|' + isnull(cast(src.[objecttype] AS varchar(8000)), '-') + '|' + isnull(cast(src.[objecttypedeployorder] AS varchar(8000)), '-') + '|' + isnull(cast(src.[script] AS varchar(8000)), '-') + '|' + isnull(cast(src.[scriptlanguagecode] AS varchar(8000)), '-') + '|' + isnull(cast(src.[scriptlanguage] AS varchar(8000)), '-') + '|' + isnull(cast(src.[objectname] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_reftype_templatetype] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_reftype_objecttype] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_reftype_objecttype_basedon] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_reftype_scriptlanguage] AS varchar(8000)), '-') + '|' + isnull(cast(src.[templateversion] AS varchar(8000)), '-')))),2) THEN 0

            ELSE -99

             END INTO # 600_template_010_default

  FROM [bld].[tr_600_template_010_default] src

  LEFT JOIN [bld].[vw_template] tgt
    ON src.[bk] = tgt.[bk]
CREATE clustered INDEX [ix_tr_600_template_010_default]
    ON # 600_template_010_default([mta_bkh] ASC, [mta_rh] ASC) --------------------- start loading data
 PRINT '-- new records:'

   SET @startdatetime = getdate()
INSERT INTO [bld].[template] ([bk], [code], [templatename], [templatetype], [templatedecription], [objecttype], [objecttypedeployorder], [script], [scriptlanguagecode], [scriptlanguage], [objectname], [bk_reftype_templatetype], [bk_reftype_objecttype], [bk_reftype_objecttype_basedon], [bk_reftype_scriptlanguage], [templateversion] , [mta_bk], [mta_bkh], [mta_rh], [mta_source], [mta_rectype])
SELECT src.[bk],

       src.[code],

       src.[templatename],

       src.[templatetype],

       src.[templatedecription],

       src.[objecttype],

       src.[objecttypedeployorder],

       src.[script],

       src.[scriptlanguagecode],

       src.[scriptlanguage],

       src.[objectname],

       src.[bk_reftype_templatetype],

       src.[bk_reftype_objecttype],

       src.[bk_reftype_objecttype_basedon],

       src.[bk_reftype_scriptlanguage],

       src.[templateversion] ,

       h.[mta_bk],

       h.[mta_bkh],

       h.[mta_rh],

       h.[mta_source],

       h.[mta_rectype]

  FROM [bld].[tr_600_template_010_default] src

  JOIN # 600_template_010_default h
    ON h.[mta_bk] = src.[bk]

  LEFT JOIN [bld].[vw_template] tgt
    ON h.[mta_bkh] = tgt.[mta_bkh]

 WHERE 1 = 1

   AND cast(h.mta_rectype AS int) = 1

   AND tgt.[mta_bkh] IS NULL

   SET @enddatetime = getutcdate() EXEC [aud].[proc_log_procedure] @logaction = 'INSERT - NEW',

       @lognote = 'New Records',

       @logprocedure = @routinename,

       @logsql = 'Insert Into [bld].[Template]',

       @logrowcount = @@ rowcount,

       @log_timestart = @startdatetime,

       @log_timeend = @enddatetime; PRINT '-- changed records:'

   SET @startdatetime = getdate()
  INSERT INTO [bld].[template] ([bk], [code], [templatename], [templatetype], [templatedecription], [objecttype], [objecttypedeployorder], [script], [scriptlanguagecode], [scriptlanguage], [objectname], [bk_reftype_templatetype], [bk_reftype_objecttype], [bk_reftype_objecttype_basedon], [bk_reftype_scriptlanguage], [templateversion] , [mta_bk], [mta_bkh], [mta_rh], [mta_source], [mta_rectype])
SELECT src.[bk],

       src.[code],

       src.[templatename],

       src.[templatetype],

       src.[templatedecription],

       src.[objecttype],

       src.[objecttypedeployorder],

       src.[script],

       src.[scriptlanguagecode],

       src.[scriptlanguage],

       src.[objectname],

       src.[bk_reftype_templatetype],

       src.[bk_reftype_objecttype],

       src.[bk_reftype_objecttype_basedon],

       src.[bk_reftype_scriptlanguage],

       src.[templateversion] ,

       h.[mta_bk],

       h.[mta_bkh],

       h.[mta_rh],

       h.[mta_source],

       h.[mta_rectype]

  FROM [bld].[tr_600_template_010_default] src

  JOIN # 600_template_010_default h
    ON h.[mta_bk] = src.[bk]

 WHERE 1 = 1

   AND cast(h.mta_rectype AS int) = 0

   SET @enddatetime = getutcdate() EXEC [aud].[proc_log_procedure] @logaction = 'INSERT - CHG',

       @lognote = 'Changed Records',

       @logprocedure = @routinename,

       @logsql = 'Insert Into [bld].[Template]',

       @logrowcount = @@ rowcount,

       @log_timestart = @startdatetime,

       @log_timeend = @enddatetime; PRINT '-- deleted records:'

   SET @startdatetime = getdate()
  INSERT INTO [bld].[template] ([bk], [code], [templatename], [templatetype], [templatedecription], [objecttype], [objecttypedeployorder], [script], [scriptlanguagecode], [scriptlanguage], [objectname], [bk_reftype_templatetype], [bk_reftype_objecttype], [bk_reftype_objecttype_basedon], [bk_reftype_scriptlanguage], [templateversion] , [mta_bk], [mta_bkh], [mta_rh], [mta_source], [mta_rectype])
SELECT src.[bk],

       src.[code],

       src.[templatename],

       src.[templatetype],

       src.[templatedecription],

       src.[objecttype],

       src.[objecttypedeployorder],

       src.[script],

       src.[scriptlanguagecode],

       src.[scriptlanguage],

       src.[objectname],

       src.[bk_reftype_templatetype],

       src.[bk_reftype_objecttype],

       src.[bk_reftype_objecttype_basedon],

       src.[bk_reftype_scriptlanguage],

       src.[templateversion] ,

       src.[mta_bk],

       src.[mta_bkh],

       src.[mta_rh],

       src.[mta_source],

       [mta_rectype] = -1

  FROM [bld].[vw_template] src

  LEFT JOIN # 600_template_010_default h
    ON h.[mta_bkh] = src.[mta_bkh]

   AND h.[mta_source] = src.[mta_source]

 WHERE 1 = 1

   AND h.[mta_bkh] IS NULL

   AND src.mta_source = '[bld].[tr_600_Template_010_Default]'

   SET @enddatetime = getutcdate() EXEC [aud].[proc_log_procedure] @logaction = 'INSERT - DEL',

       @lognote = 'Changed Deleted',

       @logprocedure = @routinename,

       @logsql = 'Insert Into [bld].[Template]',

       @logrowcount = @@ rowcount,

       @log_timestart = @startdatetime,

       @log_timeend = @enddatetime ; -- Clean up ...
 IF object_id('tempdb..#600_Template_010_Default') IS NOT NULL
  DROP TABLE # 600_template_010_default;

   SET @enddatetime = getutcdate()

   SET @duration = datediff(ss, @startdatetime, @enddatetime) PRINT 'Load "load_600_Template_010_Default" took ' + cast(@duration AS varchar(10)) + ' second(s)'
