
	CREATE PROC [bld].[load_400_DatasetDependency_030_TransformationViewsDWH] AS
	/*
	Proc is generated by	: metro
	Generated at			: 2025-01-21 08:32:55
	
	exec [bld].[load_400_DatasetDependency_030_TransformationViewsDWH]*/

	
	DECLARE @RoutineName	varchar(8000)	= 'load_400_DatasetDependency_030_TransformationViewsDWH'
	DECLARE @StartDateTime	datetime2		=  getutcdate()
	DECLARE @EndDateTime	datetime2		
	DECLARE @Duration		bigint



	-- Create a helper temp table
	IF OBJECT_ID('tempdb..#400_DatasetDependency_030_TransformationViewsDWH') IS NOT NULL 
	DROP TABLE #400_DatasetDependency_030_TransformationViewsDWH ;
	PRINT '-- create temp table:'
	SELECT
	  mta_BK		= src.[BK]
	, mta_BKH		= CONVERT(char(64),(Hashbytes('sha2_512',upper(src.BK) )),2)
	, mta_RH		= CONVERT(char(64),(Hashbytes('sha2_512',upper(
								ISNULL(CAST(src.[BK] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[BK_Parent] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[BK_Child] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[Code] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[TableTypeParent] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[TableTypeChild] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[DependencyType] AS varchar(8000)),'-') 
							))),2)
	, mta_Source	= '[bld].[tr_400_DatasetDependency_030_TransformationViewsDWH]'
	, mta_RecType	= CASE 
												WHEN tgt.[BK] IS null THEN 1
												WHEN
												    tgt.[mta_RH]
												    !=  CONVERT(
												        char(64),
												        (
												            Hashbytes(
												                'sha2_512',
												                upper(
												                    ISNULL(CAST(src.[BK] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[BK_Parent] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[BK_Child] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[Code] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[TableTypeParent] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[TableTypeChild] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[DependencyType] AS varchar(8000)),'-')
												                )
												            )
												        ),
												        2
												    )
						THEN 0
						ELSE -99 END
	
	INTO #400_DatasetDependency_030_TransformationViewsDWH
	FROM [bld].[tr_400_DatasetDependency_030_TransformationViewsDWH] src
	LEFT JOIN [bld].[vw_DatasetDependency] tgt ON src.[BK] = tgt.[BK]
	
	
	
	CREATE CLUSTERED INDEX [IX_tr_400_DatasetDependency_030_TransformationViewsDWH]
	    ON #400_DatasetDependency_030_TransformationViewsDWH( [mta_BKH] ASC,[mta_RH] ASC)
	
	
	--------------------- start loading data
	
	PRINT '-- new records:'
	
	SET @StartDateTime = getdate()
	
	INSERT INTO [bld].[DatasetDependency]
	( 
		[BK] ,[BK_Parent] ,[BK_Child] ,[Code] ,[TableTypeParent] ,[TableTypeChild] ,[DependencyType] 
		, [mta_BK], [mta_BKH], [mta_RH], [mta_Source], [mta_RecType]) 
	SELECT 
		src.[BK] ,src.[BK_Parent] ,src.[BK_Child] ,src.[Code] ,src.[TableTypeParent] ,src.[TableTypeChild] ,src.[DependencyType] 
		, h.[mta_BK], h.[mta_BKH], h.[mta_RH], h.[mta_Source], h.[mta_RecType]
	FROM  [bld].[tr_400_DatasetDependency_030_TransformationViewsDWH] src
	JOIN #400_DatasetDependency_030_TransformationViewsDWH h ON h.[mta_BK] = src.[BK]
	LEFT JOIN [bld].[vw_DatasetDependency] tgt ON h.[mta_BKH] = tgt.[mta_BKH] 
	WHERE 1=1 AND CAST(h.mta_RecType AS int) = 1 AND tgt.[mta_BKH] IS null
	
	
	SET @EndDateTime = getutcdate()
	EXEC [aud].[proc_Log_Procedure]  
							@LogAction		= 'INSERT - NEW', 
							@LogNote		= 'New Records',
							@LogProcedure	= @RoutineName,
							@LogSQL			= 'Insert Into [bld].[DatasetDependency]',
							@LogRowCount	= @@ROWCOUNT,
							@Log_TimeStart  = @StartDateTime,
							@Log_TimeEnd    = @EndDateTime;
	
	PRINT '-- changed records:'
	SET @StartDateTime = getdate()
	
		INSERT INTO [bld].[DatasetDependency]
	( 
		[BK] ,[BK_Parent] ,[BK_Child] ,[Code] ,[TableTypeParent] ,[TableTypeChild] ,[DependencyType] 
		, [mta_BK], [mta_BKH], [mta_RH], [mta_Source], [mta_RecType]) 
	SELECT 
		src.[BK] ,src.[BK_Parent] ,src.[BK_Child] ,src.[Code] ,src.[TableTypeParent] ,src.[TableTypeChild] ,src.[DependencyType] 
		, h.[mta_BK], h.[mta_BKH], h.[mta_RH], h.[mta_Source], h.[mta_RecType]
	FROM  [bld].[tr_400_DatasetDependency_030_TransformationViewsDWH] src
	JOIN #400_DatasetDependency_030_TransformationViewsDWH h ON h.[mta_BK] = src.[BK]
	WHERE 1=1 AND CAST(h.mta_RecType AS int) = 0

	
	SET @EndDateTime = getutcdate()
	EXEC [aud].[proc_Log_Procedure]  
												@LogAction		= 'INSERT - CHG', 
												@LogNote		= 'Changed Records',
												@LogProcedure	= @RoutineName,
												@LogSQL			= 'Insert Into [bld].[DatasetDependency]',
												@LogRowCount	= @@ROWCOUNT,
												@Log_TimeStart  = @StartDateTime,
												@Log_TimeEnd    = @EndDateTime;
	
	PRINT '-- deleted records:'
	
	SET @StartDateTime = getdate()
	
	INSERT INTO [bld].[DatasetDependency]
	
	( 
	
		[BK] ,[BK_Parent] ,[BK_Child] ,[Code] ,[TableTypeParent] ,[TableTypeChild] ,[DependencyType] 
		, [mta_BK], [mta_BKH], [mta_RH], [mta_Source], [mta_RecType]) 
	SELECT 
		src.[BK] ,src.[BK_Parent] ,src.[BK_Child] ,src.[Code] ,src.[TableTypeParent] ,src.[TableTypeChild] ,src.[DependencyType] 
		, src.[mta_BK], src.[mta_BKH], src.[mta_RH], src.[mta_Source], [mta_RecType] = -1
	FROM  [bld].[vw_DatasetDependency] src
	LEFT JOIN #400_DatasetDependency_030_TransformationViewsDWH h ON h.[mta_BKH] = src.[mta_BKH] AND h.[mta_Source] = src.[mta_Source]
	WHERE 1=1 AND h.[mta_BKH] IS null AND  src.mta_Source = '[bld].[tr_400_DatasetDependency_030_TransformationViewsDWH]'
	
	
	SET @EndDateTime = getutcdate()
	EXEC [aud].[proc_Log_Procedure]  
												@LogAction		= 'INSERT - DEL', 
												@LogNote		= 'Changed Deleted',
												@LogProcedure	= @RoutineName,
												@LogSQL			= 'Insert Into [bld].[DatasetDependency]',
												@LogRowCount	= @@ROWCOUNT,
												@Log_TimeStart  = @StartDateTime,
												@Log_TimeEnd    = @EndDateTime
												;
	
	-- Clean up ...
	IF OBJECT_ID('tempdb..#400_DatasetDependency_030_TransformationViewsDWH') IS NOT NULL 
DROP TABLE #400_DatasetDependency_030_TransformationViewsDWH;
	
	SET @EndDateTime =  getutcdate()
	SET @Duration = datediff(SS,@StartDateTime, @EndDateTime)
	PRINT 'Load "load_400_DatasetDependency_030_TransformationViewsDWH" took ' +CAST(@Duration AS varchar(10))+ ' second(s)'