
	CREATE PROC [bld].[load_075_Flow_010_Default] AS
	/*
	Proc is generated by	: metro
	Generated at			: 2025-01-06 14:43:27
	
	exec [bld].[load_075_Flow_010_Default]*/

	
	DECLARE @RoutineName	varchar(8000)	= 'load_075_Flow_010_Default'
	DECLARE @StartDateTime	datetime2		=  getutcdate()
	DECLARE @EndDateTime	datetime2		
	DECLARE @Duration		bigint



	-- Create a helper temp table
	IF OBJECT_ID('tempdb..#075_Flow_010_Default') IS NOT NULL 
	DROP TABLE #075_Flow_010_Default ;
	PRINT '-- create temp table:'
	SELECT
	  mta_BK		= src.[BK]
	, mta_BKH		= CONVERT(char(64),(Hashbytes('sha2_512',upper(src.BK) )),2)
	, mta_RH		= CONVERT(char(64),(Hashbytes('sha2_512',upper(
								ISNULL(CAST(src.[BK] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[Code] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[BK_Flow] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[Flow_Name] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[Flow_Description] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[Flow_Layer_Step_Name] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[Flow_Layer_Step_Description] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[Flow_Layer_Step_Order] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[BK_Layer] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[BK_Schema] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[ReadFromView] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[BK_Template_Load] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[BK_Template_Create] AS varchar(8000)),'-') 
							))),2)
	, mta_Source	= '[bld].[tr_075_Flow_010_Default]'
	, mta_RecType	= CASE 
												WHEN tgt.[BK] IS null THEN 1
												WHEN
												    tgt.[mta_RH]
												    !=  CONVERT(
												        char(64),
												        (
												            Hashbytes(
												                'sha2_512',
												                upper(
												                    ISNULL(CAST(src.[BK] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[Code] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[BK_Flow] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[Flow_Name] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[Flow_Description] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[Flow_Layer_Step_Name] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[Flow_Layer_Step_Description] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[Flow_Layer_Step_Order] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[BK_Layer] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[BK_Schema] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[ReadFromView] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[BK_Template_Load] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[BK_Template_Create] AS varchar(8000)),'-')
												                )
												            )
												        ),
												        2
												    )
						THEN 0
						ELSE -99 END
	
	INTO #075_Flow_010_Default
	FROM [bld].[tr_075_Flow_010_Default] src
	LEFT JOIN [bld].[vw_Flow] tgt ON src.[BK] = tgt.[BK]
	
	
	
	CREATE CLUSTERED INDEX [IX_tr_075_Flow_010_Default] ON #075_Flow_010_Default( [mta_BKH] ASC,[mta_RH] ASC)
	
	
	--------------------- start loading data
	
	PRINT '-- new records:'
	
	SET @StartDateTime = getdate()
	
	INSERT INTO [bld].[Flow]
	( 
		[BK] ,
		[Code] ,
		[BK_Flow] ,
		[Flow_Name] ,
		[Flow_Description] ,
		[Flow_Layer_Step_Name] ,
		[Flow_Layer_Step_Description] ,
		[Flow_Layer_Step_Order] ,
		[BK_Layer] ,
		[BK_Schema] ,
		[ReadFromView] ,
		[BK_Template_Load] ,
		[BK_Template_Create] 
		, [mta_BK], [mta_BKH], [mta_RH], [mta_Source], [mta_RecType]) 
	SELECT 
		src.[BK] ,
		src.[Code] ,
		src.[BK_Flow] ,
		src.[Flow_Name] ,
		src.[Flow_Description] ,
		src.[Flow_Layer_Step_Name] ,
		src.[Flow_Layer_Step_Description] ,
		src.[Flow_Layer_Step_Order] ,
		src.[BK_Layer] ,
		src.[BK_Schema] ,
		src.[ReadFromView] ,
		src.[BK_Template_Load] ,
		src.[BK_Template_Create] 
		, h.[mta_BK], h.[mta_BKH], h.[mta_RH], h.[mta_Source], h.[mta_RecType]
	FROM  [bld].[tr_075_Flow_010_Default] src
	JOIN #075_Flow_010_Default h ON h.[mta_BK] = src.[BK]
	LEFT JOIN [bld].[vw_Flow] tgt ON h.[mta_BKH] = tgt.[mta_BKH] 
	WHERE 1=1 AND CAST(h.mta_RecType AS int) = 1 AND tgt.[mta_BKH] IS null
	
	
	SET @EndDateTime = getutcdate()
	EXEC [aud].[proc_Log_Procedure]  
							@LogAction		= 'INSERT - NEW', 
							@LogNote		= 'New Records',
							@LogProcedure	= @RoutineName,
							@LogSQL			= 'Insert Into [bld].[Flow]',
							@LogRowCount	= @@ROWCOUNT,
							@Log_TimeStart  = @StartDateTime,
							@Log_TimeEnd    = @EndDateTime;
	
	PRINT '-- changed records:'
	SET @StartDateTime = getdate()
	
		INSERT INTO [bld].[Flow]
	( 
		[BK] ,
		[Code] ,
		[BK_Flow] ,
		[Flow_Name] ,
		[Flow_Description] ,
		[Flow_Layer_Step_Name] ,
		[Flow_Layer_Step_Description] ,
		[Flow_Layer_Step_Order] ,
		[BK_Layer] ,
		[BK_Schema] ,
		[ReadFromView] ,
		[BK_Template_Load] ,
		[BK_Template_Create] 
		, [mta_BK], [mta_BKH], [mta_RH], [mta_Source], [mta_RecType]) 
	SELECT 
		src.[BK] ,
		src.[Code] ,
		src.[BK_Flow] ,
		src.[Flow_Name] ,
		src.[Flow_Description] ,
		src.[Flow_Layer_Step_Name] ,
		src.[Flow_Layer_Step_Description] ,
		src.[Flow_Layer_Step_Order] ,
		src.[BK_Layer] ,
		src.[BK_Schema] ,
		src.[ReadFromView] ,
		src.[BK_Template_Load] ,
		src.[BK_Template_Create] 
		, h.[mta_BK], h.[mta_BKH], h.[mta_RH], h.[mta_Source], h.[mta_RecType]
	FROM  [bld].[tr_075_Flow_010_Default] src
	JOIN #075_Flow_010_Default h ON h.[mta_BK] = src.[BK]
	WHERE 1=1 AND CAST(h.mta_RecType AS int) = 0

	
	SET @EndDateTime = getutcdate()
	EXEC [aud].[proc_Log_Procedure]  
												@LogAction		= 'INSERT - CHG', 
												@LogNote		= 'Changed Records',
												@LogProcedure	= @RoutineName,
												@LogSQL			= 'Insert Into [bld].[Flow]',
												@LogRowCount	= @@ROWCOUNT,
												@Log_TimeStart  = @StartDateTime,
												@Log_TimeEnd    = @EndDateTime;
	
	PRINT '-- deleted records:'
	
	SET @StartDateTime = getdate()
	
	INSERT INTO [bld].[Flow]
	
	( 
	
		[BK] ,
		[Code] ,
		[BK_Flow] ,
		[Flow_Name] ,
		[Flow_Description] ,
		[Flow_Layer_Step_Name] ,
		[Flow_Layer_Step_Description] ,
		[Flow_Layer_Step_Order] ,
		[BK_Layer] ,
		[BK_Schema] ,
		[ReadFromView] ,
		[BK_Template_Load] ,
		[BK_Template_Create] 
		, [mta_BK], [mta_BKH], [mta_RH], [mta_Source], [mta_RecType]) 
	SELECT 
		src.[BK] ,
		src.[Code] ,
		src.[BK_Flow] ,
		src.[Flow_Name] ,
		src.[Flow_Description] ,
		src.[Flow_Layer_Step_Name] ,
		src.[Flow_Layer_Step_Description] ,
		src.[Flow_Layer_Step_Order] ,
		src.[BK_Layer] ,
		src.[BK_Schema] ,
		src.[ReadFromView] ,
		src.[BK_Template_Load] ,
		src.[BK_Template_Create] 
		, src.[mta_BK], src.[mta_BKH], src.[mta_RH], src.[mta_Source], [mta_RecType] = -1
	FROM  [bld].[vw_Flow] src
	LEFT JOIN #075_Flow_010_Default h ON h.[mta_BKH] = src.[mta_BKH] AND h.[mta_Source] = src.[mta_Source]
	WHERE 1=1 AND h.[mta_BKH] IS null AND  src.mta_Source = '[bld].[tr_075_Flow_010_Default]'
	
	
	SET @EndDateTime = getutcdate()
	EXEC [aud].[proc_Log_Procedure]  
												@LogAction		= 'INSERT - DEL', 
												@LogNote		= 'Changed Deleted',
												@LogProcedure	= @RoutineName,
												@LogSQL			= 'Insert Into [bld].[Flow]',
												@LogRowCount	= @@ROWCOUNT,
												@Log_TimeStart  = @StartDateTime,
												@Log_TimeEnd    = @EndDateTime
												;
	
	-- Clean up ...
	IF OBJECT_ID('tempdb..#075_Flow_010_Default') IS NOT NULL 
DROP TABLE #075_Flow_010_Default;
	
	SET @EndDateTime =  getutcdate()
	SET @Duration = datediff(SS,@StartDateTime, @EndDateTime)
	PRINT 'Load "load_075_Flow_010_Default" took ' +CAST(@Duration AS varchar(10))+ ' second(s)'