
	create proc [bld].[load_230_Attribute_030_AddMtaAttributes] as
	/*
	Proc is generated by	: metro
	Generated at			: 2025-01-06 14:43:27
	makes use of Smartload!
	exec [bld].[load_230_Attribute_030_AddMtaAttributes]*/

	
	Declare @RoutineName	varchar(8000)	= 'load_230_Attribute_030_AddMtaAttributes'
	Declare @StartDateTime	datetime2		=  getutcdate()
	Declare @EndDateTime	datetime2		
	Declare @Duration		bigint



	-- Create a helper temp table
	If OBJECT_ID('tempdb..#230_Attribute_030_AddMtaAttributes') IS NOT NULL 
	Drop Table #230_Attribute_030_AddMtaAttributes ;
	Print '-- create temp table:'
	Select
	  mta_BK		= src.[BK]
	, mta_BKH		= Convert(char(64),(Hashbytes('sha2_512',upper(src.BK) )),2)
	, mta_RH		= Convert(char(64),(Hashbytes('sha2_512',upper(
								ISNULL(Cast(src.[BK] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[Code] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[Name] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[BK_Dataset] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[Dataset] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[AttributeName] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[Description] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[Expression] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[DistributionHashKey] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[NotInRH] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[BusinessKey] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[isMta] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[SrcName] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[BK_RefType_DataType] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[DataType] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[FixedSchemaDataType] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[OrgMappedDataType] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[Isnullable] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[OrdinalPosition] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[MaximumLength] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[Precision] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[Scale] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[Collation] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[DefaultValue] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[Active] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[FlowOrder] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[BK_RefType_ObjectType] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[BK_RefType_RepositoryStatus] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[DDL_Type1] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[DDL_Type2] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[DDL_Type3] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[DDL_Type4] as varchar(8000)),'-') 
							))),2)
	, mta_Source	= '[bld].[tr_230_Attribute_030_AddMtaAttributes]'
	, mta_RecType	= diff.RecType
	Into #230_Attribute_030_AddMtaAttributes
	From [bld].[tr_230_Attribute_030_AddMtaAttributes] src
	Left join [bld].[vw_Attribute] tgt on src.[BK] = tgt.[BK]
	join [bld].[vw_AttributeSmartLoad] diff on diff.code =  src.code
	where 1=1  and  cast(diff.RecType as int) > -99
	
	Create Clustered INDEX [IX_tr_230_Attribute_030_AddMtaAttributes] ON #230_Attribute_030_AddMtaAttributes( [mta_BKH] ASC,[mta_RH] ASC)
	
	
	--------------------- start loading data
	
	Print '-- new records:'
	
	set @StartDateTime = getdate()
	
	Insert Into [bld].[Attribute]
	( 
		[BK] ,[Code] ,[Name] ,[BK_Dataset] ,[Dataset] ,[AttributeName] ,[Description] ,[Expression] ,[DistributionHashKey] ,[NotInRH] ,[BusinessKey] ,[isMta] ,[SrcName] ,[BK_RefType_DataType] ,[DataType] ,[FixedSchemaDataType] ,[OrgMappedDataType] ,[Isnullable] ,[OrdinalPosition] ,[MaximumLength] ,[Precision] ,[Scale] ,[Collation] ,[DefaultValue] ,[Active] ,[FlowOrder] ,[BK_RefType_ObjectType] ,[BK_RefType_RepositoryStatus] ,[DDL_Type1] ,[DDL_Type2] ,[DDL_Type3] ,[DDL_Type4] 
		, [mta_BK], [mta_BKH], [mta_RH], [mta_Source], [mta_RecType]) 
	select 
		src.[BK] ,src.[Code] ,src.[Name] ,src.[BK_Dataset] ,src.[Dataset] ,src.[AttributeName] ,src.[Description] ,src.[Expression] ,src.[DistributionHashKey] ,src.[NotInRH] ,src.[BusinessKey] ,src.[isMta] ,src.[SrcName] ,src.[BK_RefType_DataType] ,src.[DataType] ,src.[FixedSchemaDataType] ,src.[OrgMappedDataType] ,src.[Isnullable] ,src.[OrdinalPosition] ,src.[MaximumLength] ,src.[Precision] ,src.[Scale] ,src.[Collation] ,src.[DefaultValue] ,src.[Active] ,src.[FlowOrder] ,src.[BK_RefType_ObjectType] ,src.[BK_RefType_RepositoryStatus] ,src.[DDL_Type1] ,src.[DDL_Type2] ,src.[DDL_Type3] ,src.[DDL_Type4] 
		, h.[mta_BK], h.[mta_BKH], h.[mta_RH], h.[mta_Source], h.[mta_RecType]
	From  [bld].[tr_230_Attribute_030_AddMtaAttributes] src
	Join #230_Attribute_030_AddMtaAttributes h on h.[mta_BK] = src.[BK]
	Left Join [bld].[vw_Attribute] tgt on h.[mta_BKH] = tgt.[mta_BKH] 
	Where 1=1 and cast(h.mta_RecType as int) = 1 and tgt.[mta_BKH] is null
	
	
	set @EndDateTime = getutcdate()
	exec [aud].[proc_Log_Procedure]  
							@LogAction		= 'INSERT - NEW', 
							@LogNote		= 'New Records',
							@LogProcedure	= @RoutineName,
							@LogSQL			= 'Insert Into [bld].[Attribute]',
							@LogRowCount	= @@ROWCOUNT,
							@Log_TimeStart  = @StartDateTime,
							@Log_TimeEnd    = @EndDateTime;
	
	Print '-- changed records:'
	set @StartDateTime = getdate()
	
		Insert Into [bld].[Attribute]
	( 
		[BK] ,[Code] ,[Name] ,[BK_Dataset] ,[Dataset] ,[AttributeName] ,[Description] ,[Expression] ,[DistributionHashKey] ,[NotInRH] ,[BusinessKey] ,[isMta] ,[SrcName] ,[BK_RefType_DataType] ,[DataType] ,[FixedSchemaDataType] ,[OrgMappedDataType] ,[Isnullable] ,[OrdinalPosition] ,[MaximumLength] ,[Precision] ,[Scale] ,[Collation] ,[DefaultValue] ,[Active] ,[FlowOrder] ,[BK_RefType_ObjectType] ,[BK_RefType_RepositoryStatus] ,[DDL_Type1] ,[DDL_Type2] ,[DDL_Type3] ,[DDL_Type4] 
		, [mta_BK], [mta_BKH], [mta_RH], [mta_Source], [mta_RecType]) 
	select 
		src.[BK] ,src.[Code] ,src.[Name] ,src.[BK_Dataset] ,src.[Dataset] ,src.[AttributeName] ,src.[Description] ,src.[Expression] ,src.[DistributionHashKey] ,src.[NotInRH] ,src.[BusinessKey] ,src.[isMta] ,src.[SrcName] ,src.[BK_RefType_DataType] ,src.[DataType] ,src.[FixedSchemaDataType] ,src.[OrgMappedDataType] ,src.[Isnullable] ,src.[OrdinalPosition] ,src.[MaximumLength] ,src.[Precision] ,src.[Scale] ,src.[Collation] ,src.[DefaultValue] ,src.[Active] ,src.[FlowOrder] ,src.[BK_RefType_ObjectType] ,src.[BK_RefType_RepositoryStatus] ,src.[DDL_Type1] ,src.[DDL_Type2] ,src.[DDL_Type3] ,src.[DDL_Type4] 
		, h.[mta_BK], h.[mta_BKH], h.[mta_RH], h.[mta_Source], h.[mta_RecType]
	From  [bld].[tr_230_Attribute_030_AddMtaAttributes] src
	Join #230_Attribute_030_AddMtaAttributes h on h.[mta_BK] = src.[BK]
	Where 1=1 and cast(h.mta_RecType as int) = 0

	
	set @EndDateTime = getutcdate()
	exec [aud].[proc_Log_Procedure]  
												@LogAction		= 'INSERT - CHG', 
												@LogNote		= 'Changed Records',
												@LogProcedure	= @RoutineName,
												@LogSQL			= 'Insert Into [bld].[Attribute]',
												@LogRowCount	= @@ROWCOUNT,
												@Log_TimeStart  = @StartDateTime,
												@Log_TimeEnd    = @EndDateTime;
	
	Print '-- deleted records:'
	
	set @StartDateTime = getdate()
	
	Insert Into [bld].[Attribute]
	
	( 
	
		[BK] ,[Code] ,[Name] ,[BK_Dataset] ,[Dataset] ,[AttributeName] ,[Description] ,[Expression] ,[DistributionHashKey] ,[NotInRH] ,[BusinessKey] ,[isMta] ,[SrcName] ,[BK_RefType_DataType] ,[DataType] ,[FixedSchemaDataType] ,[OrgMappedDataType] ,[Isnullable] ,[OrdinalPosition] ,[MaximumLength] ,[Precision] ,[Scale] ,[Collation] ,[DefaultValue] ,[Active] ,[FlowOrder] ,[BK_RefType_ObjectType] ,[BK_RefType_RepositoryStatus] ,[DDL_Type1] ,[DDL_Type2] ,[DDL_Type3] ,[DDL_Type4] 
		, [mta_BK], [mta_BKH], [mta_RH], [mta_Source], [mta_RecType]) 
	select 
		src.[BK] ,src.[Code] ,src.[Name] ,src.[BK_Dataset] ,src.[Dataset] ,src.[AttributeName] ,src.[Description] ,src.[Expression] ,src.[DistributionHashKey] ,src.[NotInRH] ,src.[BusinessKey] ,src.[isMta] ,src.[SrcName] ,src.[BK_RefType_DataType] ,src.[DataType] ,src.[FixedSchemaDataType] ,src.[OrgMappedDataType] ,src.[Isnullable] ,src.[OrdinalPosition] ,src.[MaximumLength] ,src.[Precision] ,src.[Scale] ,src.[Collation] ,src.[DefaultValue] ,src.[Active] ,src.[FlowOrder] ,src.[BK_RefType_ObjectType] ,src.[BK_RefType_RepositoryStatus] ,src.[DDL_Type1] ,src.[DDL_Type2] ,src.[DDL_Type3] ,src.[DDL_Type4] 
		, src.[mta_BK], src.[mta_BKH], src.[mta_RH], src.[mta_Source], [mta_RecType] = -1
	From  [bld].[vw_Attribute] src
	Left Join #230_Attribute_030_AddMtaAttributes h on h.[mta_BKH] = src.[mta_BKH] and h.[mta_Source] = src.[mta_Source]
	Where 1=1 and h.[mta_BKH] is null and  src.mta_Source = '[bld].[tr_230_Attribute_030_AddMtaAttributes]'
	and  h.mta_RecType =-1
	
	set @EndDateTime = getutcdate()
	exec [aud].[proc_Log_Procedure]  
												@LogAction		= 'INSERT - DEL', 
												@LogNote		= 'Changed Deleted',
												@LogProcedure	= @RoutineName,
												@LogSQL			= 'Insert Into [bld].[Attribute]',
												@LogRowCount	= @@ROWCOUNT,
												@Log_TimeStart  = @StartDateTime,
												@Log_TimeEnd    = @EndDateTime
												;
	
	-- Clean up ...
	If OBJECT_ID('tempdb..#230_Attribute_030_AddMtaAttributes') IS NOT NULL 
Drop Table #230_Attribute_030_AddMtaAttributes;
	
	set @EndDateTime =  getutcdate()
	set @Duration = datediff(ss,@StartDateTime, @EndDateTime)
	print 'Load "load_230_Attribute_030_AddMtaAttributes" took ' +cast(@Duration as varchar(10))+ ' second(s)'