
	create proc [bld].[load_060_Layer_010_Default] as
	/*
	Proc is generated by	: metro
	Generated at			: 2025-01-06 14:43:27
	
	exec [bld].[load_060_Layer_010_Default]*/

	
	Declare @RoutineName	varchar(8000)	= 'load_060_Layer_010_Default'
	Declare @StartDateTime	datetime2		=  getutcdate()
	Declare @EndDateTime	datetime2		
	Declare @Duration		bigint



	-- Create a helper temp table
	If OBJECT_ID('tempdb..#060_Layer_010_Default') IS NOT NULL 
	Drop Table #060_Layer_010_Default ;
	Print '-- create temp table:'
	Select
	  mta_BK		= src.[BK]
	, mta_BKH		= Convert(char(64),(Hashbytes('sha2_512',upper(src.BK) )),2)
	, mta_RH		= Convert(char(64),(Hashbytes('sha2_512',upper(
								ISNULL(Cast(src.[bk] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[code] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[Layer_Name] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[Layer_Desciption] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[isDWHhelper] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[isRep] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[isAudit] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[isSRC] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[isDWH] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[isTGT] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[Layer_Process_Order] as varchar(8000)),'-') 
							))),2)
	, mta_Source	= '[bld].[tr_060_Layer_010_Default]'
	, mta_RecType	= case 
												when tgt.[BK] is null then 1
												when tgt.[mta_RH] !=  Convert(char(64),(Hashbytes('sha2_512',upper(ISNULL(Cast(src.[bk] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[code] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[Layer_Name] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[Layer_Desciption] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[isDWHhelper] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[isRep] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[isAudit] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[isSRC] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[isDWH] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[isTGT] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[Layer_Process_Order] as varchar(8000)),'-') ))),2)
						then 0
						else -99 end
	
	Into #060_Layer_010_Default
	From [bld].[tr_060_Layer_010_Default] src
	Left join [bld].[vw_Layer] tgt on src.[BK] = tgt.[BK]
	
	
	
	Create Clustered INDEX [IX_tr_060_Layer_010_Default] ON #060_Layer_010_Default( [mta_BKH] ASC,[mta_RH] ASC)
	
	
	--------------------- start loading data
	
	Print '-- new records:'
	
	set @StartDateTime = getdate()
	
	Insert Into [bld].[Layer]
	( 
		[bk] ,[code] ,[Layer_Name] ,[Layer_Desciption] ,[isDWHhelper] ,[isRep] ,[isAudit] ,[isSRC] ,[isDWH] ,[isTGT] ,[Layer_Process_Order] 
		, [mta_BK], [mta_BKH], [mta_RH], [mta_Source], [mta_RecType]) 
	select 
		src.[bk] ,src.[code] ,src.[Layer_Name] ,src.[Layer_Desciption] ,src.[isDWHhelper] ,src.[isRep] ,src.[isAudit] ,src.[isSRC] ,src.[isDWH] ,src.[isTGT] ,src.[Layer_Process_Order] 
		, h.[mta_BK], h.[mta_BKH], h.[mta_RH], h.[mta_Source], h.[mta_RecType]
	From  [bld].[tr_060_Layer_010_Default] src
	Join #060_Layer_010_Default h on h.[mta_BK] = src.[BK]
	Left Join [bld].[vw_Layer] tgt on h.[mta_BKH] = tgt.[mta_BKH] 
	Where 1=1 and cast(h.mta_RecType as int) = 1 and tgt.[mta_BKH] is null
	
	
	set @EndDateTime = getutcdate()
	exec [aud].[proc_Log_Procedure]  
							@LogAction		= 'INSERT - NEW', 
							@LogNote		= 'New Records',
							@LogProcedure	= @RoutineName,
							@LogSQL			= 'Insert Into [bld].[Layer]',
							@LogRowCount	= @@ROWCOUNT,
							@Log_TimeStart  = @StartDateTime,
							@Log_TimeEnd    = @EndDateTime;
	
	Print '-- changed records:'
	set @StartDateTime = getdate()
	
		Insert Into [bld].[Layer]
	( 
		[bk] ,[code] ,[Layer_Name] ,[Layer_Desciption] ,[isDWHhelper] ,[isRep] ,[isAudit] ,[isSRC] ,[isDWH] ,[isTGT] ,[Layer_Process_Order] 
		, [mta_BK], [mta_BKH], [mta_RH], [mta_Source], [mta_RecType]) 
	select 
		src.[bk] ,src.[code] ,src.[Layer_Name] ,src.[Layer_Desciption] ,src.[isDWHhelper] ,src.[isRep] ,src.[isAudit] ,src.[isSRC] ,src.[isDWH] ,src.[isTGT] ,src.[Layer_Process_Order] 
		, h.[mta_BK], h.[mta_BKH], h.[mta_RH], h.[mta_Source], h.[mta_RecType]
	From  [bld].[tr_060_Layer_010_Default] src
	Join #060_Layer_010_Default h on h.[mta_BK] = src.[BK]
	Where 1=1 and cast(h.mta_RecType as int) = 0

	
	set @EndDateTime = getutcdate()
	exec [aud].[proc_Log_Procedure]  
												@LogAction		= 'INSERT - CHG', 
												@LogNote		= 'Changed Records',
												@LogProcedure	= @RoutineName,
												@LogSQL			= 'Insert Into [bld].[Layer]',
												@LogRowCount	= @@ROWCOUNT,
												@Log_TimeStart  = @StartDateTime,
												@Log_TimeEnd    = @EndDateTime;
	
	Print '-- deleted records:'
	
	set @StartDateTime = getdate()
	
	Insert Into [bld].[Layer]
	
	( 
	
		[bk] ,[code] ,[Layer_Name] ,[Layer_Desciption] ,[isDWHhelper] ,[isRep] ,[isAudit] ,[isSRC] ,[isDWH] ,[isTGT] ,[Layer_Process_Order] 
		, [mta_BK], [mta_BKH], [mta_RH], [mta_Source], [mta_RecType]) 
	select 
		src.[bk] ,src.[code] ,src.[Layer_Name] ,src.[Layer_Desciption] ,src.[isDWHhelper] ,src.[isRep] ,src.[isAudit] ,src.[isSRC] ,src.[isDWH] ,src.[isTGT] ,src.[Layer_Process_Order] 
		, src.[mta_BK], src.[mta_BKH], src.[mta_RH], src.[mta_Source], [mta_RecType] = -1
	From  [bld].[vw_Layer] src
	Left Join #060_Layer_010_Default h on h.[mta_BKH] = src.[mta_BKH] and h.[mta_Source] = src.[mta_Source]
	Where 1=1 and h.[mta_BKH] is null and  src.mta_Source = '[bld].[tr_060_Layer_010_Default]'
	
	
	set @EndDateTime = getutcdate()
	exec [aud].[proc_Log_Procedure]  
												@LogAction		= 'INSERT - DEL', 
												@LogNote		= 'Changed Deleted',
												@LogProcedure	= @RoutineName,
												@LogSQL			= 'Insert Into [bld].[Layer]',
												@LogRowCount	= @@ROWCOUNT,
												@Log_TimeStart  = @StartDateTime,
												@Log_TimeEnd    = @EndDateTime
												;
	
	-- Clean up ...
	If OBJECT_ID('tempdb..#060_Layer_010_Default') IS NOT NULL 
Drop Table #060_Layer_010_Default;
	
	set @EndDateTime =  getutcdate()
	set @Duration = datediff(ss,@StartDateTime, @EndDateTime)
	print 'Load "load_060_Layer_010_Default" took ' +cast(@Duration as varchar(10))+ ' second(s)'