
	CREATE PROC [bld].[load_110_FileProperties_010_DatasetSrc] AS
	/*
	Proc is generated by	: metro
	Generated at			: 2025-01-06 14:43:27
	
	exec [bld].[load_110_FileProperties_010_DatasetSrc]*/

	
	DECLARE @RoutineName	varchar(8000)	= 'load_110_FileProperties_010_DatasetSrc'
	DECLARE @StartDateTime	datetime2		=  getutcdate()
	DECLARE @EndDateTime	datetime2		
	DECLARE @Duration		bigint



	-- Create a helper temp table
	IF OBJECT_ID('tempdb..#110_FileProperties_010_DatasetSrc') IS NOT NULL 
	DROP TABLE #110_FileProperties_010_DatasetSrc ;
	PRINT '-- create temp table:'
	SELECT
	  mta_BK		= src.[BK]
	, mta_BKH		= CONVERT(char(64),(Hashbytes('sha2_512',upper(src.BK) )),2)
	, mta_RH		= CONVERT(char(64),(Hashbytes('sha2_512',upper(
								ISNULL(CAST(src.[BK] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[Code] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[Description] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[FileMask] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[Filename] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[FileSystem] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[Folder] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[isPGP] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[ExpectedFileCount] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[ExpectedFileSize] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[bk_schedule_FileExpected] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[DateInFileNameFormat] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[DateinFileNameLength] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[DateInFileNameStartPos] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[DateInFileNameExpression] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[TestDateInFileName] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[FF_Name] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[FF_Fileformat] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[FF_ColumnDelimiter] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[FF_RowDelimiter] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[FF_QuoteCharacter] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[FF_CompressionLevel] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[FF_CompressionType] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[FF_EnableCDC] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[FF_EscapeCharacter] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[FF_FileEncoding] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[FF_FirstRow] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[FF_FirstRowAsHeader] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[FF_Filesize] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[FF_Threshold] AS varchar(8000)),'-') 
							))),2)
	, mta_Source	= '[bld].[tr_110_FileProperties_010_DatasetSrc]'
	, mta_RecType	= CASE 
												WHEN tgt.[BK] IS null THEN 1
												WHEN
												    tgt.[mta_RH]
												    !=  CONVERT(
												        char(64),
												        (
												            Hashbytes(
												                'sha2_512',
												                upper(
												                    ISNULL(CAST(src.[BK] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[Code] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[Description] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[FileMask] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[Filename] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[FileSystem] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[Folder] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[isPGP] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[ExpectedFileCount] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[ExpectedFileSize] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[bk_schedule_FileExpected] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[DateInFileNameFormat] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[DateinFileNameLength] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[DateInFileNameStartPos] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[DateInFileNameExpression] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[TestDateInFileName] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[FF_Name] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[FF_Fileformat] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[FF_ColumnDelimiter] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[FF_RowDelimiter] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[FF_QuoteCharacter] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[FF_CompressionLevel] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[FF_CompressionType] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[FF_EnableCDC] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[FF_EscapeCharacter] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[FF_FileEncoding] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[FF_FirstRow] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[FF_FirstRowAsHeader] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[FF_Filesize] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[FF_Threshold] AS varchar(8000)),'-')
												                )
												            )
												        ),
												        2
												    )
						THEN 0
						ELSE -99 END
	
	INTO #110_FileProperties_010_DatasetSrc
	FROM [bld].[tr_110_FileProperties_010_DatasetSrc] src
	LEFT JOIN [bld].[vw_FileProperties] tgt ON src.[BK] = tgt.[BK]
	
	
	
	CREATE CLUSTERED INDEX [IX_tr_110_FileProperties_010_DatasetSrc] ON #110_FileProperties_010_DatasetSrc( [mta_BKH] ASC,[mta_RH] ASC)
	
	
	--------------------- start loading data
	
	PRINT '-- new records:'
	
	SET @StartDateTime = getdate()
	
	INSERT INTO [bld].[FileProperties]
	( 
		[BK] ,
		[Code] ,
		[Description] ,
		[FileMask] ,
		[Filename] ,
		[FileSystem] ,
		[Folder] ,
		[isPGP] ,
		[ExpectedFileCount] ,
		[ExpectedFileSize] ,
		[bk_schedule_FileExpected] ,
		[DateInFileNameFormat] ,
		[DateinFileNameLength] ,
		[DateInFileNameStartPos] ,
		[DateInFileNameExpression] ,
		[TestDateInFileName] ,
		[FF_Name] ,
		[FF_Fileformat] ,
		[FF_ColumnDelimiter] ,
		[FF_RowDelimiter] ,
		[FF_QuoteCharacter] ,
		[FF_CompressionLevel] ,
		[FF_CompressionType] ,
		[FF_EnableCDC] ,
		[FF_EscapeCharacter] ,
		[FF_FileEncoding] ,
		[FF_FirstRow] ,
		[FF_FirstRowAsHeader] ,
		[FF_Filesize] ,
		[FF_Threshold] 
		, [mta_BK], [mta_BKH], [mta_RH], [mta_Source], [mta_RecType]) 
	SELECT 
		src.[BK] ,
		src.[Code] ,
		src.[Description] ,
		src.[FileMask] ,
		src.[Filename] ,
		src.[FileSystem] ,
		src.[Folder] ,
		src.[isPGP] ,
		src.[ExpectedFileCount] ,
		src.[ExpectedFileSize] ,
		src.[bk_schedule_FileExpected] ,
		src.[DateInFileNameFormat] ,
		src.[DateinFileNameLength] ,
		src.[DateInFileNameStartPos] ,
		src.[DateInFileNameExpression] ,
		src.[TestDateInFileName] ,
		src.[FF_Name] ,
		src.[FF_Fileformat] ,
		src.[FF_ColumnDelimiter] ,
		src.[FF_RowDelimiter] ,
		src.[FF_QuoteCharacter] ,
		src.[FF_CompressionLevel] ,
		src.[FF_CompressionType] ,
		src.[FF_EnableCDC] ,
		src.[FF_EscapeCharacter] ,
		src.[FF_FileEncoding] ,
		src.[FF_FirstRow] ,
		src.[FF_FirstRowAsHeader] ,
		src.[FF_Filesize] ,
		src.[FF_Threshold] 
		, h.[mta_BK], h.[mta_BKH], h.[mta_RH], h.[mta_Source], h.[mta_RecType]
	FROM  [bld].[tr_110_FileProperties_010_DatasetSrc] src
	JOIN #110_FileProperties_010_DatasetSrc h ON h.[mta_BK] = src.[BK]
	LEFT JOIN [bld].[vw_FileProperties] tgt ON h.[mta_BKH] = tgt.[mta_BKH] 
	WHERE 1=1 AND CAST(h.mta_RecType AS int) = 1 AND tgt.[mta_BKH] IS null
	
	
	SET @EndDateTime = getutcdate()
	EXEC [aud].[proc_Log_Procedure]  
							@LogAction		= 'INSERT - NEW', 
							@LogNote		= 'New Records',
							@LogProcedure	= @RoutineName,
							@LogSQL			= 'Insert Into [bld].[FileProperties]',
							@LogRowCount	= @@ROWCOUNT,
							@Log_TimeStart  = @StartDateTime,
							@Log_TimeEnd    = @EndDateTime;
	
	PRINT '-- changed records:'
	SET @StartDateTime = getdate()
	
		INSERT INTO [bld].[FileProperties]
	( 
		[BK] ,
		[Code] ,
		[Description] ,
		[FileMask] ,
		[Filename] ,
		[FileSystem] ,
		[Folder] ,
		[isPGP] ,
		[ExpectedFileCount] ,
		[ExpectedFileSize] ,
		[bk_schedule_FileExpected] ,
		[DateInFileNameFormat] ,
		[DateinFileNameLength] ,
		[DateInFileNameStartPos] ,
		[DateInFileNameExpression] ,
		[TestDateInFileName] ,
		[FF_Name] ,
		[FF_Fileformat] ,
		[FF_ColumnDelimiter] ,
		[FF_RowDelimiter] ,
		[FF_QuoteCharacter] ,
		[FF_CompressionLevel] ,
		[FF_CompressionType] ,
		[FF_EnableCDC] ,
		[FF_EscapeCharacter] ,
		[FF_FileEncoding] ,
		[FF_FirstRow] ,
		[FF_FirstRowAsHeader] ,
		[FF_Filesize] ,
		[FF_Threshold] 
		, [mta_BK], [mta_BKH], [mta_RH], [mta_Source], [mta_RecType]) 
	SELECT 
		src.[BK] ,
		src.[Code] ,
		src.[Description] ,
		src.[FileMask] ,
		src.[Filename] ,
		src.[FileSystem] ,
		src.[Folder] ,
		src.[isPGP] ,
		src.[ExpectedFileCount] ,
		src.[ExpectedFileSize] ,
		src.[bk_schedule_FileExpected] ,
		src.[DateInFileNameFormat] ,
		src.[DateinFileNameLength] ,
		src.[DateInFileNameStartPos] ,
		src.[DateInFileNameExpression] ,
		src.[TestDateInFileName] ,
		src.[FF_Name] ,
		src.[FF_Fileformat] ,
		src.[FF_ColumnDelimiter] ,
		src.[FF_RowDelimiter] ,
		src.[FF_QuoteCharacter] ,
		src.[FF_CompressionLevel] ,
		src.[FF_CompressionType] ,
		src.[FF_EnableCDC] ,
		src.[FF_EscapeCharacter] ,
		src.[FF_FileEncoding] ,
		src.[FF_FirstRow] ,
		src.[FF_FirstRowAsHeader] ,
		src.[FF_Filesize] ,
		src.[FF_Threshold] 
		, h.[mta_BK], h.[mta_BKH], h.[mta_RH], h.[mta_Source], h.[mta_RecType]
	FROM  [bld].[tr_110_FileProperties_010_DatasetSrc] src
	JOIN #110_FileProperties_010_DatasetSrc h ON h.[mta_BK] = src.[BK]
	WHERE 1=1 AND CAST(h.mta_RecType AS int) = 0

	
	SET @EndDateTime = getutcdate()
	EXEC [aud].[proc_Log_Procedure]  
												@LogAction		= 'INSERT - CHG', 
												@LogNote		= 'Changed Records',
												@LogProcedure	= @RoutineName,
												@LogSQL			= 'Insert Into [bld].[FileProperties]',
												@LogRowCount	= @@ROWCOUNT,
												@Log_TimeStart  = @StartDateTime,
												@Log_TimeEnd    = @EndDateTime;
	
	PRINT '-- deleted records:'
	
	SET @StartDateTime = getdate()
	
	INSERT INTO [bld].[FileProperties]
	
	( 
	
		[BK] ,
		[Code] ,
		[Description] ,
		[FileMask] ,
		[Filename] ,
		[FileSystem] ,
		[Folder] ,
		[isPGP] ,
		[ExpectedFileCount] ,
		[ExpectedFileSize] ,
		[bk_schedule_FileExpected] ,
		[DateInFileNameFormat] ,
		[DateinFileNameLength] ,
		[DateInFileNameStartPos] ,
		[DateInFileNameExpression] ,
		[TestDateInFileName] ,
		[FF_Name] ,
		[FF_Fileformat] ,
		[FF_ColumnDelimiter] ,
		[FF_RowDelimiter] ,
		[FF_QuoteCharacter] ,
		[FF_CompressionLevel] ,
		[FF_CompressionType] ,
		[FF_EnableCDC] ,
		[FF_EscapeCharacter] ,
		[FF_FileEncoding] ,
		[FF_FirstRow] ,
		[FF_FirstRowAsHeader] ,
		[FF_Filesize] ,
		[FF_Threshold] 
		, [mta_BK], [mta_BKH], [mta_RH], [mta_Source], [mta_RecType]) 
	SELECT 
		src.[BK] ,
		src.[Code] ,
		src.[Description] ,
		src.[FileMask] ,
		src.[Filename] ,
		src.[FileSystem] ,
		src.[Folder] ,
		src.[isPGP] ,
		src.[ExpectedFileCount] ,
		src.[ExpectedFileSize] ,
		src.[bk_schedule_FileExpected] ,
		src.[DateInFileNameFormat] ,
		src.[DateinFileNameLength] ,
		src.[DateInFileNameStartPos] ,
		src.[DateInFileNameExpression] ,
		src.[TestDateInFileName] ,
		src.[FF_Name] ,
		src.[FF_Fileformat] ,
		src.[FF_ColumnDelimiter] ,
		src.[FF_RowDelimiter] ,
		src.[FF_QuoteCharacter] ,
		src.[FF_CompressionLevel] ,
		src.[FF_CompressionType] ,
		src.[FF_EnableCDC] ,
		src.[FF_EscapeCharacter] ,
		src.[FF_FileEncoding] ,
		src.[FF_FirstRow] ,
		src.[FF_FirstRowAsHeader] ,
		src.[FF_Filesize] ,
		src.[FF_Threshold] 
		, src.[mta_BK], src.[mta_BKH], src.[mta_RH], src.[mta_Source], [mta_RecType] = -1
	FROM  [bld].[vw_FileProperties] src
	LEFT JOIN #110_FileProperties_010_DatasetSrc h ON h.[mta_BKH] = src.[mta_BKH] AND h.[mta_Source] = src.[mta_Source]
	WHERE 1=1 AND h.[mta_BKH] IS null AND  src.mta_Source = '[bld].[tr_110_FileProperties_010_DatasetSrc]'
	
	
	SET @EndDateTime = getutcdate()
	EXEC [aud].[proc_Log_Procedure]  
												@LogAction		= 'INSERT - DEL', 
												@LogNote		= 'Changed Deleted',
												@LogProcedure	= @RoutineName,
												@LogSQL			= 'Insert Into [bld].[FileProperties]',
												@LogRowCount	= @@ROWCOUNT,
												@Log_TimeStart  = @StartDateTime,
												@Log_TimeEnd    = @EndDateTime
												;
	
	-- Clean up ...
	IF OBJECT_ID('tempdb..#110_FileProperties_010_DatasetSrc') IS NOT NULL 
DROP TABLE #110_FileProperties_010_DatasetSrc;
	
	SET @EndDateTime =  getutcdate()
	SET @Duration = datediff(SS,@StartDateTime, @EndDateTime)
	PRINT 'Load "load_110_FileProperties_010_DatasetSrc" took ' +CAST(@Duration AS varchar(10))+ ' second(s)'