
	create proc [bld].[load_400_DatasetDependency_010_SrcToTgt] as
	/*
	Proc is generated by	: metro
	Generated at			: 2025-01-06 14:43:27
	
	exec [bld].[load_400_DatasetDependency_010_SrcToTgt]*/

	
	Declare @RoutineName	varchar(8000)	= 'load_400_DatasetDependency_010_SrcToTgt'
	Declare @StartDateTime	datetime2		=  getutcdate()
	Declare @EndDateTime	datetime2		
	Declare @Duration		bigint



	-- Create a helper temp table
	If OBJECT_ID('tempdb..#400_DatasetDependency_010_SrcToTgt') IS NOT NULL 
	Drop Table #400_DatasetDependency_010_SrcToTgt ;
	Print '-- create temp table:'
	Select
	  mta_BK		= src.[BK]
	, mta_BKH		= Convert(char(64),(Hashbytes('sha2_512',upper(src.BK) )),2)
	, mta_RH		= Convert(char(64),(Hashbytes('sha2_512',upper(
								ISNULL(Cast(src.[BK] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[BK_Parent] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[BK_Child] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[Code] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[TableTypeParent] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[TableTypeChild] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[DependencyType] as varchar(8000)),'-') 
							))),2)
	, mta_Source	= '[bld].[tr_400_DatasetDependency_010_SrcToTgt]'
	, mta_RecType	= case 
												when tgt.[BK] is null then 1
												when tgt.[mta_RH] !=  Convert(char(64),(Hashbytes('sha2_512',upper(ISNULL(Cast(src.[BK] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[BK_Parent] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[BK_Child] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[Code] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[TableTypeParent] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[TableTypeChild] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[DependencyType] as varchar(8000)),'-') ))),2)
						then 0
						else -99 end
	
	Into #400_DatasetDependency_010_SrcToTgt
	From [bld].[tr_400_DatasetDependency_010_SrcToTgt] src
	Left join [bld].[vw_DatasetDependency] tgt on src.[BK] = tgt.[BK]
	
	
	
	Create Clustered INDEX [IX_tr_400_DatasetDependency_010_SrcToTgt] ON #400_DatasetDependency_010_SrcToTgt( [mta_BKH] ASC,[mta_RH] ASC)
	
	
	--------------------- start loading data
	
	Print '-- new records:'
	
	set @StartDateTime = getdate()
	
	Insert Into [bld].[DatasetDependency]
	( 
		[BK] ,[BK_Parent] ,[BK_Child] ,[Code] ,[TableTypeParent] ,[TableTypeChild] ,[DependencyType] 
		, [mta_BK], [mta_BKH], [mta_RH], [mta_Source], [mta_RecType]) 
	select 
		src.[BK] ,src.[BK_Parent] ,src.[BK_Child] ,src.[Code] ,src.[TableTypeParent] ,src.[TableTypeChild] ,src.[DependencyType] 
		, h.[mta_BK], h.[mta_BKH], h.[mta_RH], h.[mta_Source], h.[mta_RecType]
	From  [bld].[tr_400_DatasetDependency_010_SrcToTgt] src
	Join #400_DatasetDependency_010_SrcToTgt h on h.[mta_BK] = src.[BK]
	Left Join [bld].[vw_DatasetDependency] tgt on h.[mta_BKH] = tgt.[mta_BKH] 
	Where 1=1 and cast(h.mta_RecType as int) = 1 and tgt.[mta_BKH] is null
	
	
	set @EndDateTime = getutcdate()
	exec [aud].[proc_Log_Procedure]  
							@LogAction		= 'INSERT - NEW', 
							@LogNote		= 'New Records',
							@LogProcedure	= @RoutineName,
							@LogSQL			= 'Insert Into [bld].[DatasetDependency]',
							@LogRowCount	= @@ROWCOUNT,
							@Log_TimeStart  = @StartDateTime,
							@Log_TimeEnd    = @EndDateTime;
	
	Print '-- changed records:'
	set @StartDateTime = getdate()
	
		Insert Into [bld].[DatasetDependency]
	( 
		[BK] ,[BK_Parent] ,[BK_Child] ,[Code] ,[TableTypeParent] ,[TableTypeChild] ,[DependencyType] 
		, [mta_BK], [mta_BKH], [mta_RH], [mta_Source], [mta_RecType]) 
	select 
		src.[BK] ,src.[BK_Parent] ,src.[BK_Child] ,src.[Code] ,src.[TableTypeParent] ,src.[TableTypeChild] ,src.[DependencyType] 
		, h.[mta_BK], h.[mta_BKH], h.[mta_RH], h.[mta_Source], h.[mta_RecType]
	From  [bld].[tr_400_DatasetDependency_010_SrcToTgt] src
	Join #400_DatasetDependency_010_SrcToTgt h on h.[mta_BK] = src.[BK]
	Where 1=1 and cast(h.mta_RecType as int) = 0

	
	set @EndDateTime = getutcdate()
	exec [aud].[proc_Log_Procedure]  
												@LogAction		= 'INSERT - CHG', 
												@LogNote		= 'Changed Records',
												@LogProcedure	= @RoutineName,
												@LogSQL			= 'Insert Into [bld].[DatasetDependency]',
												@LogRowCount	= @@ROWCOUNT,
												@Log_TimeStart  = @StartDateTime,
												@Log_TimeEnd    = @EndDateTime;
	
	Print '-- deleted records:'
	
	set @StartDateTime = getdate()
	
	Insert Into [bld].[DatasetDependency]
	
	( 
	
		[BK] ,[BK_Parent] ,[BK_Child] ,[Code] ,[TableTypeParent] ,[TableTypeChild] ,[DependencyType] 
		, [mta_BK], [mta_BKH], [mta_RH], [mta_Source], [mta_RecType]) 
	select 
		src.[BK] ,src.[BK_Parent] ,src.[BK_Child] ,src.[Code] ,src.[TableTypeParent] ,src.[TableTypeChild] ,src.[DependencyType] 
		, src.[mta_BK], src.[mta_BKH], src.[mta_RH], src.[mta_Source], [mta_RecType] = -1
	From  [bld].[vw_DatasetDependency] src
	Left Join #400_DatasetDependency_010_SrcToTgt h on h.[mta_BKH] = src.[mta_BKH] and h.[mta_Source] = src.[mta_Source]
	Where 1=1 and h.[mta_BKH] is null and  src.mta_Source = '[bld].[tr_400_DatasetDependency_010_SrcToTgt]'
	
	
	set @EndDateTime = getutcdate()
	exec [aud].[proc_Log_Procedure]  
												@LogAction		= 'INSERT - DEL', 
												@LogNote		= 'Changed Deleted',
												@LogProcedure	= @RoutineName,
												@LogSQL			= 'Insert Into [bld].[DatasetDependency]',
												@LogRowCount	= @@ROWCOUNT,
												@Log_TimeStart  = @StartDateTime,
												@Log_TimeEnd    = @EndDateTime
												;
	
	-- Clean up ...
	If OBJECT_ID('tempdb..#400_DatasetDependency_010_SrcToTgt') IS NOT NULL 
Drop Table #400_DatasetDependency_010_SrcToTgt;
	
	set @EndDateTime =  getutcdate()
	set @Duration = datediff(ss,@StartDateTime, @EndDateTime)
	print 'Load "load_400_DatasetDependency_010_SrcToTgt" took ' +cast(@Duration as varchar(10))+ ' second(s)'