
	CREATE PROC [bld].[load_550_Schedule_010_default] AS
	/*
	Proc is generated by	: metro
	Generated at			: 2025-01-21 08:32:56
	
	exec [bld].[load_550_Schedule_010_default]*/

	
	DECLARE @RoutineName	varchar(8000)	= 'load_550_Schedule_010_default'
	DECLARE @StartDateTime	datetime2		=  getutcdate()
	DECLARE @EndDateTime	datetime2		
	DECLARE @Duration		bigint



	-- Create a helper temp table
	IF OBJECT_ID('tempdb..#550_Schedule_010_default') IS NOT NULL 
	DROP TABLE #550_Schedule_010_default ;
	PRINT '-- create temp table:'
	SELECT
	  mta_BK		= src.[BK]
	, mta_BKH		= CONVERT(char(64),(Hashbytes('sha2_512',upper(src.BK) )),2)
	, mta_RH		= CONVERT(char(64),(Hashbytes('sha2_512',upper(
								ISNULL(CAST(src.[BK] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[Code] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[BK_Schedule] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[ScheduleCode] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[ScheduleName] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[ScheduleDesc] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[StartDate] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[EndDate] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[StartTime] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[EndTime] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[BK_ScheduleType] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[ScheduleTypeCode] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[ScheduleTypeName] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[BK_ScheduleFrequency] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[ScheduleFrequencyCode] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[ScheduleFrequencyName] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[BK_ScheduleDailyInterval] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[ScheduleDailyIntervalCode] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[ScheduleDailyIntervalName] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[BK_ScheduleWeeklyInterval] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[ScheduleWeeklyIntervalCode] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[ScheduleWeeklyIntervalName] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[BK_ScheduleWorkDayInterval] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[ScheduleWorkDayIntervalCode] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[ScheduleWorkDayIntervalName] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[BK_ScheduleMonthlyInterval] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[ScheduleMonthlyIntervalCode] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[ScheduleMonthlyIntervalName] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[BK_ScheduleQuarterlyInterval] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[ScheduleQuarterlyIntervalCode] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[ScheduleQuarterlyIntervalName] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[BK_ScheduleYearlyInterval] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[ScheduleYearlyIntervalCode] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[ScheduleYearlyIntervalName] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[BK_ScheduleSpecials] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[ScheduleSpecialsCode] AS varchar(8000)),'-')
								+'|'
								+ISNULL(CAST(src.[ScheduleSpecialsName] AS varchar(8000)),'-') 
							))),2)
	, mta_Source	= '[bld].[tr_550_Schedule_010_default]'
	, mta_RecType	= CASE 
												WHEN tgt.[BK] IS null THEN 1
												WHEN
												    tgt.[mta_RH]
												    !=  CONVERT(
												        char(64),
												        (
												            Hashbytes(
												                'sha2_512',
												                upper(
												                    ISNULL(CAST(src.[BK] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[Code] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[BK_Schedule] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[ScheduleCode] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[ScheduleName] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[ScheduleDesc] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[StartDate] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[EndDate] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[StartTime] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[EndTime] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[BK_ScheduleType] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[ScheduleTypeCode] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[ScheduleTypeName] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[BK_ScheduleFrequency] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[ScheduleFrequencyCode] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[ScheduleFrequencyName] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[BK_ScheduleDailyInterval] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[ScheduleDailyIntervalCode] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[ScheduleDailyIntervalName] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[BK_ScheduleWeeklyInterval] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[ScheduleWeeklyIntervalCode] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[ScheduleWeeklyIntervalName] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[BK_ScheduleWorkDayInterval] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[ScheduleWorkDayIntervalCode] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[ScheduleWorkDayIntervalName] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[BK_ScheduleMonthlyInterval] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[ScheduleMonthlyIntervalCode] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[ScheduleMonthlyIntervalName] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[BK_ScheduleQuarterlyInterval] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[ScheduleQuarterlyIntervalCode] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[ScheduleQuarterlyIntervalName] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[BK_ScheduleYearlyInterval] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[ScheduleYearlyIntervalCode] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[ScheduleYearlyIntervalName] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[BK_ScheduleSpecials] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[ScheduleSpecialsCode] AS varchar(8000)),'-')
												                    +'|'
												                    +ISNULL(CAST(src.[ScheduleSpecialsName] AS varchar(8000)),'-')
												                )
												            )
												        ),
												        2
												    )
						THEN 0
						ELSE -99 END
	
	INTO #550_Schedule_010_default
	FROM [bld].[tr_550_Schedule_010_default] src
	LEFT JOIN [bld].[vw_Schedule] tgt ON src.[BK] = tgt.[BK]
	
	
	
	CREATE CLUSTERED INDEX [IX_tr_550_Schedule_010_default] ON #550_Schedule_010_default( [mta_BKH] ASC,[mta_RH] ASC)
	
	
	--------------------- start loading data
	
	PRINT '-- new records:'
	
	SET @StartDateTime = getdate()
	
	INSERT INTO [bld].[Schedule]
	( 
		[BK] ,
		[Code] ,
		[BK_Schedule] ,
		[ScheduleCode] ,
		[ScheduleName] ,
		[ScheduleDesc] ,
		[StartDate] ,
		[EndDate] ,
		[StartTime] ,
		[EndTime] ,
		[BK_ScheduleType] ,
		[ScheduleTypeCode] ,
		[ScheduleTypeName] ,
		[BK_ScheduleFrequency] ,
		[ScheduleFrequencyCode] ,
		[ScheduleFrequencyName] ,
		[BK_ScheduleDailyInterval] ,
		[ScheduleDailyIntervalCode] ,
		[ScheduleDailyIntervalName] ,
		[BK_ScheduleWeeklyInterval] ,
		[ScheduleWeeklyIntervalCode] ,
		[ScheduleWeeklyIntervalName] ,
		[BK_ScheduleWorkDayInterval] ,
		[ScheduleWorkDayIntervalCode] ,
		[ScheduleWorkDayIntervalName] ,
		[BK_ScheduleMonthlyInterval] ,
		[ScheduleMonthlyIntervalCode] ,
		[ScheduleMonthlyIntervalName] ,
		[BK_ScheduleQuarterlyInterval] ,
		[ScheduleQuarterlyIntervalCode] ,
		[ScheduleQuarterlyIntervalName] ,
		[BK_ScheduleYearlyInterval] ,
		[ScheduleYearlyIntervalCode] ,
		[ScheduleYearlyIntervalName] ,
		[BK_ScheduleSpecials] ,
		[ScheduleSpecialsCode] ,
		[ScheduleSpecialsName] 
		, [mta_BK], [mta_BKH], [mta_RH], [mta_Source], [mta_RecType]) 
	SELECT 
		src.[BK] ,
		src.[Code] ,
		src.[BK_Schedule] ,
		src.[ScheduleCode] ,
		src.[ScheduleName] ,
		src.[ScheduleDesc] ,
		src.[StartDate] ,
		src.[EndDate] ,
		src.[StartTime] ,
		src.[EndTime] ,
		src.[BK_ScheduleType] ,
		src.[ScheduleTypeCode] ,
		src.[ScheduleTypeName] ,
		src.[BK_ScheduleFrequency] ,
		src.[ScheduleFrequencyCode] ,
		src.[ScheduleFrequencyName] ,
		src.[BK_ScheduleDailyInterval] ,
		src.[ScheduleDailyIntervalCode] ,
		src.[ScheduleDailyIntervalName] ,
		src.[BK_ScheduleWeeklyInterval] ,
		src.[ScheduleWeeklyIntervalCode] ,
		src.[ScheduleWeeklyIntervalName] ,
		src.[BK_ScheduleWorkDayInterval] ,
		src.[ScheduleWorkDayIntervalCode] ,
		src.[ScheduleWorkDayIntervalName] ,
		src.[BK_ScheduleMonthlyInterval] ,
		src.[ScheduleMonthlyIntervalCode] ,
		src.[ScheduleMonthlyIntervalName] ,
		src.[BK_ScheduleQuarterlyInterval] ,
		src.[ScheduleQuarterlyIntervalCode] ,
		src.[ScheduleQuarterlyIntervalName] ,
		src.[BK_ScheduleYearlyInterval] ,
		src.[ScheduleYearlyIntervalCode] ,
		src.[ScheduleYearlyIntervalName] ,
		src.[BK_ScheduleSpecials] ,
		src.[ScheduleSpecialsCode] ,
		src.[ScheduleSpecialsName] 
		, h.[mta_BK], h.[mta_BKH], h.[mta_RH], h.[mta_Source], h.[mta_RecType]
	FROM  [bld].[tr_550_Schedule_010_default] src
	JOIN #550_Schedule_010_default h ON h.[mta_BK] = src.[BK]
	LEFT JOIN [bld].[vw_Schedule] tgt ON h.[mta_BKH] = tgt.[mta_BKH] 
	WHERE 1=1 AND CAST(h.mta_RecType AS int) = 1 AND tgt.[mta_BKH] IS null
	
	
	SET @EndDateTime = getutcdate()
	EXEC [aud].[proc_Log_Procedure]  
							@LogAction		= 'INSERT - NEW', 
							@LogNote		= 'New Records',
							@LogProcedure	= @RoutineName,
							@LogSQL			= 'Insert Into [bld].[Schedule]',
							@LogRowCount	= @@ROWCOUNT,
							@Log_TimeStart  = @StartDateTime,
							@Log_TimeEnd    = @EndDateTime;
	
	PRINT '-- changed records:'
	SET @StartDateTime = getdate()
	
		INSERT INTO [bld].[Schedule]
	( 
		[BK] ,
		[Code] ,
		[BK_Schedule] ,
		[ScheduleCode] ,
		[ScheduleName] ,
		[ScheduleDesc] ,
		[StartDate] ,
		[EndDate] ,
		[StartTime] ,
		[EndTime] ,
		[BK_ScheduleType] ,
		[ScheduleTypeCode] ,
		[ScheduleTypeName] ,
		[BK_ScheduleFrequency] ,
		[ScheduleFrequencyCode] ,
		[ScheduleFrequencyName] ,
		[BK_ScheduleDailyInterval] ,
		[ScheduleDailyIntervalCode] ,
		[ScheduleDailyIntervalName] ,
		[BK_ScheduleWeeklyInterval] ,
		[ScheduleWeeklyIntervalCode] ,
		[ScheduleWeeklyIntervalName] ,
		[BK_ScheduleWorkDayInterval] ,
		[ScheduleWorkDayIntervalCode] ,
		[ScheduleWorkDayIntervalName] ,
		[BK_ScheduleMonthlyInterval] ,
		[ScheduleMonthlyIntervalCode] ,
		[ScheduleMonthlyIntervalName] ,
		[BK_ScheduleQuarterlyInterval] ,
		[ScheduleQuarterlyIntervalCode] ,
		[ScheduleQuarterlyIntervalName] ,
		[BK_ScheduleYearlyInterval] ,
		[ScheduleYearlyIntervalCode] ,
		[ScheduleYearlyIntervalName] ,
		[BK_ScheduleSpecials] ,
		[ScheduleSpecialsCode] ,
		[ScheduleSpecialsName] 
		, [mta_BK], [mta_BKH], [mta_RH], [mta_Source], [mta_RecType]) 
	SELECT 
		src.[BK] ,
		src.[Code] ,
		src.[BK_Schedule] ,
		src.[ScheduleCode] ,
		src.[ScheduleName] ,
		src.[ScheduleDesc] ,
		src.[StartDate] ,
		src.[EndDate] ,
		src.[StartTime] ,
		src.[EndTime] ,
		src.[BK_ScheduleType] ,
		src.[ScheduleTypeCode] ,
		src.[ScheduleTypeName] ,
		src.[BK_ScheduleFrequency] ,
		src.[ScheduleFrequencyCode] ,
		src.[ScheduleFrequencyName] ,
		src.[BK_ScheduleDailyInterval] ,
		src.[ScheduleDailyIntervalCode] ,
		src.[ScheduleDailyIntervalName] ,
		src.[BK_ScheduleWeeklyInterval] ,
		src.[ScheduleWeeklyIntervalCode] ,
		src.[ScheduleWeeklyIntervalName] ,
		src.[BK_ScheduleWorkDayInterval] ,
		src.[ScheduleWorkDayIntervalCode] ,
		src.[ScheduleWorkDayIntervalName] ,
		src.[BK_ScheduleMonthlyInterval] ,
		src.[ScheduleMonthlyIntervalCode] ,
		src.[ScheduleMonthlyIntervalName] ,
		src.[BK_ScheduleQuarterlyInterval] ,
		src.[ScheduleQuarterlyIntervalCode] ,
		src.[ScheduleQuarterlyIntervalName] ,
		src.[BK_ScheduleYearlyInterval] ,
		src.[ScheduleYearlyIntervalCode] ,
		src.[ScheduleYearlyIntervalName] ,
		src.[BK_ScheduleSpecials] ,
		src.[ScheduleSpecialsCode] ,
		src.[ScheduleSpecialsName] 
		, h.[mta_BK], h.[mta_BKH], h.[mta_RH], h.[mta_Source], h.[mta_RecType]
	FROM  [bld].[tr_550_Schedule_010_default] src
	JOIN #550_Schedule_010_default h ON h.[mta_BK] = src.[BK]
	WHERE 1=1 AND CAST(h.mta_RecType AS int) = 0

	
	SET @EndDateTime = getutcdate()
	EXEC [aud].[proc_Log_Procedure]  
												@LogAction		= 'INSERT - CHG', 
												@LogNote		= 'Changed Records',
												@LogProcedure	= @RoutineName,
												@LogSQL			= 'Insert Into [bld].[Schedule]',
												@LogRowCount	= @@ROWCOUNT,
												@Log_TimeStart  = @StartDateTime,
												@Log_TimeEnd    = @EndDateTime;
	
	PRINT '-- deleted records:'
	
	SET @StartDateTime = getdate()
	
	INSERT INTO [bld].[Schedule]
	
	( 
	
		[BK] ,
		[Code] ,
		[BK_Schedule] ,
		[ScheduleCode] ,
		[ScheduleName] ,
		[ScheduleDesc] ,
		[StartDate] ,
		[EndDate] ,
		[StartTime] ,
		[EndTime] ,
		[BK_ScheduleType] ,
		[ScheduleTypeCode] ,
		[ScheduleTypeName] ,
		[BK_ScheduleFrequency] ,
		[ScheduleFrequencyCode] ,
		[ScheduleFrequencyName] ,
		[BK_ScheduleDailyInterval] ,
		[ScheduleDailyIntervalCode] ,
		[ScheduleDailyIntervalName] ,
		[BK_ScheduleWeeklyInterval] ,
		[ScheduleWeeklyIntervalCode] ,
		[ScheduleWeeklyIntervalName] ,
		[BK_ScheduleWorkDayInterval] ,
		[ScheduleWorkDayIntervalCode] ,
		[ScheduleWorkDayIntervalName] ,
		[BK_ScheduleMonthlyInterval] ,
		[ScheduleMonthlyIntervalCode] ,
		[ScheduleMonthlyIntervalName] ,
		[BK_ScheduleQuarterlyInterval] ,
		[ScheduleQuarterlyIntervalCode] ,
		[ScheduleQuarterlyIntervalName] ,
		[BK_ScheduleYearlyInterval] ,
		[ScheduleYearlyIntervalCode] ,
		[ScheduleYearlyIntervalName] ,
		[BK_ScheduleSpecials] ,
		[ScheduleSpecialsCode] ,
		[ScheduleSpecialsName] 
		, [mta_BK], [mta_BKH], [mta_RH], [mta_Source], [mta_RecType]) 
	SELECT 
		src.[BK] ,
		src.[Code] ,
		src.[BK_Schedule] ,
		src.[ScheduleCode] ,
		src.[ScheduleName] ,
		src.[ScheduleDesc] ,
		src.[StartDate] ,
		src.[EndDate] ,
		src.[StartTime] ,
		src.[EndTime] ,
		src.[BK_ScheduleType] ,
		src.[ScheduleTypeCode] ,
		src.[ScheduleTypeName] ,
		src.[BK_ScheduleFrequency] ,
		src.[ScheduleFrequencyCode] ,
		src.[ScheduleFrequencyName] ,
		src.[BK_ScheduleDailyInterval] ,
		src.[ScheduleDailyIntervalCode] ,
		src.[ScheduleDailyIntervalName] ,
		src.[BK_ScheduleWeeklyInterval] ,
		src.[ScheduleWeeklyIntervalCode] ,
		src.[ScheduleWeeklyIntervalName] ,
		src.[BK_ScheduleWorkDayInterval] ,
		src.[ScheduleWorkDayIntervalCode] ,
		src.[ScheduleWorkDayIntervalName] ,
		src.[BK_ScheduleMonthlyInterval] ,
		src.[ScheduleMonthlyIntervalCode] ,
		src.[ScheduleMonthlyIntervalName] ,
		src.[BK_ScheduleQuarterlyInterval] ,
		src.[ScheduleQuarterlyIntervalCode] ,
		src.[ScheduleQuarterlyIntervalName] ,
		src.[BK_ScheduleYearlyInterval] ,
		src.[ScheduleYearlyIntervalCode] ,
		src.[ScheduleYearlyIntervalName] ,
		src.[BK_ScheduleSpecials] ,
		src.[ScheduleSpecialsCode] ,
		src.[ScheduleSpecialsName] 
		, src.[mta_BK], src.[mta_BKH], src.[mta_RH], src.[mta_Source], [mta_RecType] = -1
	FROM  [bld].[vw_Schedule] src
	LEFT JOIN #550_Schedule_010_default h ON h.[mta_BKH] = src.[mta_BKH] AND h.[mta_Source] = src.[mta_Source]
	WHERE 1=1 AND h.[mta_BKH] IS null AND  src.mta_Source = '[bld].[tr_550_Schedule_010_default]'
	
	
	SET @EndDateTime = getutcdate()
	EXEC [aud].[proc_Log_Procedure]  
												@LogAction		= 'INSERT - DEL', 
												@LogNote		= 'Changed Deleted',
												@LogProcedure	= @RoutineName,
												@LogSQL			= 'Insert Into [bld].[Schedule]',
												@LogRowCount	= @@ROWCOUNT,
												@Log_TimeStart  = @StartDateTime,
												@Log_TimeEnd    = @EndDateTime
												;
	
	-- Clean up ...
	IF OBJECT_ID('tempdb..#550_Schedule_010_default') IS NOT NULL 
DROP TABLE #550_Schedule_010_default;
	
	SET @EndDateTime =  getutcdate()
	SET @Duration = datediff(SS,@StartDateTime, @EndDateTime)
	PRINT 'Load "load_550_Schedule_010_default" took ' +CAST(@Duration AS varchar(10))+ ' second(s)'