
CREATE proc [bld].[load_900_deployscripts_010_metroprocedure] AS /*
	Proc is generated by	: metro
	Generated at			: 2025-01-06 14:43:28

	exec [bld].[load_900_DeployScripts_010_MetroProcedure]*/  DECLARE @routinename varchar(8000) = 'load_900_DeployScripts_010_MetroProcedure' DECLARE @startdatetime datetime2 = getutcdate() DECLARE @enddatetime datetime2 DECLARE @duration bigint -- Create a helper temp table
 IF object_id('tempdb..#900_DeployScripts_010_MetroProcedure') IS NOT NULL
DROP TABLE # 900_deployscripts_010_metroprocedure ; PRINT '-- create temp table:'
SELECT mta_bk = src.[bk] ,

       mta_bkh = convert(char(64),(hashbytes('sha2_512', upper(src.bk))),2) ,

       mta_rh = convert(char(64),(hashbytes('sha2_512', upper(isnull(cast(src.[bk] AS varchar(8000)), '-') + '|' + isnull(cast(src.[code] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_template] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_dataset] AS varchar(8000)), '-') + '|' + isnull(cast(src.[tgt_objectname] AS varchar(8000)), '-') + '|' + isnull(cast(src.[objecttype] AS varchar(8000)), '-') + '|' + isnull(cast(src.[objecttypedeployorder] AS varchar(8000)), '-') + '|' + isnull(cast(src.[templatetype] AS varchar(8000)), '-') + '|' + isnull(cast(src.[scriptlanguagecode] AS varchar(8000)), '-') + '|' + isnull(cast(src.[scriptlanguage] AS varchar(8000)), '-') + '|' + isnull(cast(src.[templatesource] AS varchar(8000)), '-') + '|' + isnull(cast(src.[templatename] AS varchar(8000)), '-') + '|' + isnull(cast(src.[templatescript] AS varchar(8000)), '-') + '|' + isnull(cast(src.[templateversion] AS varchar(8000)), '-') + '|' + isnull(cast(src.[todeploy] AS varchar(8000)), '-')))),2) ,

       mta_source = '[bld].[tr_900_DeployScripts_010_MetroProcedure]' ,

       mta_rectype = CASE
                         WHEN tgt.[bk] IS NULL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            THEN 1

            WHEN tgt.[mta_rh] != convert(char(64),(hashbytes('sha2_512', upper(isnull(cast(src.[bk] AS varchar(8000)), '-') + '|' + isnull(cast(src.[code] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_template] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_dataset] AS varchar(8000)), '-') + '|' + isnull(cast(src.[tgt_objectname] AS varchar(8000)), '-') + '|' + isnull(cast(src.[objecttype] AS varchar(8000)), '-') + '|' + isnull(cast(src.[objecttypedeployorder] AS varchar(8000)), '-') + '|' + isnull(cast(src.[templatetype] AS varchar(8000)), '-') + '|' + isnull(cast(src.[scriptlanguagecode] AS varchar(8000)), '-') + '|' + isnull(cast(src.[scriptlanguage] AS varchar(8000)), '-') + '|' + isnull(cast(src.[templatesource] AS varchar(8000)), '-') + '|' + isnull(cast(src.[templatename] AS varchar(8000)), '-') + '|' + isnull(cast(src.[templatescript] AS varchar(8000)), '-') + '|' + isnull(cast(src.[templateversion] AS varchar(8000)), '-') + '|' + isnull(cast(src.[todeploy] AS varchar(8000)), '-')))),2) THEN 0

            ELSE -99

             END INTO # 900_deployscripts_010_metroprocedure

  FROM [bld].[tr_900_deployscripts_010_metroprocedure] src

  LEFT JOIN [bld].[vw_deployscripts] tgt
    ON src.[bk] = tgt.[bk]
CREATE clustered INDEX [ix_tr_900_deployscripts_010_metroprocedure]
    ON # 900_deployscripts_010_metroprocedure([mta_bkh] ASC, [mta_rh] ASC) --------------------- start loading data
 PRINT '-- new records:'

   SET @startdatetime = getdate()
INSERT INTO [bld].[deployscripts] ([bk], [code], [bk_template], [bk_dataset], [tgt_objectname], [objecttype], [objecttypedeployorder], [templatetype], [scriptlanguagecode], [scriptlanguage], [templatesource], [templatename], [templatescript], [templateversion], [todeploy] , [mta_bk], [mta_bkh], [mta_rh], [mta_source], [mta_rectype])
SELECT src.[bk],

       src.[code],

       src.[bk_template],

       src.[bk_dataset],

       src.[tgt_objectname],

       src.[objecttype],

       src.[objecttypedeployorder],

       src.[templatetype],

       src.[scriptlanguagecode],

       src.[scriptlanguage],

       src.[templatesource],

       src.[templatename],

       src.[templatescript],

       src.[templateversion],

       src.[todeploy] ,

       h.[mta_bk],

       h.[mta_bkh],

       h.[mta_rh],

       h.[mta_source],

       h.[mta_rectype]

  FROM [bld].[tr_900_deployscripts_010_metroprocedure] src

  JOIN # 900_deployscripts_010_metroprocedure h
    ON h.[mta_bk] = src.[bk]

  LEFT JOIN [bld].[vw_deployscripts] tgt
    ON h.[mta_bkh] = tgt.[mta_bkh]

 WHERE 1 = 1

   AND cast(h.mta_rectype AS int) = 1

   AND tgt.[mta_bkh] IS NULL

   SET @enddatetime = getutcdate() EXEC [aud].[proc_log_procedure] @logaction = 'INSERT - NEW',

       @lognote = 'New Records',

       @logprocedure = @routinename,

       @logsql = 'Insert Into [bld].[DeployScripts]',

       @logrowcount = @@ rowcount,

       @log_timestart = @startdatetime,

       @log_timeend = @enddatetime; PRINT '-- changed records:'

   SET @startdatetime = getdate()
  INSERT INTO [bld].[deployscripts] ([bk], [code], [bk_template], [bk_dataset], [tgt_objectname], [objecttype], [objecttypedeployorder], [templatetype], [scriptlanguagecode], [scriptlanguage], [templatesource], [templatename], [templatescript], [templateversion], [todeploy] , [mta_bk], [mta_bkh], [mta_rh], [mta_source], [mta_rectype])
SELECT src.[bk],

       src.[code],

       src.[bk_template],

       src.[bk_dataset],

       src.[tgt_objectname],

       src.[objecttype],

       src.[objecttypedeployorder],

       src.[templatetype],

       src.[scriptlanguagecode],

       src.[scriptlanguage],

       src.[templatesource],

       src.[templatename],

       src.[templatescript],

       src.[templateversion],

       src.[todeploy] ,

       h.[mta_bk],

       h.[mta_bkh],

       h.[mta_rh],

       h.[mta_source],

       h.[mta_rectype]

  FROM [bld].[tr_900_deployscripts_010_metroprocedure] src

  JOIN # 900_deployscripts_010_metroprocedure h
    ON h.[mta_bk] = src.[bk]

 WHERE 1 = 1

   AND cast(h.mta_rectype AS int) = 0

   SET @enddatetime = getutcdate() EXEC [aud].[proc_log_procedure] @logaction = 'INSERT - CHG',

       @lognote = 'Changed Records',

       @logprocedure = @routinename,

       @logsql = 'Insert Into [bld].[DeployScripts]',

       @logrowcount = @@ rowcount,

       @log_timestart = @startdatetime,

       @log_timeend = @enddatetime; PRINT '-- deleted records:'

   SET @startdatetime = getdate()
  INSERT INTO [bld].[deployscripts] ([bk], [code], [bk_template], [bk_dataset], [tgt_objectname], [objecttype], [objecttypedeployorder], [templatetype], [scriptlanguagecode], [scriptlanguage], [templatesource], [templatename], [templatescript], [templateversion], [todeploy] , [mta_bk], [mta_bkh], [mta_rh], [mta_source], [mta_rectype])
SELECT src.[bk],

       src.[code],

       src.[bk_template],

       src.[bk_dataset],

       src.[tgt_objectname],

       src.[objecttype],

       src.[objecttypedeployorder],

       src.[templatetype],

       src.[scriptlanguagecode],

       src.[scriptlanguage],

       src.[templatesource],

       src.[templatename],

       src.[templatescript],

       src.[templateversion],

       src.[todeploy] ,

       src.[mta_bk],

       src.[mta_bkh],

       src.[mta_rh],

       src.[mta_source],

       [mta_rectype] = -1

  FROM [bld].[vw_deployscripts] src

  LEFT JOIN # 900_deployscripts_010_metroprocedure h
    ON h.[mta_bkh] = src.[mta_bkh]

   AND h.[mta_source] = src.[mta_source]

 WHERE 1 = 1

   AND h.[mta_bkh] IS NULL

   AND src.mta_source = '[bld].[tr_900_DeployScripts_010_MetroProcedure]'

   SET @enddatetime = getutcdate() EXEC [aud].[proc_log_procedure] @logaction = 'INSERT - DEL',

       @lognote = 'Changed Deleted',

       @logprocedure = @routinename,

       @logsql = 'Insert Into [bld].[DeployScripts]',

       @logrowcount = @@ rowcount,

       @log_timestart = @startdatetime,

       @log_timeend = @enddatetime ; -- Clean up ...
 IF object_id('tempdb..#900_DeployScripts_010_MetroProcedure') IS NOT NULL
  DROP TABLE # 900_deployscripts_010_metroprocedure;

   SET @enddatetime = getutcdate()

   SET @duration = datediff(ss, @startdatetime, @enddatetime) PRINT 'Load "load_900_DeployScripts_010_MetroProcedure" took ' + cast(@duration AS varchar(10)) + ' second(s)'
