
	create proc [bld].[load_050_Schema_010_Default] as
	/*
	Proc is generated by	: metro
	Generated at			: 2025-01-06 14:43:26
	
	exec [bld].[load_050_Schema_010_Default]*/

	
	Declare @RoutineName	varchar(8000)	= 'load_050_Schema_010_Default'
	Declare @StartDateTime	datetime2		=  getutcdate()
	Declare @EndDateTime	datetime2		
	Declare @Duration		bigint



	-- Create a helper temp table
	If OBJECT_ID('tempdb..#050_Schema_010_Default') IS NOT NULL 
	Drop Table #050_Schema_010_Default ;
	Print '-- create temp table:'
	Select
	  mta_BK		= src.[BK]
	, mta_BKH		= Convert(char(64),(Hashbytes('sha2_512',upper(src.BK) )),2)
	, mta_RH		= Convert(char(64),(Hashbytes('sha2_512',upper(
								ISNULL(Cast(src.[BK] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[Code] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[Name] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[BK_Schema] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[BK_Layer] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[BK_DataSource] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[BK_LinkedService] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[SchemaCode] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[SchemaName] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[DataSourceCode] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[DataSourceName] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[BK_DataSourceType] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[DataSourceTypeCode] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[DataSourceTypeName] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[LayerCode] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[LayerName] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[LayerOrder] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[ProcessOrderLayer] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[ProcessParallel] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[isDWH] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[isSRC] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[isTGT] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[IsRep] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[CreateDummies] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[LinkedServiceCode] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[LinkedServiceName] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[BK_Template_Create] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[BK_Template_Load] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[BK_RefType_ToChar] as varchar(8000)),'-') 
							))),2)
	, mta_Source	= '[bld].[tr_050_Schema_010_Default]'
	, mta_RecType	= case 
												when tgt.[BK] is null then 1
												when tgt.[mta_RH] !=  Convert(char(64),(Hashbytes('sha2_512',upper(ISNULL(Cast(src.[BK] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[Code] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[Name] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[BK_Schema] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[BK_Layer] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[BK_DataSource] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[BK_LinkedService] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[SchemaCode] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[SchemaName] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[DataSourceCode] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[DataSourceName] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[BK_DataSourceType] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[DataSourceTypeCode] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[DataSourceTypeName] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[LayerCode] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[LayerName] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[LayerOrder] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[ProcessOrderLayer] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[ProcessParallel] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[isDWH] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[isSRC] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[isTGT] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[IsRep] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[CreateDummies] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[LinkedServiceCode] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[LinkedServiceName] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[BK_Template_Create] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[BK_Template_Load] as varchar(8000)),'-') +'|'+ISNULL(Cast(src.[BK_RefType_ToChar] as varchar(8000)),'-') ))),2)
						then 0
						else -99 end
	
	Into #050_Schema_010_Default
	From [bld].[tr_050_Schema_010_Default] src
	Left join [bld].[vw_Schema] tgt on src.[BK] = tgt.[BK]
	
	
	
	Create Clustered INDEX [IX_tr_050_Schema_010_Default] ON #050_Schema_010_Default( [mta_BKH] ASC,[mta_RH] ASC)
	
	
	--------------------- start loading data
	
	Print '-- new records:'
	
	set @StartDateTime = getdate()
	
	Insert Into [bld].[Schema]
	( 
		[BK] ,[Code] ,[Name] ,[BK_Schema] ,[BK_Layer] ,[BK_DataSource] ,[BK_LinkedService] ,[SchemaCode] ,[SchemaName] ,[DataSourceCode] ,[DataSourceName] ,[BK_DataSourceType] ,[DataSourceTypeCode] ,[DataSourceTypeName] ,[LayerCode] ,[LayerName] ,[LayerOrder] ,[ProcessOrderLayer] ,[ProcessParallel] ,[isDWH] ,[isSRC] ,[isTGT] ,[IsRep] ,[CreateDummies] ,[LinkedServiceCode] ,[LinkedServiceName] ,[BK_Template_Create] ,[BK_Template_Load] ,[BK_RefType_ToChar] 
		, [mta_BK], [mta_BKH], [mta_RH], [mta_Source], [mta_RecType]) 
	select 
		src.[BK] ,src.[Code] ,src.[Name] ,src.[BK_Schema] ,src.[BK_Layer] ,src.[BK_DataSource] ,src.[BK_LinkedService] ,src.[SchemaCode] ,src.[SchemaName] ,src.[DataSourceCode] ,src.[DataSourceName] ,src.[BK_DataSourceType] ,src.[DataSourceTypeCode] ,src.[DataSourceTypeName] ,src.[LayerCode] ,src.[LayerName] ,src.[LayerOrder] ,src.[ProcessOrderLayer] ,src.[ProcessParallel] ,src.[isDWH] ,src.[isSRC] ,src.[isTGT] ,src.[IsRep] ,src.[CreateDummies] ,src.[LinkedServiceCode] ,src.[LinkedServiceName] ,src.[BK_Template_Create] ,src.[BK_Template_Load] ,src.[BK_RefType_ToChar] 
		, h.[mta_BK], h.[mta_BKH], h.[mta_RH], h.[mta_Source], h.[mta_RecType]
	From  [bld].[tr_050_Schema_010_Default] src
	Join #050_Schema_010_Default h on h.[mta_BK] = src.[BK]
	Left Join [bld].[vw_Schema] tgt on h.[mta_BKH] = tgt.[mta_BKH] 
	Where 1=1 and cast(h.mta_RecType as int) = 1 and tgt.[mta_BKH] is null
	
	
	set @EndDateTime = getutcdate()
	exec [aud].[proc_Log_Procedure]  
							@LogAction		= 'INSERT - NEW', 
							@LogNote		= 'New Records',
							@LogProcedure	= @RoutineName,
							@LogSQL			= 'Insert Into [bld].[Schema]',
							@LogRowCount	= @@ROWCOUNT,
							@Log_TimeStart  = @StartDateTime,
							@Log_TimeEnd    = @EndDateTime;
	
	Print '-- changed records:'
	set @StartDateTime = getdate()
	
		Insert Into [bld].[Schema]
	( 
		[BK] ,[Code] ,[Name] ,[BK_Schema] ,[BK_Layer] ,[BK_DataSource] ,[BK_LinkedService] ,[SchemaCode] ,[SchemaName] ,[DataSourceCode] ,[DataSourceName] ,[BK_DataSourceType] ,[DataSourceTypeCode] ,[DataSourceTypeName] ,[LayerCode] ,[LayerName] ,[LayerOrder] ,[ProcessOrderLayer] ,[ProcessParallel] ,[isDWH] ,[isSRC] ,[isTGT] ,[IsRep] ,[CreateDummies] ,[LinkedServiceCode] ,[LinkedServiceName] ,[BK_Template_Create] ,[BK_Template_Load] ,[BK_RefType_ToChar] 
		, [mta_BK], [mta_BKH], [mta_RH], [mta_Source], [mta_RecType]) 
	select 
		src.[BK] ,src.[Code] ,src.[Name] ,src.[BK_Schema] ,src.[BK_Layer] ,src.[BK_DataSource] ,src.[BK_LinkedService] ,src.[SchemaCode] ,src.[SchemaName] ,src.[DataSourceCode] ,src.[DataSourceName] ,src.[BK_DataSourceType] ,src.[DataSourceTypeCode] ,src.[DataSourceTypeName] ,src.[LayerCode] ,src.[LayerName] ,src.[LayerOrder] ,src.[ProcessOrderLayer] ,src.[ProcessParallel] ,src.[isDWH] ,src.[isSRC] ,src.[isTGT] ,src.[IsRep] ,src.[CreateDummies] ,src.[LinkedServiceCode] ,src.[LinkedServiceName] ,src.[BK_Template_Create] ,src.[BK_Template_Load] ,src.[BK_RefType_ToChar] 
		, h.[mta_BK], h.[mta_BKH], h.[mta_RH], h.[mta_Source], h.[mta_RecType]
	From  [bld].[tr_050_Schema_010_Default] src
	Join #050_Schema_010_Default h on h.[mta_BK] = src.[BK]
	Where 1=1 and cast(h.mta_RecType as int) = 0

	
	set @EndDateTime = getutcdate()
	exec [aud].[proc_Log_Procedure]  
												@LogAction		= 'INSERT - CHG', 
												@LogNote		= 'Changed Records',
												@LogProcedure	= @RoutineName,
												@LogSQL			= 'Insert Into [bld].[Schema]',
												@LogRowCount	= @@ROWCOUNT,
												@Log_TimeStart  = @StartDateTime,
												@Log_TimeEnd    = @EndDateTime;
	
	Print '-- deleted records:'
	
	set @StartDateTime = getdate()
	
	Insert Into [bld].[Schema]
	
	( 
	
		[BK] ,[Code] ,[Name] ,[BK_Schema] ,[BK_Layer] ,[BK_DataSource] ,[BK_LinkedService] ,[SchemaCode] ,[SchemaName] ,[DataSourceCode] ,[DataSourceName] ,[BK_DataSourceType] ,[DataSourceTypeCode] ,[DataSourceTypeName] ,[LayerCode] ,[LayerName] ,[LayerOrder] ,[ProcessOrderLayer] ,[ProcessParallel] ,[isDWH] ,[isSRC] ,[isTGT] ,[IsRep] ,[CreateDummies] ,[LinkedServiceCode] ,[LinkedServiceName] ,[BK_Template_Create] ,[BK_Template_Load] ,[BK_RefType_ToChar] 
		, [mta_BK], [mta_BKH], [mta_RH], [mta_Source], [mta_RecType]) 
	select 
		src.[BK] ,src.[Code] ,src.[Name] ,src.[BK_Schema] ,src.[BK_Layer] ,src.[BK_DataSource] ,src.[BK_LinkedService] ,src.[SchemaCode] ,src.[SchemaName] ,src.[DataSourceCode] ,src.[DataSourceName] ,src.[BK_DataSourceType] ,src.[DataSourceTypeCode] ,src.[DataSourceTypeName] ,src.[LayerCode] ,src.[LayerName] ,src.[LayerOrder] ,src.[ProcessOrderLayer] ,src.[ProcessParallel] ,src.[isDWH] ,src.[isSRC] ,src.[isTGT] ,src.[IsRep] ,src.[CreateDummies] ,src.[LinkedServiceCode] ,src.[LinkedServiceName] ,src.[BK_Template_Create] ,src.[BK_Template_Load] ,src.[BK_RefType_ToChar] 
		, src.[mta_BK], src.[mta_BKH], src.[mta_RH], src.[mta_Source], [mta_RecType] = -1
	From  [bld].[vw_Schema] src
	Left Join #050_Schema_010_Default h on h.[mta_BKH] = src.[mta_BKH] and h.[mta_Source] = src.[mta_Source]
	Where 1=1 and h.[mta_BKH] is null and  src.mta_Source = '[bld].[tr_050_Schema_010_Default]'
	
	
	set @EndDateTime = getutcdate()
	exec [aud].[proc_Log_Procedure]  
												@LogAction		= 'INSERT - DEL', 
												@LogNote		= 'Changed Deleted',
												@LogProcedure	= @RoutineName,
												@LogSQL			= 'Insert Into [bld].[Schema]',
												@LogRowCount	= @@ROWCOUNT,
												@Log_TimeStart  = @StartDateTime,
												@Log_TimeEnd    = @EndDateTime
												;
	
	-- Clean up ...
	If OBJECT_ID('tempdb..#050_Schema_010_Default') IS NOT NULL 
Drop Table #050_Schema_010_Default;
	
	set @EndDateTime =  getutcdate()
	set @Duration = datediff(ss,@StartDateTime, @EndDateTime)
	print 'Load "load_050_Schema_010_Default" took ' +cast(@Duration as varchar(10))+ ' second(s)'