
CREATE proc [bld].[load_420_loaddependency_010_srctotgt] AS /*
	Proc is generated by	: metro
	Generated at			: 2025-01-06 14:43:27

	exec [bld].[load_420_LoadDependency_010_SrcToTgt]*/  DECLARE @routinename varchar(8000) = 'load_420_LoadDependency_010_SrcToTgt' DECLARE @startdatetime datetime2 = getutcdate() DECLARE @enddatetime datetime2 DECLARE @duration bigint -- Create a helper temp table
 IF object_id('tempdb..#420_LoadDependency_010_SrcToTgt') IS NOT NULL
DROP TABLE # 420_loaddependency_010_srctotgt ; PRINT '-- create temp table:'
SELECT mta_bk = src.[bk] ,

       mta_bkh = convert(char(64),(hashbytes('sha2_512', upper(src.bk))),2) ,

       mta_rh = convert(char(64),(hashbytes('sha2_512', upper(isnull(cast(src.[bk] AS varchar(8000)), '-') + '|' + isnull(cast(src.[code] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_target] AS varchar(8000)), '-') + '|' + isnull(cast(src.[tgt_layer] AS varchar(8000)), '-') + '|' + isnull(cast(src.[tgt_schema] AS varchar(8000)), '-') + '|' + isnull(cast(src.[tgt_group] AS varchar(8000)), '-') + '|' + isnull(cast(src.[tgt_shortname] AS varchar(8000)), '-') + '|' + isnull(cast(src.[tgt_code] AS varchar(8000)), '-') + '|' + isnull(cast(src.[tgt_datasetname] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_source] AS varchar(8000)), '-') + '|' + isnull(cast(src.[src_layer] AS varchar(8000)), '-') + '|' + isnull(cast(src.[src_schema] AS varchar(8000)), '-') + '|' + isnull(cast(src.[src_group] AS varchar(8000)), '-') + '|' + isnull(cast(src.[src_shortname] AS varchar(8000)), '-') + '|' + isnull(cast(src.[src_code] AS varchar(8000)), '-') + '|' + isnull(cast(src.[src_datasetname] AS varchar(8000)), '-') + '|' + isnull(cast(src.[dependencytype] AS varchar(8000)), '-') + '|' + isnull(cast(src.[generation_number] AS varchar(8000)), '-')))),2) ,

       mta_source = '[bld].[tr_420_LoadDependency_010_SrcToTgt]' ,

       mta_rectype = CASE
                         WHEN tgt.[bk] IS NULL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         THEN 1

            WHEN tgt.[mta_rh] != convert(char(64),(hashbytes('sha2_512', upper(isnull(cast(src.[bk] AS varchar(8000)), '-') + '|' + isnull(cast(src.[code] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_target] AS varchar(8000)), '-') + '|' + isnull(cast(src.[tgt_layer] AS varchar(8000)), '-') + '|' + isnull(cast(src.[tgt_schema] AS varchar(8000)), '-') + '|' + isnull(cast(src.[tgt_group] AS varchar(8000)), '-') + '|' + isnull(cast(src.[tgt_shortname] AS varchar(8000)), '-') + '|' + isnull(cast(src.[tgt_code] AS varchar(8000)), '-') + '|' + isnull(cast(src.[tgt_datasetname] AS varchar(8000)), '-') + '|' + isnull(cast(src.[bk_source] AS varchar(8000)), '-') + '|' + isnull(cast(src.[src_layer] AS varchar(8000)), '-') + '|' + isnull(cast(src.[src_schema] AS varchar(8000)), '-') + '|' + isnull(cast(src.[src_group] AS varchar(8000)), '-') + '|' + isnull(cast(src.[src_shortname] AS varchar(8000)), '-') + '|' + isnull(cast(src.[src_code] AS varchar(8000)), '-') + '|' + isnull(cast(src.[src_datasetname] AS varchar(8000)), '-') + '|' + isnull(cast(src.[dependencytype] AS varchar(8000)), '-') + '|' + isnull(cast(src.[generation_number] AS varchar(8000)), '-')))),2) THEN 0

            ELSE -99

             END INTO # 420_loaddependency_010_srctotgt

  FROM [bld].[tr_420_loaddependency_010_srctotgt] src

  LEFT JOIN [bld].[vw_loaddependency] tgt
    ON src.[bk] = tgt.[bk]
CREATE clustered INDEX [ix_tr_420_loaddependency_010_srctotgt]
    ON # 420_loaddependency_010_srctotgt([mta_bkh] ASC, [mta_rh] ASC) --------------------- start loading data
 PRINT '-- new records:'

   SET @startdatetime = getdate()
INSERT INTO [bld].[loaddependency] ([bk], [code], [bk_target], [tgt_layer], [tgt_schema], [tgt_group], [tgt_shortname], [tgt_code], [tgt_datasetname], [bk_source], [src_layer], [src_schema], [src_group], [src_shortname], [src_code], [src_datasetname], [dependencytype], [generation_number] , [mta_bk], [mta_bkh], [mta_rh], [mta_source], [mta_rectype])
SELECT src.[bk],

       src.[code],

       src.[bk_target],

       src.[tgt_layer],

       src.[tgt_schema],

       src.[tgt_group],

       src.[tgt_shortname],

       src.[tgt_code],

       src.[tgt_datasetname],

       src.[bk_source],

       src.[src_layer],

       src.[src_schema],

       src.[src_group],

       src.[src_shortname],

       src.[src_code],

       src.[src_datasetname],

       src.[dependencytype],

       src.[generation_number] ,

       h.[mta_bk],

       h.[mta_bkh],

       h.[mta_rh],

       h.[mta_source],

       h.[mta_rectype]

  FROM [bld].[tr_420_loaddependency_010_srctotgt] src

  JOIN # 420_loaddependency_010_srctotgt h
    ON h.[mta_bk] = src.[bk]

  LEFT JOIN [bld].[vw_loaddependency] tgt
    ON h.[mta_bkh] = tgt.[mta_bkh]

 WHERE 1 = 1

   AND cast(h.mta_rectype AS int) = 1

   AND tgt.[mta_bkh] IS NULL

   SET @enddatetime = getutcdate() EXEC [aud].[proc_log_procedure] @logaction = 'INSERT - NEW',

       @lognote = 'New Records',

       @logprocedure = @routinename,

       @logsql = 'Insert Into [bld].[LoadDependency]',

       @logrowcount = @@ rowcount,

       @log_timestart = @startdatetime,

       @log_timeend = @enddatetime; PRINT '-- changed records:'

   SET @startdatetime = getdate()
  INSERT INTO [bld].[loaddependency] ([bk], [code], [bk_target], [tgt_layer], [tgt_schema], [tgt_group], [tgt_shortname], [tgt_code], [tgt_datasetname], [bk_source], [src_layer], [src_schema], [src_group], [src_shortname], [src_code], [src_datasetname], [dependencytype], [generation_number] , [mta_bk], [mta_bkh], [mta_rh], [mta_source], [mta_rectype])
SELECT src.[bk],

       src.[code],

       src.[bk_target],

       src.[tgt_layer],

       src.[tgt_schema],

       src.[tgt_group],

       src.[tgt_shortname],

       src.[tgt_code],

       src.[tgt_datasetname],

       src.[bk_source],

       src.[src_layer],

       src.[src_schema],

       src.[src_group],

       src.[src_shortname],

       src.[src_code],

       src.[src_datasetname],

       src.[dependencytype],

       src.[generation_number] ,

       h.[mta_bk],

       h.[mta_bkh],

       h.[mta_rh],

       h.[mta_source],

       h.[mta_rectype]

  FROM [bld].[tr_420_loaddependency_010_srctotgt] src

  JOIN # 420_loaddependency_010_srctotgt h
    ON h.[mta_bk] = src.[bk]

 WHERE 1 = 1

   AND cast(h.mta_rectype AS int) = 0

   SET @enddatetime = getutcdate() EXEC [aud].[proc_log_procedure] @logaction = 'INSERT - CHG',

       @lognote = 'Changed Records',

       @logprocedure = @routinename,

       @logsql = 'Insert Into [bld].[LoadDependency]',

       @logrowcount = @@ rowcount,

       @log_timestart = @startdatetime,

       @log_timeend = @enddatetime; PRINT '-- deleted records:'

   SET @startdatetime = getdate()
  INSERT INTO [bld].[loaddependency] ([bk], [code], [bk_target], [tgt_layer], [tgt_schema], [tgt_group], [tgt_shortname], [tgt_code], [tgt_datasetname], [bk_source], [src_layer], [src_schema], [src_group], [src_shortname], [src_code], [src_datasetname], [dependencytype], [generation_number] , [mta_bk], [mta_bkh], [mta_rh], [mta_source], [mta_rectype])
SELECT src.[bk],

       src.[code],

       src.[bk_target],

       src.[tgt_layer],

       src.[tgt_schema],

       src.[tgt_group],

       src.[tgt_shortname],

       src.[tgt_code],

       src.[tgt_datasetname],

       src.[bk_source],

       src.[src_layer],

       src.[src_schema],

       src.[src_group],

       src.[src_shortname],

       src.[src_code],

       src.[src_datasetname],

       src.[dependencytype],

       src.[generation_number] ,

       src.[mta_bk],

       src.[mta_bkh],

       src.[mta_rh],

       src.[mta_source],

       [mta_rectype] = -1

  FROM [bld].[vw_loaddependency] src

  LEFT JOIN # 420_loaddependency_010_srctotgt h
    ON h.[mta_bkh] = src.[mta_bkh]

   AND h.[mta_source] = src.[mta_source]

 WHERE 1 = 1

   AND h.[mta_bkh] IS NULL

   AND src.mta_source = '[bld].[tr_420_LoadDependency_010_SrcToTgt]'

   SET @enddatetime = getutcdate() EXEC [aud].[proc_log_procedure] @logaction = 'INSERT - DEL',

       @lognote = 'Changed Deleted',

       @logprocedure = @routinename,

       @logsql = 'Insert Into [bld].[LoadDependency]',

       @logrowcount = @@ rowcount,

       @log_timestart = @startdatetime,

       @log_timeend = @enddatetime ; -- Clean up ...
 IF object_id('tempdb..#420_LoadDependency_010_SrcToTgt') IS NOT NULL
  DROP TABLE # 420_loaddependency_010_srctotgt;

   SET @enddatetime = getutcdate()

   SET @duration = datediff(ss, @startdatetime, @enddatetime) PRINT 'Load "load_420_LoadDependency_010_SrcToTgt" took ' + cast(@duration AS varchar(10)) + ' second(s)'
