permissions:
  contents: write
  actions: read
  pull-requests: write

name: Clean SQL Files

on: [push, pull_request]

jobs:
  clean_sql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install SQLFluff
      run: pip install sqlfluff

    - name: Find and clean SQL files
      run: |
        find . -name "*.sql" | while read sqlfile; do
          echo "Cleaning $sqlfile"
          sqlfluff fix "$sqlfile" --dialect tsql --rules L010,L016 --exclude-rules L014 --ignore parsing --FIX-EVEN-UNPARSABLE
        done

    - name: Check if there are changes to commit
      run: git diff --exit-code || echo "Changes detected"

    - name: Commit changes
      if: success() && steps.check.outputs.changes_detected == 'true'
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Automated SQL formatting with SQLFluff"
    
    - name: Push changes
      if: success() && steps.check.outputs.changes_detected == 'true'
      run: git push origin HEAD:automated-sql-formatting

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Automated SQL formatting with SQLFluff"
        branch: automated-sql-formatting
        title: "Automated SQL formatting with SQLFluff"
        body: "This pull request contains automated SQL formatting with SQLFluff."


        
        
      
      