permissions:
  contents: write
  actions: read

name: Clean SQL Files

on: [push, pull_request]

jobs:
  clean_sql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install SQLFluff
      run: pip install sqlfluff

    - name: Find and clean SQL files
      run: |
        find . -name "*.sql" | while read sqlfile; do
          echo "Cleaning $sqlfile"
          sqlfluff fix "$sqlfile" --force
        done

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Automated SQL formatting with SQLFluff"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}